Repository exadel-inc/esl, pull requests merged in 2021-12, with the labels that each got.

#689 feat(esl-utils): `ESLVSizeCSSProxy` utility to fix 100vh problem is introduced
  pages/src/common/viewport.ts
  pages/src/localdev.ts
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/fixes/viewport.ts
Labels: feature

#698 epic: esl-animate
  package.json
  pages/src/common/flex.less
  pages/src/common/helpers.less
  pages/src/common/simple-grid.less
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/src/navigation/footer/footer.less
  pages/views/_includes/landing/benefits.njk
  pages/views/_includes/landing/promo-banner.njk
  pages/views/components/esl-animate.njk
  pages/views/examples/animate.njk
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-animate/README.md
  src/modules/esl-animate/core.less
  src/modules/esl-animate/core.ts
  src/modules/esl-animate/core/esl-animate-animations.less
  src/modules/esl-animate/core/esl-animate-service.ts
  src/modules/esl-animate/core/esl-animate.less
  src/modules/esl-animate/core/esl-animate.ts
  src/modules/esl-utils/async/promise.ts
  src/modules/esl-utils/dom/class.ts
  src/modules/esl-utils/fixes/viewport.ts
Labels: feature

#715 style: add animated icon representation for esl-animate example
  pages/static/assets/examples/animate.svg
  pages/views/examples/animate.njk
Labels: documentation

#688 feat: support for continues click on the scrollbar area
  pages/views/examples/scrollbar.njk
  src/modules/esl-scrollbar/core/esl-scrollbar.shape.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-utils/dom/events.ts
  src/modules/esl-utils/dom/test/events.test.ts
Labels: feature, not ready for merge

#725 chore: `actions/setup-node@v1` migrated to `actions/setup-node@v2`
  .github/workflows/commit.yml
  .github/workflows/pages.yml
  .github/workflows/release.yml
  .github/workflows/test-pack.yml
  .github/workflows/validate.yml
Labels: enhancement

#722 feat(esl-scrollbar): ESL Scrollbar v2.0.0 + `EventUtils` improvements
  pages/views/examples/scrollbar.njk
  src/modules/esl-scrollbar/README.md
  src/modules/esl-scrollbar/core/esl-scrollbar.shape.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-utils/dom/events.ts
  src/modules/esl-utils/dom/test/events.test.ts
Labels: enhancement, feature

#723 feat(gh-pages): GSS integration
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/src/navigation/header/header-search.less
  pages/src/navigation/header/header-search.ts
  pages/src/navigation/header/header.less
  pages/src/navigation/navigation.less
  pages/src/navigation/navigation.ts
  pages/src/navigation/sidebar/sidebar-primary-nav.less
  pages/src/page/search.less
  pages/static/assets/common/header-search.svg
  pages/static/assets/sidebar/examples.svg
  pages/static/assets/sidebar/search.svg
  pages/views/_includes/navigation/footer.njk
  pages/views/_includes/navigation/header.njk
  pages/views/_includes/navigation/sidebar.njk
  pages/views/_layouts/base.njk
  pages/views/search.njk
Labels: enhancement, feature

#731 feat(esl-toggleable): small enchancements
  src/modules/esl-toggleable/core/esl-toggleable.shape.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: enhancement

#733 fix(esl-scrollbar): fix event subscriber leak
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
Labels: bug

#734 feat(esl-panel-group): dispatch change:mode event
  src/modules/esl-panel-group/core/esl-panel-group.ts
Labels: enhancement, feature

#736 fix: toggleable fixes
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-panel/README.md
  src/modules/esl-tab/README.md
  src/modules/esl-toggleable/README.md
  src/modules/esl-trigger/README.md
Labels: bug

#746 feat(esl-toggleable): add auto id
  src/modules/esl-toggleable/README.md
  src/modules/esl-toggleable/core/esl-toggleable.shape.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: feature
