Repository exadel-inc/esl, pull requests merged in 2021-03, with the labels that each got.

#78 fix: deepCompare null check fix
  src/modules/esl-utils/misc/object.ts
  src/modules/esl-utils/misc/test/object.test.ts
Labels: bug

#81 fix: adjust group control
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.ts
Labels: bug

#80 Bugfix: esl panel animation
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
  test-server/views/pages/esl-scrollable-tab.html
Labels: bug, enhancement

#83 feat: filtration common pseudo-selectors
  src/modules/esl-traversing-query/core/esl-traversing-query.ts
  src/modules/esl-traversing-query/test/esl-traversing-query.test.ts
Labels: enhancement

#84 feat: set iframe as a default provider for valid urls
  src/modules/esl-media/providers/iframe-provider.ts
Labels: enhancement

#93 docs: release cleanup part 1
  README.md
  docs/esl-tab.html
  pages/views/pages/esl-tab.html
  src/modules/esl-a11y-group/README.md
  src/modules/esl-a11y-group/core/esl-a11y-group.ts
  src/modules/esl-alert/README.md
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-base-element/README.md
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-image/README.md
  src/modules/esl-image/core/esl-image-iobserver.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media-query/README.md
  src/modules/esl-media-query/core/esl-media-breakpoints.ts
  src/modules/esl-media-query/core/esl-media-query.ts
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-media-query/core/esl-media-rule.ts
  src/modules/esl-media/README.md
  src/modules/esl-media/core/esl-media-iobserver.ts
  src/modules/esl-media/core/esl-media-manager.ts
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-media/core/esl-media-registry.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-media/providers/brightcove-provider.ts
  src/modules/esl-media/providers/html5/audio-provider.ts
  src/modules/esl-media/providers/html5/media-provider.ts
  src/modules/esl-media/providers/html5/video-provider.ts
  src/modules/esl-media/providers/iframe-provider.ts
  src/modules/esl-media/providers/youtube-provider.ts
  src/modules/esl-scrollbar/README.md
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-traversing-query/README.md
Labels: documentation

#94 Documentation cleanup 2 + small consumer's requests
  README.md
  docs/bundles/localdev.js
  docs/contribute/commit.md
  docs/contribute/scripts.md
  docs/esl-accordion.html
  docs/esl-alert.html
  docs/esl-forms/esl-select-list.html
  docs/esl-forms/esl-select.html
  docs/esl-forms/index.html
  docs/esl-image.html
  docs/esl-media.html
  docs/esl-scrollbar.html
  docs/esl-tab.html
  docs/esl-toggleable.html
  docs/index.html
  pages/settings.json
  pages/views/pages/esl-media.html
  pages/views/pages/esl-toggleable.html
  src/modules/esl-base-trigger/README.md
  src/modules/esl-base-trigger/core.ts
  src/modules/esl-media/README.md
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-toggleable/README.md
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/README.md
  src/modules/esl-trigger/core/esl-base-trigger.ts
  src/modules/esl-trigger/core/esl-trigger.less
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-trigger/core/esl-triggers-container.ts
Labels: documentation, enhancement, feature

#98 feat: esl-trigger rewritten
  src/modules/esl-trigger/README.md
  src/modules/esl-trigger/core/esl-base-trigger.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: enhancement, feature

#100 docs: esl-select + esl-select-list + esl-tabs vs esl-tab
  docs/bundles/localdev.css
  docs/bundles/localdev.js
  docs/esl-forms/esl-select.html
  docs/esl-media.html
  docs/esl-tab.html
  pages/views/pages/esl-forms/esl-select.html
  pages/views/pages/esl-tab.html
  src/modules/esl-forms/esl-select-list/README.md
  src/modules/esl-forms/esl-select-list/core/esl-select-item.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-wrapper.ts
  src/modules/esl-forms/esl-select/README.md
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-forms/esl-select/core/esl-select-renderer.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
  src/modules/esl-tab/README.md
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-tab/core/esl-tabs.ts
Labels: documentation, enhancement

#95 docs: esl panel and esl panel group components
  package-lock.json
  pages/views/pages/esl-tab.html
  src/modules/esl-panel/README.md
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-tab/core/esl-tabs.ts
Labels: documentation

#103 CI: GH Pages cleanup and build
  .github/workflows/cla.yml
  .github/workflows/pages.yml
  .github/workflows/release.yml
  .github/workflows/validate.yml
  .gitignore
  docs/.nojekyll
  docs/bundles/localdev.css
  docs/bundles/localdev.js
  docs/bundles/polyfill-full.js
  docs/bundles/polyfill-light.js
  docs/config.yml
  docs/esl-alert.html
  docs/esl-forms/esl-select-list.html
  docs/esl-forms/esl-select.html
  docs/esl-forms/index.html
  docs/esl-image.html
  docs/esl-media.html
  docs/esl-scrollbar.html
  docs/esl-tab.html
  docs/index.html
  package-lock.json
  pages/controllers/PublishConfig.js
  pages/pages.build.js
  pages/settings.json
  pages/views/index.html
  pages/views/layouts/basic.html
  pages/views/layouts/header.html
  pages/views/pages/components/esl-accordion.html
  pages/views/pages/components/esl-alert.html
  pages/views/pages/components/esl-image.html
  pages/views/pages/components/esl-media.html
  pages/views/pages/components/esl-scrollbar.html
  pages/views/pages/components/esl-select-list.html
  pages/views/pages/components/esl-select.html
  pages/views/pages/components/esl-tab.html
  pages/views/pages/components/esl-toggleable.html
  pages/views/pages/drafts/esl-carousel/_parts/code1.html
  pages/views/pages/drafts/esl-carousel/_parts/example-text.txt
  pages/views/pages/drafts/esl-carousel/esl-multi-carousel-page-dev.html
  pages/views/pages/drafts/esl-carousel/esl-multi-carousel-page.html
  pages/views/pages/drafts/esl-carousel/esl-multi-carousel-rule.html
  pages/views/pages/drafts/esl-carousel/esl-single-carousel-page.html
  pages/views/pages/esl-accordion.html
  pages/views/pages/esl-toggleable.html
  src/modules/esl-media/core/esl-media.less
Labels: enhancement

#119 fix: dependencies vulnerability cleanup 2
  .whitesource
  package-lock.json
Labels: security fix

#120 feat: ability to refresh esl-media via esl:refresh
  src/modules/esl-media/core/esl-media.ts
Labels: enhancement, feature
