Repository exadel-inc/esl, pull requests merged in 2021-09, with the labels that each got.

#443 docs: fixes
  .github/workflows/pages.yml
  package-lock.json
  package.json
  pages/src/common/markdown.less
  pages/src/header/logo.less
  pages/src/localdev.less
  pages/static/assets/logo.svg
  pages/views/_data/md-render.js
  pages/views/_data/site.json
  pages/views/_includes/header.njk
  pages/views/components/esl-scrollbar.njk
  src/modules/esl-scrollbar/README.md
  src/modules/esl-utils/README.md
Labels: bug, enhancement

#445 feat(esl-panel-group): allows any number of open panels for accordion mode
  pages/views/samples/accordion.njk
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel-group/core/esl-panel-group.ts
Labels: feature

#446 Tech/utils cleanup
  pages/views/components/esl-media.njk
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-traversing-query/core/esl-traversing-query.ts
  src/modules/esl-utils/README.md
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/dom/api.ts
  src/modules/esl-utils/dom/rtl.ts
  src/modules/esl-utils/dom/scroll.ts
  src/modules/esl-utils/dom/traversing.ts
  src/modules/esl-utils/dom/window.ts
Labels: enhancement

#450 fix: incorrect moment of change outside action listener state
  .releaserc.json
  README.md
  docs/contribute/commit.md
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: bug

#454 fix: fix unsubscribe for outside actions
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: bug

#456 fix: toggleable and panel animation fixes
  pages/src/common/page.less
  pages/src/header/header.less
  pages/views/_includes/header-menu.njk
  pages/views/_includes/header.njk
  pages/views/samples/image.njk
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/README.md
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel/README.md
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: bug, enhancement

#461 fix: fix default target value for trigger
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: bug

#462 fix: fix allowed children for new JSX Shapes
  src/modules/esl-a11y-group/core.ts
  src/modules/esl-a11y-group/core/esl-a11y-group.shape.ts
  src/modules/esl-image/core/esl-image.shape.ts
  src/modules/esl-media/core/esl-media.shape.ts
  src/modules/esl-panel-group/core.ts
  src/modules/esl-panel-group/core/esl-panel-group.shape.ts
  src/modules/esl-panel/core.ts
  src/modules/esl-panel/core/esl-panel.shape.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.shape.ts
  src/modules/esl-tab/core.ts
  src/modules/esl-tab/core/esl-tab.shape.ts
  src/modules/esl-tab/core/esl-tabs.shape.ts
  src/modules/esl-toggleable/core.ts
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.shape.ts
  src/modules/esl-toggleable/core/esl-toggleable.shape.ts
  src/modules/esl-trigger/core.ts
  src/modules/esl-trigger/core/esl-trigger.shape.ts
Labels: bug

#478 docs: replace relative links to absolute
  src/modules/esl-a11y-group/README.md
  src/modules/esl-alert/README.md
  src/modules/esl-base-element/README.md
  src/modules/esl-footnotes/README.md
  src/modules/esl-forms/esl-select-list/README.md
  src/modules/esl-forms/esl-select/README.md
  src/modules/esl-image/README.md
  src/modules/esl-media-query/README.md
  src/modules/esl-media/README.md
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel/README.md
  src/modules/esl-popup/README.md
  src/modules/esl-scrollbar/README.md
  src/modules/esl-tab/README.md
  src/modules/esl-toggleable/README.md
  src/modules/esl-traversing-query/README.md
  src/modules/esl-trigger/README.md
  src/modules/esl-utils/README.md
Labels: documentation

#477 feat: tsx support
  eslint/coderules.eslintrc.yml
  package-lock.json
  package.json
  src/modules/esl-a11y-group/core/esl-a11y-group.shape.ts
  src/modules/esl-alert/core.ts
  src/modules/esl-alert/core/esl-alert.shape.ts
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-base-element/core.ts
  src/modules/esl-base-element/core/esl-base-element.shape.ts
  src/modules/esl-base-element/shape/dom-events.shape.ts
  src/modules/esl-base-element/shape/html-element.shape.ts
  src/modules/esl-base-element/shape/wai-aria.shape.ts
  src/modules/esl-image/core/esl-image.shape.ts
  src/modules/esl-media/core/esl-media.shape.ts
  src/modules/esl-panel-group/core/esl-panel-group.shape.ts
  src/modules/esl-panel/core/esl-panel.shape.ts
  src/modules/esl-popup/README.md
  src/modules/esl-popup/core.ts
  src/modules/esl-popup/core/esl-popup.shape.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-scrollbar/core.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.shape.ts
  src/modules/esl-tab/core/esl-tab.shape.ts
  src/modules/esl-tab/core/esl-tabs.shape.ts
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.shape.ts
  src/modules/esl-toggleable/core/esl-toggleable.shape.ts
  src/modules/esl-trigger/core/esl-trigger.shape.ts
  src/modules/lib.ts
Labels: feature

#483 fix: esl-trigger event
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-tab/core/esl-tabs.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: bug, enhancement
