Repository exadel-inc/esl, pull requests merged in 2021-05, with the labels that each got.

#183 fix: 'Stack out of bounds' exception for memoized non static member in IE
  src/modules/esl-utils/decorators/memoize.ts
Labels: bug

#193 esl-panel-group: support mode="open" to make all panels active
  package-lock.json
  pages/views/pages/basic/esl-tab.html
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-panel/core/esl-panel-group.less
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: feature

#199 epic: esl-utils updates
  src/modules/esl-utils/README.md
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/async/aggregate.ts
  src/modules/esl-utils/async/test/aggregate.test.ts
  src/modules/esl-utils/decorators/override.ts
  src/modules/esl-utils/decorators/readonly.ts
  src/modules/esl-utils/dom/focus.ts
  src/modules/esl-utils/dom/scroll.ts
  src/modules/esl-utils/dom/styles.ts
Labels: enhancement

#201 fix(esl-image): svg loading check update
  src/modules/esl-image/README.md
  src/modules/esl-image/core/esl-image.ts
Labels: bug

#206 Feature: Toggleable API changes
  pages/views/pages/basic/esl-tab.html
  src/modules/esl-panel/README.md
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-toggleable/README.md
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: enhancement

#211 fix(esl-utils): utility DeviceDetector updated to recognize iOS13
  src/modules/esl-utils/environment/device-detector.ts
Labels: bug

#219 Added alt, shift and control to the keys.ts (within HPE keycode removing)
  src/modules/esl-utils/dom/keys.ts
Labels: enhancement

#213 version updates, style-guide rework and editorconfig validation update
  .eslintrc.json
  .github/workflows/editorconfig.yml
  .github/workflows/validate.yml
  README.md
  jest.config.js
  package-lock.json
  package.json
  pages/views/error.html
  pages/views/pages/basic/esl-tab.html
  pages/views/pages/basic/esl-toggleable.html
  src/modules/draft/esl-carousel/core/esl-carousel.ts
  src/modules/draft/esl-carousel/core/view/esl-carousel-view.ts
  src/modules/draft/esl-carousel/core/view/esl-multi-carousel-view.ts
  src/modules/draft/esl-carousel/core/view/esl-single-carousel-view.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-touch.plugin.ts
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-base-element/decorators/json-attr.ts
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
  src/modules/esl-image/core/esl-image-iobserver.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/core/esl-media-manager.ts
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-media/core/esl-media-registry.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-media/providers/brightcove-provider.ts
  src/modules/esl-media/providers/html5/audio-provider.ts
  src/modules/esl-media/providers/html5/media-provider.ts
  src/modules/esl-media/providers/html5/video-provider.ts
  src/modules/esl-media/providers/youtube-provider.ts
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-popup/core.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-tab/core/esl-tabs.ts
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-utils/async/debounce.ts
  src/modules/esl-utils/async/throttle.ts
  src/modules/esl-utils/decorators/memoize.ts
  src/modules/esl-utils/misc/memoize.ts
  src/polyfills/list/es6.array.find.ts
Labels: enhancement
