Repository exadel-inc/esl, pull requests merged in 2021-11, with the labels that each got.

#609 chore: 11ty configuration enhancements
  .eslintrc.yml
  package-lock.json
  package.json
  pages/.eleventy.js
  pages/.eslintrc.yml
  pages/11ty/markdown.lib.js
  pages/11ty/prismjs.lib.js
  pages/11ty/sort.filter.js
  pages/11ty/sortByName.filter.js
  pages/src/localdev.less
  pages/views/index.njk
  tsconfig.eslint.json
Labels: enhancement

#608 docs: fix footer style
  pages/src/footer/footer.less
  pages/views/_includes/footer-menu.njk
  pages/views/_includes/footer.njk
Labels: documentation

#610 Benefits component
  pages/src/benefit-component/benefit-component.less
  pages/src/localdev.less
  pages/static/assets/common/line.svg
  pages/static/assets/icon-benefits-component/efficient.svg
  pages/static/assets/icon-benefits-component/fast.svg
  pages/static/assets/icon-benefits-component/light.svg
  pages/static/assets/icon-benefits-component/powerful.svg
  pages/static/assets/icon-benefits-component/tested.svg
  pages/static/assets/icon-benefits-component/versatile.svg
  pages/views/_data/benefit.json
  pages/views/_includes/benefit.njk
  pages/views/_layouts/landing.njk
Labels: documentation

#614 fix(esl-utils): scrollIntoViewAsync() method signature
  src/modules/esl-utils/dom/scroll.ts
Labels: bug

#613 Fix style benefit and footer
  package-lock.json
  pages/11ty/ignored.filter.js
  pages/src/benefits/benefits.less
  pages/src/footer/footer.less
  pages/src/marquee/marquee.less
  pages/src/page/landing-layout.less
  pages/views/_includes/collection-grid.njk
  pages/views/_includes/footer-menu.njk
  pages/views/_includes/footer.njk
  pages/views/_includes/landing/benefits.njk
  pages/views/_includes/landing/marquee.njk
  pages/views/components/index.njk
  pages/views/examples/index.njk
  pages/views/utils/index.njk
  src/modules/esl-utils/dom/scroll.ts
Labels: documentation

#616 refactor(gh-pages): navigation massive cleanup and bugfix
  pages/src/common/variables.less
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/src/marquee/marquee.less
  pages/src/marquee/marquee.ts
  pages/src/navigation/footer/footer-compact.less
  pages/src/navigation/footer/footer.less
  pages/src/navigation/header/header.less
  pages/src/navigation/header/logo.less
  pages/src/navigation/navigation.less
  pages/src/navigation/navigation.ts
  pages/src/navigation/sidebar/sidebar-content.less
  pages/src/navigation/sidebar/sidebar-controls.less
  pages/src/navigation/sidebar/sidebar-primary-nav.less
  pages/src/navigation/sidebar/sidebar-seccondary-nav.less
  pages/src/navigation/sidebar/sidebar.less
  pages/src/navigation/sidebar/sidebar.ts
  pages/src/page/landing-layout.less
  pages/src/page/sidebar-layout.less
  pages/src/sidebar/sidebar-menu.less
  pages/src/sidebar/sidebar-navigation.less
  pages/src/sidebar/sidebar.less
  pages/src/sidebar/sidebar.ts
  pages/views/_data/functions.js
  pages/views/_includes/landing/marquee.njk
  pages/views/_includes/navigation/footer-compact.njk
  pages/views/_includes/navigation/footer-menu.njk
  pages/views/_includes/navigation/footer.njk
  pages/views/_includes/navigation/header.njk
  pages/views/_includes/navigation/sidebar-item.njk
  pages/views/_includes/navigation/sidebar.njk
  pages/views/_includes/sidebar-menu.njk
  pages/views/_includes/sidebar.njk
  pages/views/_layouts/content.njk
  pages/views/_layouts/landing.njk
Labels: enhancement

#627 tech(redesign): sidebar imporvement
  pages/src/common/accordion.less
  pages/src/common/links.less
  pages/src/common/variables.less
  pages/src/navigation/footer/footer.less
  pages/src/navigation/header/header.less
  pages/src/navigation/sidebar/sidebar-content.less
  pages/src/navigation/sidebar/sidebar-primary-nav.less
  pages/src/navigation/sidebar/sidebar.less
  pages/src/navigation/sidebar/sidebar.ts
  pages/src/page/landing-layout.less
  pages/src/page/sidebar-layout.less
  pages/views/_includes/navigation/footer.njk
  pages/views/_includes/navigation/header.njk
  pages/views/_includes/navigation/sidebar-item.njk
  pages/views/_includes/navigation/sidebar.njk
  pages/views/_layouts/content.njk
  pages/views/_layouts/landing.njk
  pages/views/examples/accordion.njk
Labels: enhancement

#631 fix(esl-popup): fix arrow position for adjacent axis
  src/modules/esl-popup/core/esl-popup.ts
Labels: bug

#626 feat: add ability to scrollIntoView to detect when scrolling stops
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-utils/dom/scroll.ts
Labels: feature

#653 feat(esl-popup): add new feature to be able to set position of arrow on popup
  pages/views/_layouts/popup.njk
  pages/views/examples/popup.njk
  src/modules/esl-popup/core/esl-popup-position.ts
  src/modules/esl-popup/core/esl-popup.less
  src/modules/esl-popup/core/esl-popup.ts
Labels: feature

#634 feat(esl-utils): array unwrap utility
  src/modules/esl-utils/misc/array.ts
  src/modules/esl-utils/misc/object.ts
  src/modules/esl-utils/misc/test/array.test.ts
  src/modules/esl-utils/misc/test/object.test.ts
Labels: feature

#651 refactor(gh-pages): add missing ESLPanelGroup component and improve meta information
  pages/views/404.njk
  pages/views/_data/site.json
  pages/views/_includes/landing/marquee.njk
  pages/views/_layouts/base.njk
  pages/views/components/esl-alert.njk
  pages/views/components/esl-footnotes.njk
  pages/views/components/esl-image.njk
  pages/views/components/esl-media.njk
  pages/views/components/esl-panel-group.njk
  pages/views/components/esl-panel.njk
  pages/views/components/esl-popup.njk
  pages/views/components/esl-scrollbar.njk
  pages/views/components/esl-select-list.njk
  pages/views/components/esl-select.njk
  pages/views/components/esl-tabs.njk
  pages/views/components/esl-toggleable.njk
  pages/views/components/esl-trigger.njk
  pages/views/components/index.njk
  pages/views/examples/accordion.njk
  pages/views/examples/carousel.njk
  pages/views/examples/embedded-audio.njk
  pages/views/examples/embedded-video.njk
  pages/views/examples/footnotes.njk
  pages/views/examples/forms-select-list.njk
  pages/views/examples/forms-select.njk
  pages/views/examples/image.njk
  pages/views/examples/index.njk
  pages/views/examples/menu.njk
  pages/views/examples/notification.njk
  pages/views/examples/popup.njk
  pages/views/examples/scrollbar.njk
  pages/views/examples/tabs.njk
  pages/views/examples/toggleable.njk
  pages/views/index.njk
  pages/views/introduction/browser-support.njk
  pages/views/introduction/index.njk
  pages/views/introduction/roadmap.njk
  pages/views/utils/esl-a11ty-group.njk
  pages/views/utils/esl-base.njk
  pages/views/utils/esl-media-query.njk
  pages/views/utils/esl-traversing-query.njk
  pages/views/utils/esl-utils.njk
  pages/views/utils/index.njk
  src/modules/esl-panel-group/README.md
Labels: enhancement

#656 fix(esl-poup): fix popup positioning
  pages/views/_layouts/popup.njk
  src/modules/esl-popup/core/esl-popup-position.ts
  src/modules/esl-popup/core/esl-popup.less
Labels: bug

#639 feat(esl-traversing-query): add ability to restrict global scope
  src/modules/esl-traversing-query/core/esl-traversing-query.ts
  src/modules/esl-traversing-query/test/esl-traversing-query.test.ts
Labels: enhancement

#652 refactor: split light polyfill into light and medium
  pages/src/polyfill-full.ts
  pages/src/polyfill-light.ts
  pages/src/polyfill-medium.ts
  pages/views/_includes/navigation/sidebar.njk
  pages/views/_includes/polyfill.njk
  pages/webpack.config.js
Labels: documentation

#632 feat(esl-animate): make a new module "esl-animate" to animate elements on viewport intersecting
  pages/src/common/flex.less
  pages/src/common/helpers.less
  pages/src/common/simple-grid.less
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/src/navigation/footer/footer.less
  pages/views/_includes/landing/benefits.njk
  pages/views/components/esl-animate.njk
  pages/views/examples/animate.njk
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-animate/README.md
  src/modules/esl-animate/core.less
  src/modules/esl-animate/core.ts
  src/modules/esl-animate/core/esl-animate-service.ts
  src/modules/esl-animate/core/esl-animate.less
  src/modules/esl-animate/core/esl-animate.ts
Labels: feature, under discussion

#667 feat(esl-footnotes): add back-to-note-label attribute and renderIndex for connected note
  pages/views/examples/footnotes.njk
  src/modules/esl-footnotes/core/esl-footnotes-data.ts
  src/modules/esl-footnotes/core/esl-footnotes.ts
  src/modules/esl-footnotes/core/esl-note.ts
Labels: enhancement

#655 style(gh-pages): Changes to sidebar
  pages/src/navigation/sidebar/sidebar-content.less
  pages/src/navigation/sidebar/sidebar.ts
  pages/views/_includes/navigation/sidebar-item.njk
  pages/views/_includes/navigation/sidebar.njk
  pages/views/components/index.njk
  pages/views/examples/index.njk
  pages/views/utils/index.njk
Labels: enhancement
