Repository exadel-inc/esl, pull requests merged in 2021-02, with the labels that each got.

#24 fix: bind method hotfix
  src/modules/esl-utils/decorators/bind.ts
Labels: bug

#27 bugfix: image event fix
  src/modules/esl-image/core/esl-image.ts
Labels: bug, enhancement

#26 feat: popup dispatcher cleanup
  src/modules/all.less
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-base-popup/README.md
  src/modules/esl-base-popup/core.less
  src/modules/esl-base-popup/core.ts
  src/modules/esl-base-popup/core/esl-base-popup-group-manager.ts
  src/modules/esl-base-popup/core/esl-popup-dispatcher.less
  src/modules/esl-base-popup/core/esl-popup-dispatcher.ts
  src/modules/esl-utils/fixes/ie-fixes.ts
  src/modules/lib.ts
  test-server/src/localdev.ts
Labels: enhancement

#29 Feat: refactor of Panel & PanelStack
  src/modules/esl-panel/core/esl-panel-stack.less
  src/modules/esl-panel/core/esl-panel-stack.ts
  src/modules/esl-panel/core/esl-panel.ts
  test-server/views/pages/esl-scrollable-tab.html
  test-server/views/pages/esl-tab.html
Labels: enhancement, feature

#31 refactor: minor fixes of Panel & BasePopup
  src/modules/esl-base-popup/core/esl-base-popup.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: enhancement

#34 refactor: minor fixes of animation
  src/modules/esl-panel/core/esl-panel-stack.less
  src/modules/esl-panel/core/esl-panel.ts
Labels: enhancement

#38 fix: bouncing up when crossing between tabs
  src/modules/esl-panel/core/esl-panel-stack.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: enhancement

#33 POC: esl select
  src/modules/draft/all.less
  src/modules/draft/all.ts
  src/modules/draft/esl-select/core.less
  src/modules/draft/esl-select/core.ts
  src/modules/draft/esl-select/core/esl-select-dropdown.less
  src/modules/draft/esl-select/core/esl-select-dropdown.ts
  src/modules/draft/esl-select/core/esl-select-item.less
  src/modules/draft/esl-select/core/esl-select-item.ts
  src/modules/draft/esl-select/core/esl-select-list.less
  src/modules/draft/esl-select/core/esl-select-list.ts
  src/modules/draft/esl-select/core/esl-select-model.ts
  src/modules/draft/esl-select/core/esl-select-text.less
  src/modules/draft/esl-select/core/esl-select-text.ts
  src/modules/draft/esl-select/core/esl-select.less
  src/modules/draft/esl-select/core/esl-select.ts
  src/modules/esl-base-trigger/core/esl-base-trigger.ts
  test-server/src/localdev.less
  test-server/src/localdev.ts
  test-server/views/pages/esl-select.html
Labels: feature

#42 fix: a11y
  src/modules/esl-panel/core/esl-panel-stack.less
Labels: enhancement

#44 fix: fix focus and position calculation
  src/modules/draft/esl-select/core/esl-select-dropdown.ts
Labels: bug

#46 feat: add more label format for esl-select; fix select dropdown focus
  src/modules/draft/esl-select/core/esl-select-dropdown.ts
  src/modules/draft/esl-select/core/esl-select-item.less
  src/modules/draft/esl-select/core/esl-select-text.less
  src/modules/draft/esl-select/core/esl-select-text.ts
  src/modules/draft/esl-select/core/esl-select.less
  src/modules/draft/esl-select/core/esl-select.ts
Labels: bug, feature

#50 tech: styleguide upd
  .eslintrc.json
  docs/commit.md
  docs/styleguide.md
  package-lock.json
  package.json
  src/modules/draft/esl-carousel/core/esl-carousel-slide.ts
  src/modules/draft/esl-carousel/core/esl-carousel.ts
  src/modules/draft/esl-carousel/core/view/esl-carousel-view.ts
  src/modules/draft/esl-carousel/core/view/esl-multi-carousel-view.ts
  src/modules/draft/esl-carousel/core/view/esl-single-carousel-view.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-autoplay.plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-dots.plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-link.plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-touch.plugin.ts
  src/modules/draft/esl-select-list/core/esl-select-list.ts
  src/modules/draft/esl-select-list/core/esl-select-wrapper.ts
  src/modules/draft/esl-select/core/esl-select-dropdown.ts
  src/modules/draft/esl-select/core/esl-select.ts
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-image/core/esl-image-iobserver.ts
  src/modules/esl-image/core/esl-image-strategies.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/core/esl-media-iobserver.ts
  src/modules/esl-media/core/esl-media-manager.ts
  src/modules/esl-media/core/esl-media-registry.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-media/test/media-manager.test.ts
  src/modules/esl-panel/core/esl-panel-stack.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-scrollable-tabs/core/esl-scrollable-tabs.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-tab/core/esl-tabs-container.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-trigger/core/esl-triggers-container.ts
  src/modules/esl-utils/async/test/throttle.test.ts
  src/modules/esl-utils/decorators/bind.ts
Labels: enhancement

#51 TECH: popup renaming
  README.md
  src/modules/all.less
  src/modules/all.ts
  src/modules/draft/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-base-popup/core.less
  src/modules/esl-base-popup/core.ts
  src/modules/esl-base-popup/core/esl-popup-dispatcher.less
  src/modules/esl-base-trigger/README.md
  src/modules/esl-base-trigger/core/esl-base-trigger.ts
  src/modules/esl-media-query/core/esl-media-breakpoints.ts
  src/modules/esl-media-query/core/esl-media-query.ts
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-media-query/core/esl-media-rule.ts
  src/modules/esl-media-query/test/esl-media-breakpoints.test.ts
  src/modules/esl-media-query/test/esl-media-query.test.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-toggleable/README.md
  src/modules/esl-toggleable/core.less
  src/modules/esl-toggleable/core.ts
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.less
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/README.md
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/lib.ts
  test-server/src/localdev.ts
Labels: enhancement

#52 [TECH]: common naming cleanup
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
Labels: enhancement

#53 EPIC: ESL Select & ESL Select List (beta)
  .stylelintrc.json
  README.md
  package.json
  paths.json
  src/modules/all.less
  src/modules/all.ts
  src/modules/draft/all.less
  src/modules/draft/all.ts
  src/modules/esl-forms/all.less
  src/modules/esl-forms/all.ts
  src/modules/esl-forms/esl-select-list/README.md
  src/modules/esl-forms/esl-select-list/core.less
  src/modules/esl-forms/esl-select-list/core.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-item.less
  src/modules/esl-forms/esl-select-list/core/esl-select-item.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-list.less
  src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-wrapper.ts
  src/modules/esl-forms/esl-select/README.md
  src/modules/esl-forms/esl-select/core.less
  src/modules/esl-forms/esl-select/core.ts
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.less
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-forms/esl-select/core/esl-select-renderer.less
  src/modules/esl-forms/esl-select/core/esl-select-renderer.ts
  src/modules/esl-forms/esl-select/core/esl-select.less
  src/modules/esl-forms/esl-select/core/esl-select.ts
  src/modules/esl-image/core/esl-image.less
  src/modules/esl-media/core/esl-media.less
  src/modules/esl-scrollbar/core/esl-scrollbar-arrows.less
  src/modules/lib.ts
  test-server/src/localdev.ts
  test-server/views/pages/esl-forms/esl-select-list.html
  test-server/views/pages/esl-forms/esl-select.html
Labels: feature

#55 Keyboard events handling
  README.md
  src/modules/draft/esl-carousel/core/view/esl-multi-carousel-view.ts
  src/modules/esl-base-trigger/core/esl-base-trigger.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-item.less
  src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-panel/core/esl-panel-stack.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/core/esl-triggers-container.ts
  src/modules/esl-utils/README.md
  src/modules/esl-utils/dom/keycodes.ts
  src/modules/esl-utils/dom/keys.ts
  src/polyfills/list/dom.keyboard.key.ts
  src/polyfills/list/es6.array.includes.ts
  src/polyfills/polyfills.es5.ts
  src/polyfills/polyfills.es6.ts
  test-server/src/localdev.less
Labels: enhancement

#56 ESL Alert extended and became releasable
  src/modules/esl-alert/README.md
  src/modules/esl-alert/core/esl-alert.less
  src/modules/esl-alert/core/esl-alert.ts
  test-server/src/localdev.ts
  test-server/views/pages/esl-alert.html
Labels: enhancement, feature

#61 refactor!: esl-utils module export reworked
  src/modules/all.ts
  src/modules/esl-utils/all.ts
Labels: enhancement

#60 ESL Alert: a11y and cleanup
  src/modules/esl-alert/core/esl-alert.ts
  test-server/views/pages/esl-alert.html
Labels: bug, enhancement

#63 feat: esl-select basic form element proxy and reset handler fix
  src/modules/esl-forms/esl-select-list/core/esl-select-wrapper.ts
  src/modules/esl-forms/esl-select/core.less
  src/modules/esl-forms/esl-select/core/esl-select-renderer.ts
  src/modules/esl-forms/esl-select/core/esl-select.less
  src/modules/esl-forms/esl-select/core/esl-select.ts
  test-server/views/pages/esl-forms/esl-select-list.html
  test-server/views/pages/esl-forms/esl-select.html
Labels: bug, enhancement, feature

#57 [POC] refactor!: new structure for components based on the trigger container
  README.md
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-a11y-group/README.md
  src/modules/esl-a11y-group/core.less
  src/modules/esl-a11y-group/core.ts
  src/modules/esl-a11y-group/core/esl-a11y-group.less
  src/modules/esl-a11y-group/core/esl-a11y-group.ts
  src/modules/esl-panel/core.less
  src/modules/esl-panel/core.ts
  src/modules/esl-panel/core/esl-panel-group.less
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-scrollable-tabs/README.md
  src/modules/esl-scrollable-tabs/core.less
  src/modules/esl-scrollable-tabs/core.ts
  src/modules/esl-scrollable-tabs/core/esl-scrollable-tabs.ts
  src/modules/esl-tab/README.md
  src/modules/esl-tab/core.less
  src/modules/esl-tab/core.ts
  src/modules/esl-tab/core/esl-tab.less
  src/modules/esl-tab/core/esl-tabs-container.ts
  src/modules/esl-tab/core/esl-tabs.arrows.less
  src/modules/esl-tab/core/esl-tabs.less
  src/modules/esl-tab/core/esl-tabs.scrollable.less
  src/modules/esl-tab/core/esl-tabs.ts
  src/modules/esl-trigger/core.ts
  src/modules/lib.ts
  test-server/src/localdev.ts
  test-server/views/pages/esl-scrollable-tab.html
  test-server/views/pages/esl-tab.html
Labels: enhancement

#66 fix: format utility support for multiple replacements
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/test/format.test.ts
Labels: bug

#67 fix: memoize context for class member decoration
  src/modules/esl-utils/decorators/memoize.ts
  src/modules/esl-utils/decorators/test/memoize.test.ts
Labels: bug, enhancement

#69 bugfix: no scrolling for iframe provider
  src/modules/esl-media/providers/iframe-provider.ts
Labels: enhancement

#72 bugfix: smart media styles
  src/modules/esl-media/core/esl-media.less
Labels: bug, enhancement

#74 ESL Select improvements
  src/modules/esl-forms/esl-select-list/core/esl-select-wrapper.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
Labels: enhancement, feature
