Repository exadel-inc/esl, pull requests merged in 2021-06, with the labels that each got.

#227 fix: activator is not defined in hide handler
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: bug

#226 feat: extend UID utilities
  src/modules/esl-media/providers/brightcove-provider.ts
  src/modules/esl-media/providers/iframe-provider.ts
  src/modules/esl-media/providers/youtube-provider.ts
  src/modules/esl-utils/misc/test/uid.test.ts
  src/modules/esl-utils/misc/uid.ts
Labels: enhancement, feature

#229 fix: activator should be available after hide
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: bug

#231 fix(esl-utils): device detector touch detection improved
  src/modules/esl-utils/environment/device-detector.ts
Labels: bug

#216 feat: add omit function
  src/modules/esl-utils/misc/object.ts
  src/modules/esl-utils/misc/test/object.test.ts
Labels: enhancement, feature

#236 feat: github pages with eleventy
  .eleventy.js
  CHANGELOG.md
  package-lock.json
  package.json
  pages/views-11ty/includes/footer.njk
  pages/views-11ty/includes/header-menu.njk
  pages/views-11ty/includes/header.njk
  pages/views-11ty/includes/img/logo.svg
  pages/views-11ty/index.html
  pages/views-11ty/index.njk
  pages/views-11ty/layouts/basic.njk
  pages/views-11ty/layouts/html5.njk
  pages/views-11ty/pages/basic/esl-alert.njk
  pages/views-11ty/pages/basic/esl-media.njk
  pages/views-11ty/pages/forms/esl-select-list.njk
  pages/views/layouts/basic.html
  pages/views/layouts/html5.html
  src/modules/esl-utils/misc/object.ts
  src/modules/esl-utils/misc/test/object.test.ts
Labels: enhancement, feature

#240 refactor: esl-media-query cleanup for API and usages
  src/modules/esl-image/core/esl-image-strategies.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media-query/core/esl-media-query.ts
  src/modules/esl-media-query/test/esl-media-query.test.ts
Labels: enhancement

#244 fix: pseudo scroll locker styles fix
  src/modules/esl-utils/dom/scroll.less
Labels: bug

#243 epic: esl-trigger for v3.0.0
  pages/src/header/header-menu.html
  pages/views/pages/basic/esl-accordion.html
  pages/views/pages/basic/esl-toggleable.html
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media-query/core/esl-media-query.ts
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-media-query/core/esl-media-rule.ts
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/README.md
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-utils/environment/device-detector.ts
  src/modules/esl-utils/misc/object.ts
Labels: breaking-change, bug, enhancement

#247 feat: component pages on nunjucks
  .eleventy.js
  pages/src/lorem/config.json
  pages/src/lorem/lorem.html
  pages/src/lorem/lorem.js
  pages/views-11ty/404.njk
  pages/views-11ty/basic/esl-accordion.njk
  pages/views-11ty/basic/esl-alert.njk
  pages/views-11ty/basic/esl-image.njk
  pages/views-11ty/basic/esl-media.njk
  pages/views-11ty/basic/esl-scrollbar.njk
  pages/views-11ty/basic/esl-tab.njk
  pages/views-11ty/basic/esl-toggleable.njk
  pages/views-11ty/forms/esl-select-list.njk
  pages/views-11ty/forms/esl-select.njk
  pages/views-11ty/includes/header-menu.njk
  pages/views-11ty/includes/header.njk
  pages/views-11ty/includes/lorem.njk
  pages/views-11ty/index.njk
  pages/views-11ty/layouts/basic.njk
  pages/views/404.html
  pages/views/pages/basic/esl-alert.html
  pages/views/pages/basic/esl-media.html
  pages/views/pages/forms/esl-select-list.html
Labels: feature

#250 fix: additional components build
  package.json
Labels: bug

#249 fix: add polyfill prefix '/esl/' for correct url
  pages/views-11ty/layouts/basic.njk
Labels: bug

#255 Update: trigger delays
  src/modules/esl-trigger/README.md
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: enhancement

#256 refactor: rewriting drafts on nunchucks and deleting server-sketch
  package-lock.json
  package.json
  pages/controllers/PublishConfig.js
  pages/views-11ty/data/functions.js
  pages/views-11ty/drafts/esl-multi-carousel-page-dev.njk
  pages/views-11ty/drafts/esl-multi-carousel-page.njk
  pages/views-11ty/drafts/esl-multi-carousel-rule.njk
  pages/views-11ty/drafts/esl-single-carousel-page.njk
  pages/views-11ty/includes/header.njk
  pages/views/error.html
  pages/views/pages/drafts/_parts/code1.html
  pages/views/pages/drafts/_parts/example-text.txt
Labels: enhancement

#259 esl-utils: a batch of small updates and fixes
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-utils/README.md
  src/modules/esl-utils/async/aggregate.ts
  src/modules/esl-utils/dom/scroll.less
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/test/format.test.ts
  src/modules/esl-utils/misc/test/uid.test.ts
  src/modules/esl-utils/misc/uid.ts
Labels: enhancement

#263 fix(esl-toggleable): allow to register toggleable as independent component
  pages/src/localdev.ts
  pages/views/pages/basic/esl-toggleable.html
  src/modules/esl-toggleable/README.md
  src/modules/esl-toggleable/core.less
  src/modules/esl-toggleable/core/esl-toggleable.less
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: enhancement, feature

#267 docs: update development information for contributors
  .github/workflows/pages.yml
  README.md
  docs/contribute/pages.md
  docs/contribute/scripts.md
Labels: documentation

#258 epic: footnotes
  pages/src/localdev.ts
  pages/views/pages/drafts/esl-notes.html
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-footnotes/core.less
  src/modules/esl-footnotes/core.ts
  src/modules/esl-footnotes/core/esl-footnotes.less
  src/modules/esl-footnotes/core/esl-footnotes.ts
  src/modules/esl-note/core.less
  src/modules/esl-note/core.ts
  src/modules/esl-note/core/esl-note.less
  src/modules/esl-note/core/esl-note.ts
  src/modules/esl-popup/core/esl-popup.less
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-tooltip/core.less
  src/modules/esl-tooltip/core.ts
  src/modules/esl-tooltip/core/esl-tooltip.less
  src/modules/esl-tooltip/core/esl-tooltip.ts
  src/modules/lib.ts
Labels: component

#268 refactor: architecture change
  .eleventy.js
  .eslintignore
  .gitignore
  package.json
  pages/src/header/header-menu.html
  pages/views-11ty/data/env.js
  pages/views/404.njk
  pages/views/_data/env.js
  pages/views/_data/functions.js
  pages/views/_includes/footer.njk
  pages/views/_includes/header-menu.njk
  pages/views/_includes/header.njk
  pages/views/_includes/img/logo.svg
  pages/views/_includes/lorem.njk
  pages/views/_layouts/basic.njk
  pages/views/_layouts/html5.njk
  pages/views/basic/esl-accordion.njk
  pages/views/basic/esl-alert.njk
  pages/views/basic/esl-image.njk
  pages/views/basic/esl-media.njk
  pages/views/basic/esl-scrollbar.njk
  pages/views/basic/esl-tab.njk
  pages/views/basic/esl-toggleable.njk
  pages/views/drafts/esl-multi-carousel-page-dev.njk
  pages/views/drafts/esl-multi-carousel-page.njk
  pages/views/drafts/esl-multi-carousel-rule.njk
  pages/views/drafts/esl-single-carousel-page.njk
  pages/views/forms/esl-select-list.njk
  pages/views/forms/esl-select.njk
  pages/views/index.njk
  pages/webpack.config.js
Labels: enhancement

#278 fix(esl-utils): isRtl check updated to use computed styles instead of attribute
  src/modules/esl-utils/dom/rtl.ts
  src/modules/esl-utils/dom/test/rtl.test.ts
Labels: bug, enhancement
