Repository exadel-inc/esl, pull requests merged in 2021-08, with the labels that each got.

#351 GH Pages: HTML minifier and prod build for assets #291
  .eleventy.js
  package-lock.json
  package.json
  pages/views/_layouts/basic.njk
  pages/webpack.config.js
Labels: enhancement

#352 feat: ESLPopup positioning
  pages/views/_layouts/basic.njk
  pages/views/_layouts/popup.njk
  pages/views/drafts/esl-popup.njk
  src/modules/esl-popup/core/esl-popup-position.ts
  src/modules/esl-popup/core/esl-popup.less
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
  src/modules/esl-utils/dom/element.ts
  src/modules/esl-utils/dom/rect.ts
  src/modules/esl-utils/dom/scroll.ts
  src/modules/esl-utils/dom/window.ts
Labels: feature

#355 fix(esl-note): fix broken connection between esl-note and esl-footnotes
  src/modules/esl-footnotes/core/esl-footnotes.less
  src/modules/esl-footnotes/core/esl-footnotes.ts
  src/modules/esl-note/core/esl-note.ts
Labels: bug

#232 feat: media query v2
  src/modules/draft/esl-carousel/core/view/esl-carousel-view.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media-query/README.md
  src/modules/esl-media-query/core.ts
  src/modules/esl-media-query/core/common/env-shortcuts.ts
  src/modules/esl-media-query/core/common/screen-breakpoint.ts
  src/modules/esl-media-query/core/common/screen-dpr.ts
  src/modules/esl-media-query/core/conditions/media-query-base.ts
  src/modules/esl-media-query/core/conditions/media-query-condition.ts
  src/modules/esl-media-query/core/conditions/media-query-containers.ts
  src/modules/esl-media-query/core/esl-media-breakpoints.ts
  src/modules/esl-media-query/core/esl-media-query.ts
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-media-query/core/esl-media-rule.ts
  src/modules/esl-media-query/test/esl-media-breakpoints.test.ts
  src/modules/esl-media-query/test/esl-media-query.test.ts
  src/modules/esl-media-query/test/esl-media-rule-list.test.ts
  src/modules/esl-media-query/test/esl-media-rule.test.ts
  src/modules/esl-media-query/test/esl-screen-breakpoint.test.ts
  src/modules/esl-media/core/esl-media-registry.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-tab/core/esl-tabs.ts
  src/modules/esl-utils/abstract/observable.ts
  src/modules/esl-utils/test/matchMedia.mock.ts
  src/modules/lib.ts
Labels: breaking-change, enhancement, feature

#364 refactor(esl-footnotes): move esl-note to esl-footnotes as part of component
  pages/views/drafts/esl-footnotes.njk
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-footnotes/core.less
  src/modules/esl-footnotes/core.ts
  src/modules/esl-footnotes/core/esl-footnotes.ts
  src/modules/esl-footnotes/core/esl-note.less
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-note/core.less
  src/modules/esl-note/core.ts
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/dom/scroll.ts
  src/modules/lib.ts
Labels: enhancement

#365 fix(esl-popup): move position attribute from popup arrow to popup element
  src/modules/esl-popup/core/esl-popup-position.ts
  src/modules/esl-popup/core/esl-popup.less
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-utils/dom/element.ts
Labels: bug

#366 Bug: TS types are missing for document.createElement default ESL tag names #332
  .eslintrc.json
  pages/.eslintrc.json
  src/modules/draft/esl-carousel/core/esl-carousel-slide.ts
  src/modules/draft/esl-carousel/core/esl-carousel.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-autoplay.plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-dots.plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-link.plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-touch.plugin.ts
  src/modules/esl-a11y-group/core/esl-a11y-group.ts
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-footnotes/core/esl-footnotes.ts
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-item.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-forms/esl-select/core/esl-select-renderer.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media-query/core/common/env-shortcuts.ts
  src/modules/esl-media-query/core/common/screen-breakpoint.ts
  src/modules/esl-media-query/core/common/screen-dpr.ts
  src/modules/esl-media-query/core/esl-media-query.ts
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-tab/core/esl-tabs.ts
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
  src/modules/esl-traversing-query/core/esl-traversing-query.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-utils/environment/device-detector.ts
  src/modules/esl-utils/environment/export-ns.ts
  src/modules/lib.ts
Labels: bug

#356 feature(markdown): rendering certain parts of markdown to page
  .eleventy.js
  jest.config.js
  package-lock.json
  package.json
  pages/src/common/markdown.less
  pages/src/common/page.less
  pages/src/localdev.less
  pages/views/_data/markdown.js
  pages/views/_data/md-render.js
  pages/views/_includes/header.njk
  pages/views/_includes/img/logo.svg
  pages/views/_includes/readme.njk
  pages/views/_layouts/basic.njk
  pages/views/basic/esl-accordion.njk
  pages/views/basic/esl-alert.njk
  pages/views/basic/esl-image.njk
  pages/views/basic/esl-media.njk
  pages/views/basic/esl-scrollbar.njk
  pages/views/basic/esl-tab.njk
  pages/views/basic/esl-toggleable.njk
  pages/views/forms/esl-select-list.njk
  pages/views/forms/esl-select.njk
  pages/views/index.njk
  src/modules/esl-alert/README.md
  src/modules/esl-forms/esl-select-list/README.md
  src/modules/esl-forms/esl-select/README.md
  src/modules/esl-image/README.md
  src/modules/esl-media/README.md
  src/modules/esl-scrollbar/README.md
  src/modules/esl-tab/README.md
  src/modules/esl-toggleable/README.md
  src/modules/esl-trigger/README.md
Labels: bug, enhancement

#367 feat(esl-utils): promise utils fixes & test updates
  src/modules/esl-utils/async/debounce.ts
  src/modules/esl-utils/async/delayed-task.ts
  src/modules/esl-utils/async/promise.ts
  src/modules/esl-utils/async/raf.ts
  src/modules/esl-utils/async/test/debounce.test.ts
  src/modules/esl-utils/async/test/promise.test.ts
  src/modules/esl-utils/async/test/throttle.test.ts
  src/modules/esl-utils/async/throttle.ts
Labels: bug

#369 feat(esl-tooltip): add new action param to set up tooltip extra classes
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: enhancement

#375 fix(esl-popup): wrong popup position when the popup is shown at the first time
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-utils/dom/element.ts
  src/modules/esl-utils/dom/rect.ts
Labels: bug

#362 GH Pages: setup a sitemap generator #292
  package-lock.json
  pages/views/404.njk
  pages/views/_data/site.json
  pages/views/robots.njk
  pages/views/sitemap.njk
Labels: enhancement

#382 feat(esl-footnotes): add a grouping of footnotes with non-unique text
  pages/views/drafts/esl-footnotes.njk
  src/modules/esl-footnotes/core/esl-footnotes-data.ts
  src/modules/esl-footnotes/core/esl-footnotes.ts
  src/modules/esl-footnotes/core/esl-note.less
  src/modules/esl-footnotes/core/esl-note.ts
Labels: feature

#385 feat: jsx types support for components
  src/modules/esl-a11y-group/core.ts
  src/modules/esl-a11y-group/core/esl-a11y-group.shape.ts
  src/modules/esl-image/core.ts
  src/modules/esl-media/core.ts
  src/modules/esl-panel/core.ts
  src/modules/esl-panel/core/esl-panel-group.shape.ts
  src/modules/esl-panel/core/esl-panel.shape.ts
  src/modules/esl-tab/core.ts
  src/modules/esl-tab/core/esl-tab.shape.ts
  src/modules/esl-tab/core/esl-tabs.shape.ts
  src/modules/esl-tab/core/esl-tabs.ts
  src/modules/esl-toggleable/core.ts
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.shape.ts
  src/modules/esl-toggleable/core/esl-toggleable.shape.ts
  src/modules/esl-trigger/core.ts
  src/modules/esl-trigger/core/esl-trigger.shape.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: enhancement, feature

#397 fix(esl-media): fix toggle method and process keydown event otb
  pages/views/basic/esl-media.njk
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-media/core/esl-media.ts
Labels: bug

#396 fix(esl-footnotes): ESLNote lost tooltip text and ESLFootnotes duplicate notes and break order
  src/modules/esl-footnotes/core/esl-footnotes-data.ts
  src/modules/esl-footnotes/core/esl-footnotes.ts
  src/modules/esl-footnotes/core/esl-note.ts
Labels: bug

#395 Feat/add arr css class utils
  src/modules/esl-utils/dom/class.ts
  src/modules/esl-utils/dom/test/class.test.ts
Labels: enhancement

#393 Feat/add new format
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/test/format.test.ts
Labels: enhancement

#403 fix(esl-footnotes): fix broken click on back-to-note
  src/modules/esl-footnotes/core/esl-footnotes.ts
Labels: bug

#400 chore(patch): refactor major part of the lint rules
  .eslintrc.json
  eslint/coderules.eslintrc.yml
  eslint/codestyle.eslintrc.yml
  eslint/import.eslintrc.yml
  eslint/sonarjs.eslintrc.yml
  src/modules/draft/esl-carousel/core/view/esl-multi-carousel-view.ts
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-image/core/esl-image-strategies.ts
  src/modules/esl-media-query/core/esl-media-breakpoints.ts
  src/modules/esl-media/providers/youtube-provider.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-utils/decorators/memoize.ts
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/memoize.ts
  src/polyfills/list/dom.tokenList.toggle.ts
Labels: enhancement

#401 Feat/throttle promise
  src/modules/esl-utils/async/test/throttle.test.ts
  src/modules/esl-utils/async/throttle.ts
Labels: enhancement

#392 fix(esl-panel): add missing observedAttributes method
  pages/views/basic/esl-tab.njk
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-tab/core/esl-tabs.ts
Labels: bug

#406 fix(esl-utils): deep merge: fix array case and refactor
  src/modules/esl-utils/misc/object.ts
  src/modules/esl-utils/misc/test/object.test.ts
Labels: bug

#405 tech: eslint rules cleanup
  .eslintrc.json
  .eslintrc.yml
  eslint/coderules.eslintrc.yml
  eslint/codestyle.eslintrc.yml
  package-lock.json
  package.json
  pages/.eslintrc.yml
  src/modules/draft/esl-carousel/core/view/esl-multi-carousel-view.ts
  src/modules/draft/esl-carousel/core/view/esl-single-carousel-view.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-plugin.ts
  src/modules/esl-a11y-group/core/esl-a11y-group.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-utils/dom/events.ts
  src/modules/esl-utils/dom/rtl.ts
Labels: enhancement

#429 feat (esl-panel-group): move to separate module
  pages/views/samples/tabs.njk
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel-group/core.less
  src/modules/esl-panel-group/core.ts
  src/modules/esl-panel-group/core/esl-panel-group.less
  src/modules/esl-panel-group/core/esl-panel-group.shape.ts
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-panel/README.md
  src/modules/esl-panel/core.less
  src/modules/esl-panel/core.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: enhancement

#432 chore(patch): update TS version to 4.4.2, related fixes
  package-lock.json
  package.json
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-utils/environment/device-detector.ts
Labels: dependencies

#431 fix: scrollbar conflicts with scroll-behaviour:smooth
  pages/views/samples/scrollbar.njk
  src/modules/esl-scrollbar/README.md
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
Labels: bug

#434 bugfix: fix trackHover hideDelay inheritance from the original action
  pages/src/header/header-dropdown.less
  pages/views/_includes/header-menu.njk
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-utils/async/delayed-task.ts
Labels: bug

#438 fix(esl-trigger): fix incorrect tap handling on mobile devices
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: bug

#435 docs: ESLPopup and ESLFootnotes
  src/modules/esl-footnotes/README.md
  src/modules/esl-popup/README.md
Labels: documentation

#437 docs: updated development info for contributors
  docs/contribute/pages.md
  docs/contribute/scripts.md
Labels: documentation
