Repository exadel-inc/esl, pull requests merged in 2021-01, with the labels that each got.

#2 commit lint integration
  .commitlintrc.json
  .github/workflows/cla.yml
  README.md
  docs/commit.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#3 fix: native 'close on body click' feature can be prevented by outside click handlers
  src/modules/esl-base-popup/core/esl-base-popup.ts
  test-server/views/pages/esl-popup-page.html
Labels: bug

#5 [ESL Alert] Introduce new ESL Alert component
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-alert/README.md
  src/modules/esl-alert/core.less
  src/modules/esl-alert/core.ts
  src/modules/esl-alert/core/esl-alert.less
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/fixes/ie-fixes.less
  src/modules/esl-utils/fixes/ie-fixes.ts
  test-server/src/localdev.ts
  test-server/views/pages/esl-alert.html
  test-server/views/pages/esl-scrollable-tab.html
Labels: component, feature

#6 [tech] - Build optimizations
  .eslintrc.json
  gulpfile.js
  package-lock.json
  package.json
  paths.json
  src/polyfills/list/dom.element.closest.ts
  src/polyfills/list/es6.array.find.ts
  test-server/build/webpack-task.js
  test-server/gulpfile.js
  test-server/package.json
  test-server/webpack.config.js
Labels: enhancement

#8 feat: extend utilities
  src/modules/esl-utils/fixes/ie-fixes.less
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/object.ts
  src/modules/esl-utils/misc/test/format.test.ts
  src/modules/esl-utils/misc/test/object.test.ts
Labels: enhancement, feature

#9 epic: esl media v2
  .eslintignore
  .npmignore
  jest.config.js
  paths.json
  sonar-project.properties
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-media/core/esl-media-registry.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-media/providers/brightcove-provider.ts
  src/modules/esl-media/providers/html5/audio-provider.ts
  src/modules/esl-media/providers/html5/media-provider.ts
  src/modules/esl-media/providers/html5/video-provider.ts
  src/modules/esl-media/providers/iframe-provider.ts
  src/modules/esl-media/providers/youtube-provider.ts
  src/modules/esl-media/test/base-provider.mock.ts
  src/modules/esl-media/test/base-provider.test.ts
  src/modules/esl-media/test/media-manager.test.ts
  src/modules/esl-media/test/youtube-provider.test.ts
  test-server/paths.json
  test-server/src/common/test-media-source.ts
  test-server/views/pages/esl-media.html
  tsconfig.json
Labels: feature

#10 dev -> main (for release 1.43)
  .eslintignore
  .eslintrc.json
  .npmignore
  README.md
  gulpfile.js
  jest.config.js
  package-lock.json
  package.json
  paths.json
  sonar-project.properties
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-alert/README.md
  src/modules/esl-alert/core.less
  src/modules/esl-alert/core.ts
  src/modules/esl-alert/core/esl-alert.less
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-media/core/esl-media-registry.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-media/providers/brightcove-provider.ts
  src/modules/esl-media/providers/html5/audio-provider.ts
  src/modules/esl-media/providers/html5/media-provider.ts
  src/modules/esl-media/providers/html5/video-provider.ts
  src/modules/esl-media/providers/iframe-provider.ts
  src/modules/esl-media/providers/youtube-provider.ts
  src/modules/esl-media/test/base-provider.mock.ts
  src/modules/esl-media/test/base-provider.test.ts
  src/modules/esl-media/test/media-manager.test.ts
  src/modules/esl-media/test/youtube-provider.test.ts
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/fixes/ie-fixes.less
  src/modules/esl-utils/fixes/ie-fixes.ts
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/object.ts
  src/modules/esl-utils/misc/test/format.test.ts
  src/modules/esl-utils/misc/test/object.test.ts
  src/polyfills/list/dom.element.closest.ts
  src/polyfills/list/es6.array.find.ts
  test-server/build/webpack-task.js
  test-server/gulpfile.js
  test-server/package.json
  test-server/paths.json
  test-server/src/common/test-media-source.ts
  test-server/src/localdev.ts
  test-server/views/pages/esl-alert.html
  test-server/views/pages/esl-media.html
  test-server/views/pages/esl-scrollable-tab.html
  test-server/webpack.config.js
  tsconfig.json
Labels: release

#11 fix: fix providerName type to allow user to extend default providers
  src/modules/esl-media/providers/brightcove-provider.ts
  src/modules/esl-media/providers/html5/audio-provider.ts
  src/modules/esl-media/providers/html5/video-provider.ts
  src/modules/esl-media/providers/iframe-provider.ts
  src/modules/esl-media/providers/youtube-provider.ts
Labels: bug

#13 TECH: eventing part#1
  src/modules/esl-base-popup/core/esl-base-popup.ts
  src/modules/esl-image/CHANGELOG.md
  src/modules/esl-image/README.md
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/README.md
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-utils/decorators/ready.ts
  src/modules/esl-utils/dom/ready.ts
  test-server/views/pages/esl-popup-page.html
  test-server/views/pages/esl-scrollbar.html
Labels: enhancement

#14 docs: proofreading and correction of documentation
  README.md
  src/modules/esl-alert/README.md
  src/modules/esl-base-element/README.md
  src/modules/esl-base-popup/README.md
  src/modules/esl-image/README.md
  src/modules/esl-media-query/README.md
  src/modules/esl-media/README.md
  src/modules/esl-panel/README.md
  src/modules/esl-popup/README.md
  src/modules/esl-scrollable-tabs/README.md
  src/modules/esl-scrollbar/README.md
  src/modules/esl-tab/README.md
  src/modules/esl-traversing-query/README.md
  src/modules/esl-trigger/README.md
  src/modules/esl-utils/README.md
Labels: documentation

#15 Tech: eventing massive updates for version 2.0.0
  src/modules/draft/esl-carousel/core/esl-carousel.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-autoplay.plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-dots.plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-link.plugin.ts
  src/modules/esl-base-element/core.ts
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-base-element/test/base-element.test.ts
  src/modules/esl-base-popup/core/esl-base-popup.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/core/esl-media-manager.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-panel/core/esl-panel-stack.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-scrollable-tabs/core/esl-scrollable-tabs.ts
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-tab/core/esl-tabs-container.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  test-server/views/pages/esl-accordion.html
Labels: enhancement

#17 feat: add originalWidth / originalHeight accessors to ESLImage
  src/modules/esl-image/CHANGELOG.md
  src/modules/esl-image/README.md
  src/modules/esl-image/core/esl-image.ts
Labels: enhancement

#19 Tech/eventing cleanup v2
  src/modules/draft/esl-carousel/plugin/esl-carousel-autoplay.plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-dots.plugin.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-link.plugin.ts
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-base-element/test/base-element.test.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/CHANGELOG.md
  src/modules/esl-media/README.md
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-panel/core/esl-panel-stack.ts
  src/modules/esl-scrollable-tabs/core/esl-scrollable-tabs.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-utils/async/test/throttle.test.ts
Labels: bug, enhancement

#20 feat: introduce new BasePopupGroupManager based on events
  package-lock.json
  package.json
  src/modules/all.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-touch.plugin.ts
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-base-element/test/base-element.test.ts
  src/modules/esl-base-popup/core.ts
  src/modules/esl-base-popup/core/esl-base-popup-group-manager.ts
  src/modules/esl-base-popup/core/esl-base-popup-group.ts
  src/modules/esl-base-popup/core/esl-base-popup.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-panel/core/esl-panel-stack.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-popup/core.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-utils/dom/events.ts
  src/modules/lib.ts
  test-server/package.json
  test-server/src/common/back-button.ts
  test-server/src/localdev.ts
Labels: enhancement, feature

#21 feat!: add last activator feature, fix outside action
  src/modules/esl-base-popup/core/esl-base-popup.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: enhancement

#22 feature: base trigger separated
  README.md
  src/modules/esl-base-trigger/README.md
  src/modules/esl-base-trigger/core.ts
  src/modules/esl-base-trigger/core/esl-base-trigger.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: enhancement, feature
