Repository exadel-inc/esl, pull requests merged in 2021-04, with the labels that each got.

#123 fix: debounce fit to viewport
  src/modules/esl-tab/core/esl-tabs.ts
Labels: bug

#129 chore: cpy-cli replaced with copyfiles
  package-lock.json
  package.json
  pages/package.json
Labels: enhancement

#137 feat: extend Scrollable Tabs to support center position
  pages/views/pages/basic/esl-tab.html
  src/modules/esl-tab/README.md
  src/modules/esl-tab/core/esl-tabs.ts
Labels: feature

#142 feat: `@prop` decorator
  .github/dependabot.yml
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-utils/README.md
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/decorators/override.ts
  src/modules/esl-utils/decorators/prop.ts
  src/modules/esl-utils/decorators/readonly.ts
  src/modules/esl-utils/decorators/test/prop.test.ts
  src/modules/esl-utils/decorators/test/readonly.test.ts
Labels: feature

#146 fix: outsideAction tracker conflicts with outside esl-triggers / activator
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-traversing-query/core/esl-traversing-query.ts
Labels: bug

#147 docs: gh-pages demo updates
  pages/src/common/page.less
  pages/src/footer/config.json
  pages/src/footer/footer.html
  pages/src/header/config.json
  pages/src/header/header-dropdown.less
  pages/src/header/header-menu.html
  pages/src/header/header.html
  pages/src/header/header.less
  pages/src/localdev.less
  pages/src/lorem/config.json
  pages/src/lorem/lorem.html
  pages/src/lorem/lorem.js
  pages/views/layouts/basic.html
  pages/views/navigation/header.html
  pages/views/pages/basic/esl-accordion.html
  pages/views/pages/basic/esl-image.html
  pages/views/pages/basic/esl-scrollbar.html
  pages/views/pages/basic/esl-tab.html
  pages/views/pages/basic/esl-toggleable.html
  src/modules/esl-utils/README.md
Labels: enhancement

#151 Class Utils Extended (concept)
  pages/src/common/page.less
  pages/src/header/header.html
  pages/static/assets/logo.svg
  pages/views/index.html
  pages/views/pages/basic/esl-toggleable.html
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-utils/README.md
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/dom/class.ts
  src/modules/esl-utils/dom/scroll.ts
  src/modules/esl-utils/dom/styles.ts
  src/modules/esl-utils/dom/test/class.test.ts
  src/modules/esl-utils/dom/test/styles.test.ts
Labels: enhancement, feature

#156 fix: provider type dynamic registration fix
  pages/tsconfig.json
  src/modules/esl-media/core/esl-media.ts
Labels: bug

#158 Bugfix/toggleable delays
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-utils/misc/object.ts
  src/modules/esl-utils/misc/test/object.test.ts
Labels: bug, enhancement

#159 feat: disabled options support for esl-select-item and fix list mutation detection
  pages/views/pages/forms/esl-select-list.html
  pages/views/pages/forms/esl-select.html
  src/modules/esl-forms/esl-select-list/core/esl-select-item.less
  src/modules/esl-forms/esl-select-list/core/esl-select-item.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-wrapper.ts
Labels: feature

#167 fix: fix fallback animation call for esl-panel and esl-panel-group
  src/modules/esl-panel/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: bug
