Repository exadel-inc/esl, pull requests merged in 2022-10, with the labels that each got.

#1261 fix(esl-utils): fix `@boolAttr` incompatible with mixin element
  src/modules/esl-mixin-element/test/mixin.attr-helpers.test.ts
  src/modules/esl-mixin-element/test/mixin.test.ts
  src/modules/esl-utils/decorators/bool-attr.ts
  src/modules/esl-utils/dom/attr.ts
Labels: bug

#1265 fix(esl-base-element): `ESLBaseElement.create` types updated to be compatible with overriding in current TS state
  src/modules/esl-base-element/core/esl-base-element.ts
Labels: bug

#1263 feat(esl-event-listener): improve `ESLEventListener` object to have exact handler for simple subscriptions
  src/modules/esl-base-element/test/element.listener.test.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/types.ts
  src/modules/esl-mixin-element/test/mixin.listener-herpers.test.ts
  src/modules/esl-mixin-element/test/mixin.listener.test.ts
Labels: enhancement

#1267 tech(esl-utils): utils export cleanup and documentation update
  src/modules/esl-utils/README.md
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/fixes.ts
  src/modules/esl-utils/misc.ts
Labels: enhancement

#1270 fix(tsx): components TSX shapes fixes
  src/modules/esl-media/core/esl-media.shape.ts
  src/modules/esl-panel-group/core/esl-panel-group.shape.ts
  src/modules/esl-tab/core/esl-tabs.shape.ts
Labels: bug

#1273 chore(esl-alert): add tests for events
  src/modules/esl-alert/test/alert.request.test.ts
Labels: require squash

#1288 fix(esl-tabs): fix styles based on current scrollable type
  src/modules/esl-tab/core/esl-tabs.scrollable.less
  src/modules/esl-tab/core/esl-tabs.ts
Labels: bug

#1298 fix(esl-media-query): fix missing Event type in `core.ts` bundle
  src/modules/esl-media-query/core.ts
Labels: bug

#1302 chore(gh-pages): fix sitemap for redirect and collections pages
  pages/views/blogs/index.njk
  pages/views/draft/index.njk
  pages/views/redirect/esl-a11y-group.njk
  pages/views/redirect/esl-media-query.njk
  pages/views/redirect/esl-traversing-query.njk
  pages/views/redirect/utils.njk
Labels: site

#1313 fix(gh-pages): fix svg format
  pages/static/assets/logo-pretty.svg
Labels: bug, site, require squash
