Repository exadel-inc/esl, pull requests merged in 2022-05, with the labels that each got.

#941 feat: esl-media-query 3.0 - extended EventTarget based API
  pages/src/navigation/sidebar/sidebar.ts
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-media-query/README.md
  src/modules/esl-media-query/core.ts
  src/modules/esl-media-query/core/common/env-shortcuts.ts
  src/modules/esl-media-query/core/conditions/media-query-base.ts
  src/modules/esl-media-query/core/conditions/media-query-condition.ts
  src/modules/esl-media-query/core/conditions/media-query-const.ts
  src/modules/esl-media-query/core/conditions/media-query-containers.ts
  src/modules/esl-media-query/core/esl-media-query.ts
  src/modules/esl-media-query/core/esl-media-rule.ts
  src/modules/esl-media-query/test/esl-media-query.test.ts
  src/modules/esl-media-query/test/esl-media-rule-list.test.ts
  src/modules/esl-media-query/test/esl-media-rule.test.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-utils/abstract/event-target.ts
  src/modules/esl-utils/test/matchMedia.mock.ts
  src/polyfills/es5-target-shim.ts
Labels: feature, under discussion

#981 feat(esl-togglable): show:request additional data
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-utils/dom/test/traversing.test.ts
  src/modules/esl-utils/dom/traversing.ts
Labels: feature

#957 Feat/media query 3.1
  src/modules/esl-media-query/README.md
  src/modules/esl-media-query/core.ts
  src/modules/esl-media-query/core/decorator/media.ts
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-media-query/core/esl-media-rule.ts
  src/modules/esl-media-query/test/esl-media-rule-list.test.ts
  src/modules/esl-media-query/test/esl-media-rule.test.ts
Labels: enhancement, feature, breaking-change

#994 docs(esl-image): fix SVG rendering mode name
  src/modules/esl-image/README.md
Labels: documentation

#987 Feat(esl-trigger): add aria-label support
  pages/views/examples/toggleable.njk
  src/modules/esl-trigger/README.md
  src/modules/esl-trigger/core/esl-trigger.shape.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: enhancement, under discussion
