Repository exadel-inc/esl, pull requests merged in 2022-08, with the labels that each got.

#1118 feat(esl-utils): extend SynteticEventTarget with ability to separate events enhancement
  src/modules/esl-utils/dom/events/target.ts
  src/modules/esl-utils/dom/events/test/target.test.ts
Labels: enhancement

#1147 fix(esl-utils): fix page content jumping after scroll lock
  src/modules/esl-utils/dom/scroll.less
Labels: bug

#1144 feat(esl-utility): event listener subscription logic fix and ability to inherit listener definition
  src/modules/esl-base-element/core.ts
  src/modules/esl-mixin-element/core.ts
  src/modules/esl-utils/decorators/listen.ts
  src/modules/esl-utils/decorators/test/listen.test.ts
  src/modules/esl-utils/dom/events/listener.ts
  src/modules/esl-utils/dom/events/test/listener.test.ts
  src/modules/esl-utils/dom/events/test/utils.test.ts
Labels: enhancement, under discussion

#1157 fix(esl-mixin-element): incorrect context applied for listener applied trough `$$on`
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
Labels: bug

#1145 refactor(esl-trigger): esl-trigger migrated to esl listener utility
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: enhancement

#1170 feat(esl-utils): allow to pass array of targets to the `ESLEventListener`
  src/modules/esl-utils/dom/events/listener.ts
Labels: enhancement

#1175 fix(esl-utils): `@listen` and event listener descriptors enchancements
  src/modules/esl-utils/decorators/listen.ts
  src/modules/esl-utils/dom/events/utils.ts
Labels: enhancement

#1189 chore(deps-dev): bump typescript from 4.7 and typescript-eslint
  package-lock.json
  package.json
Labels: dependencies

#1176 fix(esl-utils): `@decorate` and `@bind` complete rework
  src/modules/esl-utils/decorators/bind.ts
  src/modules/esl-utils/decorators/decorate.ts
  src/modules/esl-utils/decorators/listen.ts
  src/modules/esl-utils/decorators/test/bind.test.ts
  src/modules/esl-utils/decorators/test/decorate.test.ts
Labels: bug, enhancement

#1191 fix: cyclic dependencies across all modules
  eslint/import.eslintrc.yml
  pages/webpack.config.js
  src/modules/esl-forms/esl-select/core/esl-select-renderer.ts
  src/modules/esl-image/core/esl-image-iobserver.ts
  src/modules/esl-image/core/esl-image-strategies.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/core/esl-media-iobserver.ts
  src/modules/esl-panel/core/esl-panel.shape.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: bug

#1194 feat(esl-panel-group): extend esl-panel-group refresh strategies list with 'open' and 'close' strategy
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel-group/core/esl-panel-group.shape.ts
  src/modules/esl-panel-group/core/esl-panel-group.ts
Labels: enhancement

#1195 fix(esl-panel-group): animation process capturing by ESLPanel component
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-utils/async/raf.ts
Labels: bug
