Repository exadel-inc/esl, pull requests merged in 2022-07, with the labels that each got.

#1074 refactor: move parsers to esl-utils/misc/format
  src/modules/esl-utils/decorators/attr.ts
  src/modules/esl-utils/decorators/test/attr.test.ts
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/test/format.test.ts
Labels: enhancement

#1085 chore: tests speed-up
  jest.config.js
Labels: enhancement

#1094 feat(esl-utils, esl-traversing-query): update createSequenceFinder, add possibility to find closest element
  src/modules/esl-traversing-query/README.md
  src/modules/esl-traversing-query/core/esl-traversing-query.ts
  src/modules/esl-traversing-query/test/esl-traversing-query.test.ts
  src/modules/esl-utils/dom/test/traversing.test.ts
  src/modules/esl-utils/dom/traversing.ts
  src/modules/esl-utils/misc/functions.ts
Labels: feature

#1097 chore(lint): lint staged integration
  .husky/pre-commit
  .lintstagedrc.yml
  package-lock.json
  package.json
Labels: dependencies

#1100 chore: update lintstaged.rc.yml to fix build
  .lintstagedrc.yml
Labels: maintenance

#1111 fix(esl-image): fix wrong error status on svg images in FF
  src/modules/esl-image/core/esl-image.ts
Labels: bug

#1093 refactor(esl-utils): rework public api for SyntheticEventTarget
  src/modules/esl-media-query/core/conditions/media-query-condition.ts
  src/modules/esl-media-query/core/conditions/media-query-containers.ts
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-utils/dom/events/target.ts
Labels: enhancement

#1124 fix(esl-utils): fix missed body style for scroll lock strategy pseudo
  src/modules/esl-utils/dom/scroll.less
Labels: bug

#1103 test(esl-utils): scroll utils code improvements and scroll utils test coverage
  src/modules/esl-utils/dom/scroll/parent.ts
  src/modules/esl-utils/dom/scroll/test/parent.test.ts
  src/modules/esl-utils/dom/scroll/test/utils.test.ts
  src/modules/esl-utils/dom/scroll/utils.ts
Labels: enhancement
