Repository exadel-inc/esl, pull requests merged in 2022-03, with the labels that each got.

#868 feat(esl-utils): update promisifyTimeout with extended syntax support
  src/modules/esl-utils/async/promise.ts
  src/modules/esl-utils/async/test/promise.test.ts
Labels: feature

#852 feat(esl-utils): update `object#get` and `object#set` with extended syntax support
  src/modules/esl-utils/misc/object.ts
  src/modules/esl-utils/misc/object/compare.ts
  src/modules/esl-utils/misc/object/copy.ts
  src/modules/esl-utils/misc/object/merge.ts
  src/modules/esl-utils/misc/object/path.ts
  src/modules/esl-utils/misc/object/test/compare.test.ts
  src/modules/esl-utils/misc/object/test/copy.test.ts
  src/modules/esl-utils/misc/object/test/merge.test.ts
  src/modules/esl-utils/misc/object/test/path.test.ts
  src/modules/esl-utils/misc/object/test/types.test.ts
  src/modules/esl-utils/misc/object/test/utils.test.ts
  src/modules/esl-utils/misc/object/types.ts
  src/modules/esl-utils/misc/object/utils.ts
  src/modules/esl-utils/misc/test/object.test.ts
Labels: feature

#874 fix(esl-panel-group): add `capturedBy` and fix 'esl:after:show' dispatch
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: bug

#882 fix(esl-utils): move attribute decorators to the `esl-utils`
  pages/src/navigation/sidebar/sidebar.ts
  src/modules/esl-base-element/core.ts
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-utils/decorators/attr.ts
  src/modules/esl-utils/decorators/bool-attr.ts
  src/modules/esl-utils/decorators/json-attr.ts
  src/modules/esl-utils/decorators/test/attr.test.ts
  src/modules/esl-utils/decorators/test/bool-attr.test.ts
  src/modules/esl-utils/decorators/test/json-attr.test.ts
Labels: enhancement

#883 feat(esl-utils): event utils destructuring
  src/modules/draft/esl-carousel/plugin/esl-carousel-touch.plugin.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.ts
  src/modules/esl-utils/dom/events.ts
  src/modules/esl-utils/dom/events/misc.ts
  src/modules/esl-utils/dom/events/test/misc.test.ts
  src/modules/esl-utils/dom/events/test/utils.test.ts
  src/modules/esl-utils/dom/events/utils.ts
  src/modules/esl-utils/dom/test/events.test.ts
Labels: enhancement

#881 feat(esl-utils): extend object:compare utils with `isSimilar` method
  src/modules/draft/esl-carousel/core/esl-carousel.ts
  src/modules/esl-utils/misc/object/compare.ts
  src/modules/esl-utils/misc/object/test/compare.test.ts
  src/modules/esl-utils/misc/test/object.test.ts
Labels: feature

#884 refactor(gh-pages): refactoring of test media components
  pages/src/esl-media-demo/test-media-source.ts
  pages/src/esl-media-demo/test-media.less
  pages/src/esl-media-demo/test-media.ts
  pages/views/components/esl-media.njk
  pages/views/examples/embedded-audio.njk
  pages/views/examples/embedded-video.njk
Labels: enhancement

#895 feat: esl-utils extended with once feature for event listener and `@decorate` helper
  pages/src/esl-media-demo/test-media-source.ts
  pages/src/esl-media-demo/test-media.ts
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/decorators/decorate.ts
  src/modules/esl-utils/dom/events/listener.ts
Labels: enhancement

#902 fix(esl-panel-group): fix esl:before:hide bubbling from uncontrolled toggleables
  src/modules/esl-panel-group/core/esl-panel-group.ts
Labels: bug
