Repository exadel-inc/esl, pull requests merged in 2022-09, with the labels that each got.

#1198 fix: `@decorate` vs `@listen` behaviour
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-utils/decorators/bind.ts
  src/modules/esl-utils/decorators/decorate.ts
  src/modules/esl-utils/dom/events/utils.ts
Labels: under discussion

#1200 fix(esl-scrollbar): remove unnecessary width
  src/modules/esl-scrollbar/core/esl-scrollbar.less
Labels: bug

#1201 style(gh-pages): change code field in esl-tabs examples
  pages/src/common/code.less
  pages/views/examples/tabs.njk
Labels: site

#1217 code style: disallow number leading zero
  .stylelintrc.yml
  pages/src/banner/banner.less
  pages/src/common/accordion.less
  pages/src/common/alert.less
  pages/src/common/badge.less
  pages/src/common/buttons.less
  pages/src/common/dropdown-menu.less
  pages/src/common/forms.less
  pages/src/common/helpers.less
  pages/src/common/markdown.less
  pages/src/common/reboot.less
  pages/src/common/tabs.less
  pages/src/common/typography.less
  pages/src/landing/marquee/marquee.less
  pages/src/landing/overview/overview.less
  pages/src/navigation/footer/footer.less
  pages/src/navigation/header/header-search.less
  pages/src/navigation/sidebar/sidebar-content.less
  src/modules/draft/esl-carousel/plugin/esl-carousel-dots.less
  src/modules/esl-forms/esl-select-list/core/esl-select-item.less
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.less
  src/modules/esl-image/core/esl-image-container.less
  src/modules/esl-popup/core/esl-popup.less
Labels: enhancement

#1212 fix(esl-event-listener): change resolving strategy and subscription process
  pages/src/anchor/anchor-link.ts
  pages/views/core/esl-event-listener.njk
  pages/views/core/esl-utils.njk
  src/modules/esl-base-element/test/element.listener.test.ts
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core.ts
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/descriptor.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/test/subscribe.test.ts
  src/modules/esl-event-listener/test/unsubscribe.test.ts
  src/modules/esl-event-listener/test/utils.test.ts
  src/modules/esl-mixin-element/test/mixin.listener.test.ts
  src/modules/esl-trigger/test/esl-trigger.a11y.test.ts
  src/modules/esl-utils/decorators/test/listen.test.ts
  src/modules/esl-utils/dom/events.ts
  src/modules/esl-utils/dom/events/listener.ts
  src/modules/esl-utils/dom/events/misc.ts
  src/modules/esl-utils/dom/events/test/integration.test.ts
  src/modules/esl-utils/dom/events/test/listener.test.ts
  src/modules/esl-utils/dom/events/test/misc.test.ts
  src/modules/esl-utils/dom/events/test/utils.test.ts
Labels: bug, enhancement

#1223 fix(esl-panel-group): fix initial reset of panel group leads to incorrect panel selection
  src/modules/esl-panel-group/core/esl-panel-group.ts
Labels: bug

#1237 chore: return back type-checking for tests
  jest.config.js
Labels: enhancement

#1234 test(esl-event-listener): update tests
  src/modules/esl-event-listener/test/listener.delegate.test.ts
  src/modules/esl-event-listener/test/listener.find.test.ts
  src/modules/esl-event-listener/test/listener.once.test.ts
  src/modules/esl-event-listener/test/listener.provider.test.ts
  src/modules/esl-event-listener/test/listener.resubscribe.test.ts
  src/modules/esl-event-listener/test/listener.subscribe.test.ts
  src/modules/esl-event-listener/test/listener.uniqueness.test.ts
  src/modules/esl-event-listener/test/listener.unsubscribe.test.ts
  src/modules/esl-event-listener/test/subscribe.test.ts
Labels: enhancement

#1231 feat(esl-panel-group): add ability to specify the strategy of closing panels in case the max-open-items limit is reached
  pages/views/draft/accordion-regression.njk
  src/modules/esl-panel-group/core/esl-panel-group.ts
Labels: enhancement

#1238 refactor(esl-event-listener): update descriptors related methods
  src/modules/esl-event-listener/core.ts
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/types.ts
  src/modules/esl-utils/decorators/listen.ts
  src/modules/esl-utils/misc/object/test/utils.test.ts
  src/modules/esl-utils/misc/object/utils.ts
Labels: enhancement

#1243 fix(esl-event-listener): `ESLMixinElement` + `ESLEventListener` complex cases
  pages/views/examples/tabs.njk
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/types.ts
  src/modules/esl-mixin-element/test/mixin.listener-herpers.test.ts
  src/modules/esl-mixin-element/test/mixin.listener.test.ts
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
Labels: bug

#1251 fix(esl-event-listener): allow to subscribe listener by global selector without host instanceof HTMLElement
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/test/listener.subscribe.test.ts
Labels: bug

#1246 feat(els-footnotes): footnotes migrated on ESLEventListener + bugfixes
  .releaserc.json
  src/modules/esl-footnotes/core/esl-footnotes.ts
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: enhancement

#1252 feat(esl-select): `ESLSelect` and `ESLSelectList` migrated to ESLEventListeners
  src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-wrapper.ts
  src/modules/esl-forms/esl-select/core/esl-select-renderer.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
Labels: enhancement

#1253 feat (esl-scrollbar): `ESLScrollbar` migrated to `ESLEventListeners`
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
Labels: enhancement

#1257 feat(esl-tabs): `ESLTabs` migrated to `ESLEventListeners`
  src/modules/esl-tab/core/esl-tabs.ts
Labels: enhancement
