Repository exadel-inc/esl, pull requests merged in 2022-11, with the labels that each got.

#1314 fix(gh-pages): fix aurora effect for `lg-xl`, `xl` and `xs` breakpoints
  pages/src/landing/promo-banner/promo-banner.less
Labels: bug, site, require squash

#1324 epic(esl-related-target): implement mixin for ESLToggleable (or based on it) instance
  pages/src/collection-grid/collection-grid.less
  pages/src/localdev.ts
  pages/views/components/esl-toggleable.njk
  pages/views/examples/toggleable.njk
  src/modules/all.ts
  src/modules/esl-related-target/README.md
  src/modules/esl-related-target/core.ts
  src/modules/esl-related-target/core/esl-related-target.ts
  src/modules/esl-related-target/test/related-target.test.ts
Labels: feature

#1349 fix(esl-scrollbar): change target on `window` for `scroll` event
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
Labels: bug
