Repository exadel-inc/esl, pull requests merged in 2022-01, with the labels that each got.

#765 chore: update 11ty to 1.0.0
  build/catlog.js
  package-lock.json
  package.json
  pages/.eleventy.js
  pages/11ty/env.config.js
  pages/11ty/markdown.shortcut.js
  pages/views/_data/env.js
Labels: enhancement

#747 feat: esl-panel-group and toggleable API extendsion
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel-group/core/esl-panel-group.less
  src/modules/esl-panel-group/core/esl-panel-group.shape.ts
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: enhancement

#766 chore: add webpack bundle analyzer
  package-lock.json
  package.json
Labels: hacktoberfest

#774 feat(esl-toggleable): add ootb handler for esl:show:request
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: feature

#778 fix(esl-media): fix missing load condition reinitialization and docs
  src/modules/esl-media/README.md
  src/modules/esl-media/core/esl-media.shape.ts
  src/modules/esl-media/core/esl-media.ts
Labels: bug, enhancement

#783 fix(esl-media): fix incorrect `load-condition` definition in TSX shape
  src/modules/esl-media/core/esl-media.shape.ts
Labels: bug
