Repository exadel-inc/esl, pull requests merged in 2022-06, with the labels that each got.

#1007 feat(esl-utils): ability to pass Provider functions to `event`, `sele…
  pages/src/esl-media-demo/test-media.ts
  src/modules/esl-utils/decorators/listen.ts
  src/modules/esl-utils/decorators/test/listen.test.ts
  src/modules/esl-utils/dom/events/listener.ts
  src/modules/esl-utils/dom/events/test/listener.test.ts
  src/modules/esl-utils/dom/events/utils.ts
  src/modules/esl-utils/misc/functions.ts
  src/modules/esl-utils/misc/test/functions.test.ts
Labels: enhancement, feature

#1022 refactor(esl-utils): split scroll.ts file and add scroll into view example pages
  pages/src/anchor/anchor-link.ts
  pages/src/common/helpers.less
  pages/src/common/typography.less
  pages/src/localdev.ts
  pages/src/page/base-layout.less
  pages/src/page/sidebar-layout.less
  pages/views/_layouts/empty.njk
  pages/views/examples/nested-accordion.njk
  src/modules/esl-utils/dom/scroll.ts
  src/modules/esl-utils/dom/scroll/parent.ts
  src/modules/esl-utils/dom/scroll/scroll-into-view.ts
  src/modules/esl-utils/dom/scroll/utils.ts
Labels: enhancement

#1028 feat(esl-utils): simplify and extend `@prop` decorator
  src/modules/esl-utils/decorators/prop.ts
  src/modules/esl-utils/decorators/test/prop.test.ts
Labels: enhancement, breaking-change

#1038 tech: legacy and codestyle cleanup
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-animate/core/esl-animate.ts
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-item.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media-query/test/esl-media-rule-list.test.ts
  src/modules/esl-media-query/test/esl-media-rule.test.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-tab/core/esl-tabs.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: enhancement

#1042 Refactor/esl a11ty group
  pages/views/_includes/navigation/sidebar-item.njk
  src/modules/esl-a11y-group/README.md
  src/modules/esl-a11y-group/core/esl-a11y-group.ts
  src/modules/esl-utils/dom/events/listener.ts
Labels: enhancement

#1041 feat: `@attr` v2 (support of serializer/parser)
  pages/src/navigation/sidebar/sidebar.ts
  src/modules/esl-utils/decorators/attr.ts
  src/modules/esl-utils/decorators/test/attr.test.ts
Labels: feature, under discussion

#1043 feat: event normalization for 'esl:refresh' and ESLImage, ESLMedia components
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-image/README.md
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/README.md
  src/modules/esl-media/core/esl-media-iobserver.ts
  src/modules/esl-media/core/esl-media-manager.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: enhancement, under discussion

#1053 feat(esl-media-query): normalize data instead of fail
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-media-query/test/esl-media-rule-list.test.ts
Labels: enhancement

#1054 test(esl-media-query): update tests with more logical, representative and supported structure
  src/modules/esl-media-query/test/esl-media-rule-list.test.ts
  src/modules/esl-media-query/test/esl-screen-breakpoint.test.ts
Labels: enhancement

#1048 feat(gh-pages): add blogs landing component
  pages/11ty/slice.filter.js
  pages/11ty/sort.filter.js
  pages/11ty/text.filter.js
  pages/11ty/trim.filter.js
  pages/src/landing/blogs/blogs.less
  pages/src/landing/landing.less
  pages/src/navigation/footer/footer.less
  pages/views/_includes/landing/blogs.njk
  pages/views/_includes/navigation/sidebar-item.njk
  pages/views/_includes/navigation/sidebar.njk
  pages/views/blogs/Prelelease v4.0.0.md
  pages/views/blogs/index.njk
  pages/views/index.11tydata.yml
  pages/views/index.njk
Labels: site

#1057 Feat(esl-utils, esl-image): sanitize html to prevent DOM XSS vulnarabilities
  src/modules/esl-image/core/esl-image-strategies.ts
  src/modules/esl-image/test/esl-image.test.ts
  src/modules/esl-image/test/xmlHttpRequest.mock.ts
  src/modules/esl-utils/all.ts
  src/modules/esl-utils/dom/sanitize.ts
  src/modules/esl-utils/dom/test/sanitize.test.ts
Labels: enhancement, feature

#1070 chore: fix lint warnings and errors
  eslint/coderules.eslintrc.yml
  package.json
  pages/views/_includes/landing/benefits.njk
  pages/views/_includes/navigation/footer-compact.njk
  pages/views/blogs/index.njk
  pages/views/core/esl-base-element.njk
  pages/views/core/esl-media-query.njk
  pages/views/core/esl-mixin-element.njk
  pages/views/core/esl-utils.njk
  src/modules/esl-image/test/esl-image.test.ts
  src/modules/esl-image/test/xmlHttpRequest.mock.ts
  src/modules/esl-utils/dom/sanitize.ts
  src/polyfills/list/es6.object.assign.ts
Labels: not ready for merge
