Repository exadel-inc/esl, pull requests merged in 2022-02, with the labels that each got.

#813 main-beta <- epic/popup
  pages/views/examples/footnotes.njk
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-popup/core/esl-popup.ts
Labels: released on @beta

#814 main-beta <- epic/footnotes
  pages/views/examples/footnotes.njk
  src/modules/esl-footnotes/core/esl-note-group.ts
  src/modules/esl-footnotes/core/esl-note.ts
Labels: released on @beta

#830 Popup: update docs
  src/modules/esl-popup/README.md
Labels: documentation

#829 Footnotes: update docs
  pages/views/examples/footnotes.njk
  src/modules/esl-footnotes/README.md
Labels: documentation

#817 chore: Landing page content updates and improvements for content rendering flow
  package-lock.json
  package.json
  pages/11ty/env.config.js
  pages/11ty/yml.support.js
  pages/src/landing/browser-support/browser-support.less
  pages/src/landing/marquee/marquee.less
  pages/views/_data/landing/benefits.json
  pages/views/_includes/landing/benefits.njk
  pages/views/_includes/landing/browser-support.njk
  pages/views/_includes/landing/marquee.njk
  pages/views/_includes/landing/promo-banner.njk
  pages/views/_includes/navigation/footer-menu.njk
  pages/views/_includes/navigation/footer.njk
  pages/views/_includes/richtext.njk
  pages/views/index.11tydata.yml
  pages/views/index.njk
Labels: enhancement

#843 fix(esl-scrollbar): :bug: fix vertical scroll on RTL
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-utils/dom/rtl.ts
Labels: bug

#836 epic: esl-core-2.0 basic updates
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-base-element/decorators/attr.ts
  src/modules/esl-base-element/decorators/bool-attr.ts
  src/modules/esl-base-element/decorators/json-attr.ts
  src/modules/esl-base-element/test/base-element.test.ts
  src/modules/esl-base-element/test/element.test.ts
  src/modules/esl-utils/decorators/test/prop.test.ts
  src/modules/esl-utils/dom/attr.ts
  src/modules/esl-utils/dom/class.ts
  src/modules/esl-utils/dom/test/class.test.ts
Labels: feature

#844 refactor(esl-core): fix types and documentation
  src/modules/esl-base-element/README.md
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-base-element/decorators/attr.ts
  src/modules/esl-base-element/decorators/bool-attr.ts
  src/modules/esl-base-element/decorators/json-attr.ts
  src/modules/esl-utils/dom/attr.ts
Labels: enhancement

#848 feat: ESLPanel and ESLPanelGroup fallback duration retirement
  pages/views/examples/tabs.njk
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel-group/core/esl-panel-group.less
  src/modules/esl-panel-group/core/esl-panel-group.shape.ts
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-panel/README.md
  src/modules/esl-panel/core/esl-panel.shape.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: enhancement

#857 fix: `esl-panel` and `esl-panel-group` transition end handling
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: bug

#861 feat(esl-media-query): extend `ESLMediaRuleList.parseTuple` with ability to pass Parser
  src/modules/esl-media-query/README.md
  src/modules/esl-media-query/core/esl-media-query.ts
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-media-query/core/esl-media-rule.ts
  src/modules/esl-media-query/test/esl-media-rule.test.ts
Labels: feature
