Repository exadel-inc/esl, pull requests merged in 2022-04, with the labels that each got.

#903 feat(esl-utils): rework subscription API
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-utils/decorators/test/listen.test.ts
  src/modules/esl-utils/dom/events/listener.ts
  src/modules/esl-utils/dom/events/test/listener.test.ts
  src/modules/esl-utils/dom/events/test/utils.test.ts
  src/modules/esl-utils/dom/events/utils.ts
  src/modules/esl-utils/misc/object/compare.ts
  src/modules/esl-utils/misc/object/test/compare.test.ts
Labels: enhancement

#908 fix: event utils passive subscriptions and descriptors merging
  src/modules/esl-utils/dom/events/listener.ts
  src/modules/esl-utils/dom/events/misc.ts
  src/modules/esl-utils/dom/events/test/listener.test.ts
  src/modules/esl-utils/dom/events/test/misc.test.ts
  src/modules/esl-utils/dom/events/test/utils.test.ts
  src/modules/esl-utils/dom/events/utils.ts
Labels: bug

#816 Epic: Mixin Elements Core
  src/modules/esl-base-element/README.md
  src/modules/esl-base-element/core.ts
  src/modules/esl-base-element/core/esl-mixin-element.ts
  src/modules/esl-base-element/core/esl-mixin-registry.ts
  src/modules/esl-base-element/test/mixin-element.test.ts
  src/modules/esl-utils/dom/events/listener.ts
Labels: enhancement, feature

#915 fix(esl-toggleable): fix double `esl:` prefix for esl-toggleable `esl:refresh` dispatching
  src/modules/esl-toggleable/README.md
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: bug

#914 fix(esl-utils): rename some event/misc utils
  src/modules/draft/esl-carousel/plugin/esl-carousel-touch.plugin.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-utils/dom/events/misc.ts
  src/modules/esl-utils/dom/events/test/misc.test.ts
  src/modules/esl-utils/dom/test/events.test.ts
Labels: enhancement

#923 refactoring: event utils + esl-scrollbar
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-utils/dom/events/listener.ts
Labels: enhancement

#927 refactor: esl-panel/esl-panel-group remove deprecated for version 4.0.0
  pages/src/navigation/sidebar/sidebar.ts
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel-group/core/esl-panel-group.shape.ts
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: breaking-change

#940 feat(esl-popup): add configurable rootMargin for the popup activator observer
  pages/views/examples/footnotes.njk
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-popup/core/esl-popup.ts
Labels: feature

#945 feat(esl-popup): add extended offsetContainer configuration
  src/modules/esl-popup/core/esl-popup.ts
Labels: feature

#942 fix(esl-utils): `deepMerge` primitive values merging improved, undefined arguments now ignored
  src/modules/esl-utils/misc/object/merge.ts
  src/modules/esl-utils/misc/object/test/merge.test.ts
Labels: bug

#949 fix: butch of IE11 fixes
  .commitlintrc.yml
  docs/BROWSER_SUPPORT.md
  package-lock.json
  package.json
  pages/src/polyfill-full.ts
  src/modules/esl-base-element/core/esl-mixin-registry.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/polyfills/list/dom.event.base.ts
  src/polyfills/list/dom.event.custom.ts
  src/polyfills/list/dom.event.focus.ts
  src/polyfills/list/dom.event.keyboard.ts
  src/polyfills/list/dom.event.mouse.ts
  src/polyfills/list/es6.array.from.ts
  src/polyfills/list/es6.object.assign.ts
  src/polyfills/polyfills.es5.ts
Labels: bug

#950 fix(polyfills): optimized safe version of `Object.assign` polyfill
  src/polyfills/list/es6.object.assign.ts
Labels: bug
