Repository exadel-inc/esl, pull requests merged in 2023-08, with the labels that each got.

#1831 feat(esl-utils): extended parser/serializer for marker attributes (PROPOSAL)
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-utils/decorators/test/attr.extended.test.ts
  src/modules/esl-utils/decorators/test/attr.test.ts
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/test/format.test.ts
Labels: under discussion, needs review

#1845 chore(site): hot-fixes wave 2
  pages/11ty/prismjs.lib.js
  pages/src/banner/banner.less
  pages/src/common/code.less
  pages/src/localdev.less
  src/modules/esl-share/README.md
Labels: site, needs review

#1839 fix(esl-utils): debounced unhandled rejection
  src/modules/esl-utils/async/promise/defered.ts
  src/modules/esl-utils/async/test/promise/defered.test.ts
Labels: bug, require squash, needs review

#1853 fix(esl-toggleable): fix activator when close-on inner trigger click handled (#1852)
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-toggleable/test/toggleable.close-on.test.ts
Labels: needs review

#1862 feat(esl-utils): `lockScroll` / `unlockScroll` methods reworked with no-scroll detection
  src/modules/esl-utils/dom/scroll.less
  src/modules/esl-utils/dom/scroll/utils.ts
Labels: enhancement

#1873 feat(esl-utils): make __esl_sequanse__ a private key using Symbol
  src/modules/esl-utils/dom/events/target.ts
  src/modules/esl-utils/misc/uid.ts
Labels: enhancement, not ready for merge, require squash, needs review

#1891 fix: support for items being moved from iframe using unified `isElement` check
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-traversing-query/core/esl-traversing-query.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-utils/abstract/dom-target.ts
  src/modules/esl-utils/abstract/test/dom-target.test.ts
  src/modules/esl-utils/dom/api.ts
  src/modules/esl-utils/dom/scroll/parent.ts
  src/modules/esl-utils/dom/test/api.test.ts
  src/modules/esl-utils/dom/visible.ts
  src/modules/esl-utils/misc/object/test/types.test.ts
  src/modules/esl-utils/misc/object/types.ts
Labels: enhancement

#1841 feat(swipe-target): Add SwipeEventTarget
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core/targets/swipe.event.ts
  src/modules/esl-event-listener/core/targets/swipe.target.ts
  src/modules/esl-utils/dom/test/units.test.ts
  src/modules/esl-utils/dom/units.ts
Labels: feature, require squash, needs review

#1855 feat(esl-panel-group): support for esl-panel-group driven animation to closed state
  pages/src/common/tabs.less
  pages/views/draft/nav-panels.njk
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel-group/core/esl-panel-group.ts
Labels: enhancement

#1886 fix(esl-event-listener): `ESLResizeObserverTarget.for` handles no target cases silently (warning + null result)
  src/modules/esl-event-listener/core/targets/resize.adapter.ts
  src/modules/esl-event-listener/test/targets/resize.test.ts
Labels: bug, needs review
