Repository exadel-inc/esl, pull requests merged in 2023-06, with the labels that each got.

#1676 esl-popup: create appendArrow
  src/modules/esl-popup/README.md
  src/modules/esl-popup/core/esl-popup.less
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: needs review

#1693 feat(esl-event-listener): add event delegated target
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/types.ts
  src/modules/esl-event-listener/test/listener.delegate.test.ts
  src/modules/esl-utils/decorators/test/listen.test.ts
Labels: enhancement, require squash, needs review

#1723 fix(esl-utils): fix missing export of `createDeferred` method under `esl-utils/async/promise`
  src/modules/esl-utils/async/promise.ts
Labels: bug, needs review

#1725 style(esl-event-listener): regroup event listener code (#1449)
  src/modules/esl-event-listener/core/descriptors.ts
Labels: enhancement, needs review

#1690 [🚩esl-carousel]: early draft
  package.json
  pages/src/common/card.less
  pages/src/common/helpers.less
  pages/src/esl-carousel-demo/test-carousel.less
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/views/draft/carousel.njk
  pages/views/examples/carousel.11tydata.yml
  pages/views/examples/carousel.marquee.11tydata.yml
  pages/views/examples/carousel.marquee.njk
  pages/views/examples/carousel.njk
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-carousel/README.md
  src/modules/esl-carousel/all.less
  src/modules/esl-carousel/core.less
  src/modules/esl-carousel/core.ts
  src/modules/esl-carousel/core/esl-carousel.events.ts
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.types.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.utils.ts
  src/modules/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
  src/modules/esl-carousel/plugin/esl-carousel.plugin.ts
  src/modules/esl-carousel/plugin/keyboard/esl-carousel.keyboard.mixin.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.arrows.less
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.dots.less
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.dots.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.mixin.ts
  src/modules/esl-carousel/plugin/relation/esl-carousel.relation.mixin.ts
  src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
  src/modules/esl-carousel/renderers/multi/esl-multi-carousel.less
  src/modules/esl-carousel/renderers/multi/esl-multi-carousel.ts
  src/modules/esl-carousel/test/nav/esl-carousel.nav-utils.test.ts
Labels: feature

#1736 epic: esl-animate documentation, mixin and cleanup (#1281)
  pages/src/localdev.ts
  pages/views/examples/animate.njk
  src/modules/esl-animate/README.md
  src/modules/esl-animate/core.ts
  src/modules/esl-animate/core/esl-animate-mixin.ts
  src/modules/esl-animate/core/esl-animate-service.ts
  src/modules/esl-animate/test/animate.element.test.ts
  src/modules/esl-animate/test/animate.mixin.test.ts
  src/modules/esl-animate/test/animate.service.test.ts
  src/modules/esl-utils/test/intersectionObserver.mock.ts
Labels: feature, needs review

#1742 epic(esl-animate): final cleanup
  pages/src/common/simple-grid.less
  pages/views/_includes/landing/benefits.njk
  pages/views/_includes/landing/blogs.njk
  pages/views/_includes/landing/promo-banner.njk
  pages/views/components/esl-animate.njk
  pages/views/examples/animate.njk
  src/modules/esl-animate/README.md
  src/modules/esl-animate/core/esl-animate-animations.less
  src/modules/esl-animate/core/esl-animate-mixin.ts
  src/modules/esl-animate/core/esl-animate-service.ts
  src/modules/esl-animate/core/esl-animate.ts
Labels: bug, needs review

#1747 feat(esl-footnotes): add support of the anchor relationship between note and footnote for the print version
  src/modules/esl-footnotes/README.md
  src/modules/esl-footnotes/core/esl-footnotes.ts
  src/modules/esl-footnotes/core/esl-note.ts
Labels: feature
