Repository exadel-inc/esl, pull requests merged in 2023-09, with the labels that each got.

#1906 refactor(esl-event-listener): internal API and structure cleanup for `esl-event-listener` module
  src/modules/esl-event-listener/core.ts
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/targets/decorated.target.ts
  src/modules/esl-event-listener/core/targets/resize.target.event.ts
  src/modules/esl-event-listener/core/targets/resize.target.ts
  src/modules/esl-event-listener/core/targets/swipe.target.event.ts
  src/modules/esl-event-listener/core/targets/swipe.target.ts
Labels: enhancement, needs review

#1912 refactor(esl-event-listener): swipe listener examples/tests and cleanup
  pages/src/esl-swipe-demo/esl-swipe-demo-area.less
  pages/src/esl-swipe-demo/esl-swipe-demo-area.ts
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/views/draft/swipe-demo.njk
  src/modules/esl-event-listener/core/targets/swipe.target.event.ts
  src/modules/esl-event-listener/core/targets/swipe.target.ts
  src/modules/esl-event-listener/test/targets/resize.test.ts
  src/modules/esl-event-listener/test/targets/swipe.test.ts
Labels: not ready for merge, under discussion

#1919 feat(swipe-target): add angle to swipe event, simplify API
  pages/src/esl-swipe-demo/esl-swipe-demo-area.less
  pages/src/esl-swipe-demo/esl-swipe-demo-area.ts
  pages/views/draft/swipe-demo.njk
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core/targets/swipe.target.event.ts
  src/modules/esl-event-listener/core/targets/swipe.target.ts
  src/modules/esl-event-listener/test/targets/swipe.test.ts
Labels: enhancement, require squash, needs review

#1846 [:rocket: esl-share]: add out of the box share config default
  package.json
  src/modules/esl-share/README.md
  src/modules/esl-share/buttons/blogger.ts
  src/modules/esl-share/buttons/copy.ts
  src/modules/esl-share/buttons/facebook.ts
  src/modules/esl-share/buttons/hatena.ts
  src/modules/esl-share/buttons/kakao.ts
  src/modules/esl-share/buttons/line.ts
  src/modules/esl-share/buttons/linkedin.ts
  src/modules/esl-share/buttons/mail.ts
  src/modules/esl-share/buttons/mix.ts
  src/modules/esl-share/buttons/mixi.ts
  src/modules/esl-share/buttons/myspace.ts
  src/modules/esl-share/buttons/native-share.ts
  src/modules/esl-share/buttons/pinterest.ts
  src/modules/esl-share/buttons/print.ts
  src/modules/esl-share/buttons/pusha.ts
  src/modules/esl-share/buttons/reddit.ts
  src/modules/esl-share/buttons/sina-weibo.ts
  src/modules/esl-share/buttons/telegram.ts
  src/modules/esl-share/buttons/twitter.ts
  src/modules/esl-share/buttons/wykop.ts
  src/modules/esl-share/core.ts
  src/modules/esl-share/core/esl-share-config.ts
  src/modules/esl-share/core/esl-share.ts
  src/modules/esl-share/test/buttons/blogger.test.ts
  src/modules/esl-share/test/buttons/button-test-plan-factory.ts
  src/modules/esl-share/test/buttons/copy.test.ts
  src/modules/esl-share/test/buttons/facebook.test.ts
  src/modules/esl-share/test/buttons/hatena.test.ts
  src/modules/esl-share/test/buttons/kakao.test.ts
  src/modules/esl-share/test/buttons/line.test.ts
  src/modules/esl-share/test/buttons/linkedin.test.ts
  src/modules/esl-share/test/buttons/mail.test.ts
  src/modules/esl-share/test/buttons/mix.test.ts
  src/modules/esl-share/test/buttons/mixi.test.ts
  src/modules/esl-share/test/buttons/myspace.test.ts
  src/modules/esl-share/test/buttons/native-share.test.ts
  src/modules/esl-share/test/buttons/pinterest.test.ts
  src/modules/esl-share/test/buttons/print.test.ts
  src/modules/esl-share/test/buttons/pusha.test.ts
  src/modules/esl-share/test/buttons/reddit.test.ts
  src/modules/esl-share/test/buttons/sina-weibo.test.ts
  src/modules/esl-share/test/buttons/telegram.test.ts
  src/modules/esl-share/test/buttons/twitter.test.ts
  src/modules/esl-share/test/buttons/wykop.test.ts
  tsconfig.json
Labels: feature, needs review

#1923 chore(site): package structure rework (❗CRITICAL - PLEASE REVIEW❗)
  .eslintrc.yml
  .github/dependabot.yml
  .github/workflows/pages.yml
  package-lock.json
  package.json
  pages/.eleventy.js
  pages/package.json
  pages/src/anchor/anchor-link.ts
  pages/src/back-link/back-link.ts
  pages/src/banner/banner.ts
  pages/src/common/breakpoints.ts
  pages/src/esl-media-demo/test-media-source.ts
  pages/src/esl-media-demo/test-media.ts
  pages/src/landing/marquee/marquee.ts
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/src/navigation/header/header-search.ts
  pages/src/navigation/sidebar/sidebar.ts
  pages/src/polyfill-full.ts
  pages/src/polyfill-light.ts
  pages/src/search/search-script.ts
  pages/src/search/search.ts
  pages/tsconfig.json
  pages/webpack.config.js
  src/modules/esl-utils/async/test/promise/raf.test.ts
  tsconfig.json
Labels: enhancement, needs review

#1918 feat(docs): open external links in a new window
  pages/11ty/markdown.shortcut.js
Labels: documentation, require squash, needs review

#1929 chore: env small build process enchancements
  .github/dependabot.yml
  .github/workflows/pages.yml
  package-lock.json
  package.json
  pages/package.json
Labels: enhancement

#1901 [🚩epic: esl-event-listener]: `ESLSwipeEventTarget` implementation to subscribe to `swipe` events using `ESLEventListener`
  pages/src/esl-swipe-demo/esl-swipe-demo-area.less
  pages/src/esl-swipe-demo/esl-swipe-demo-area.ts
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/views/blogs/ESL v4.10.0.md
  pages/views/blogs/ESL v4.11.0.md
  pages/views/blogs/ESL v4.12.0.md
  pages/views/draft/swipe-demo.njk
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core.ts
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/targets/decorated.target.ts
  src/modules/esl-event-listener/core/targets/resize.target.event.ts
  src/modules/esl-event-listener/core/targets/resize.target.ts
  src/modules/esl-event-listener/core/targets/swipe.target.event.ts
  src/modules/esl-event-listener/core/targets/swipe.target.ts
  src/modules/esl-event-listener/test/targets/resize.test.ts
  src/modules/esl-event-listener/test/targets/swipe.test.ts
  src/modules/esl-utils/dom/test/units.test.ts
  src/modules/esl-utils/dom/units.ts
Labels: feature, needs review

#1896 [🚀esl-share]: rework esl-share-button custom element API
  pages/views/examples/share.njk
  src/modules/esl-share/actions/copy-action.ts
  src/modules/esl-share/actions/external-action.ts
  src/modules/esl-share/actions/media-action.ts
  src/modules/esl-share/core/esl-share-action-registry.ts
  src/modules/esl-share/core/esl-share-button.less
  src/modules/esl-share/core/esl-share-button.ts
  src/modules/esl-share/core/esl-share-config.ts
  src/modules/esl-share/core/esl-share.ts
Labels: feature, needs review

#1932 fix(esl-tabs): observe element resize instead of window using `ESLResizeObserverTarget`
  src/modules/esl-tab/core/esl-tabs.ts
Labels: bug, needs review

#1938 chore(site): add build version, site-config usage and small cleanup
  .github/workflows/pages.yml
  pages/11ty/env.config.js
  pages/11ty/markdown.shortcut.js
  pages/11ty/site.config.js
  pages/site.yml
  pages/static/tools/.nojekyll
  pages/views/robots.njk
  pages/views/sitemap.njk
Labels: site, maintenance

#1935 docs: add privacy policy for website
  docs/PRIVACY_POLICY.md
  pages/views/_includes/navigation/footer-compact.njk
  pages/views/_includes/navigation/footer.njk
  pages/views/privacy-policy.njk
Labels: documentation, needs review

#1854 feat(esl-media): add extended `lazy` attribute support⚠️
  pages/views/examples/embedded-video.njk
  src/modules/esl-media/README.md
  src/modules/esl-media/core/esl-media-iobserver.ts
  src/modules/esl-media/core/esl-media.shape.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-media/test/esl-media.lazy.test.ts
Labels: feature, needs review

#1374 feat(eslint): create custom rule for deprecated alias
  .eslintignore
  .eslintrc.yml
  eslint/core/deprecated-alias.d.ts
  eslint/core/deprecated-alias.js
  eslint/index.js
  eslint/jest.config.js
  eslint/package.json
  eslint/rules/4/deprecated.deep-compare.js
  eslint/rules/4/deprecated.event-utils.js
  eslint/rules/4/deprecated.generate-uid.js
  eslint/rules/4/deprecated.toggleable-action-params.js
  eslint/rules/4/deprecated.traversing-query.js
  eslint/test/deprecated-alias.invalid.test.ts
  eslint/test/deprecated-alias.valid.test.ts
  jest.config.js
  package-lock.json
  package.json
Labels: require squash, needs review

#1943 feat: UIPlayground integration (epic/playground->redesign)
  package-lock.json
  pages/package.json
  pages/src/banner/banner.ts
  pages/src/common/code.less
  pages/src/common/media.less
  pages/src/esl-media-demo/test-media-source.ts
  pages/src/esl-media-demo/test-media.less
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/src/ui-playground/ui-playground.less
  pages/views/components/esl-media.njk
  pages/views/draft/ui-playground/accordion.njk
  pages/views/draft/ui-playground/media.njk
  pages/views/draft/ui-playground/scrollbar.njk
  pages/views/examples/accordion.njk
  pages/views/examples/embedded-audio.njk
  pages/views/examples/embedded-video.njk
  pages/views/examples/scrollbar.njk
Labels: site, require squash, needs review

#1965 chore(site): migrate `html-minifier` to `html-minifier-terser` (supported continuation for initial plugin)
  package-lock.json
  pages/11ty/htmlmin.transform.js
  pages/package.json
Labels: maintenance, needs review
