Repository exadel-inc/esl, pull requests merged in 2023-10, with the labels that each got.

#1974 fix(esl-utils): fix random access to undefined error of `debounce` helper
  src/modules/esl-utils/async/debounce.ts
Labels: bug, needs review

#1971 docs(esl-media-query): improve documentation
  src/modules/esl-media-query/README.md
Labels: documentation

#1978 chore(eslint): migrate eslint rules to ts
  .eslintignore
  .eslintrc.yml
  .gitignore
  eslint/core/deprecated-alias.d.ts
  eslint/core/deprecated-alias.js
  eslint/index.js
  eslint/package.json
  eslint/src/core/deprecated-alias.ts
  eslint/src/index.ts
  eslint/src/rules/4/deprecated.deep-compare.ts
  eslint/src/rules/4/deprecated.event-utils.ts
  eslint/src/rules/4/deprecated.generate-uid.ts
  eslint/src/rules/4/deprecated.toggleable-action-params.ts
  eslint/src/rules/4/deprecated.traversing-query.ts
  eslint/src/test/deprecated-alias.invalid.test.ts
  eslint/src/test/deprecated-alias.valid.test.ts
  eslint/tsconfig.json
  jest.config.js
  linting/eslint.eslintrc.yml
Labels: needs review

#1679 fix(esl-toggleable): doesn't update after changing the activator
  src/modules/esl-popup/core/esl-popup.ts
Labels: bug, postponed

#1985 refactor(esl-toggleable): update API with before show/hide livecycle hooks
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: enhancement, needs review

#1946 [🚀esl-share]: popup internal implementation follow-up
  src/modules/esl-popup/core.ts
  src/modules/esl-popup/core/esl-popup.shape.ts
  src/modules/esl-share/core.ts
  src/modules/esl-share/core/esl-share-popup.shape.ts
  src/modules/esl-share/core/esl-share-popup.ts
  src/modules/esl-share/core/esl-share-trigger.ts
  src/modules/esl-share/core/esl-share.ts
  src/modules/esl-tooltip/core.ts
  src/modules/esl-tooltip/core/esl-tooltip.shape.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: feature, needs review

#1986 feat(esl-event-listener): create ESLIntersectionTarget adapter utility for managing `IntersectionObserver` subscriptions trough event listeners
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core.ts
  src/modules/esl-event-listener/core/targets/intersection.event.ts
  src/modules/esl-event-listener/core/targets/intersection.target.ts
  src/modules/esl-event-listener/test/targets/intersection.test.ts
  src/modules/esl-utils/test/intersectionObserver.mock.ts
Labels: feature, needs review

#2003 chore: fix updating `package-lock.json` submodules versions and enhance version update flow
  package-lock.json
  package.json
  pages/package.json
Labels: enhancement

#2006 refactor(esl-share): revisit `ESLShareConfig` API, create tests and documentation
  pages/src/localdev.ts
  pages/views/components/esl-share.njk
  pages/views/draft/share-regression.njk
  src/modules/esl-share/README.md
  src/modules/esl-share/buttons/blogger.ts
  src/modules/esl-share/buttons/copy.ts
  src/modules/esl-share/buttons/facebook.ts
  src/modules/esl-share/buttons/hatena.ts
  src/modules/esl-share/buttons/kakao.ts
  src/modules/esl-share/buttons/line.ts
  src/modules/esl-share/buttons/linkedin.ts
  src/modules/esl-share/buttons/mail.ts
  src/modules/esl-share/buttons/mix.ts
  src/modules/esl-share/buttons/mixi.ts
  src/modules/esl-share/buttons/myspace.ts
  src/modules/esl-share/buttons/native-share.ts
  src/modules/esl-share/buttons/pinterest.ts
  src/modules/esl-share/buttons/print.ts
  src/modules/esl-share/buttons/pusha.ts
  src/modules/esl-share/buttons/reddit.ts
  src/modules/esl-share/buttons/sina-weibo.ts
  src/modules/esl-share/buttons/telegram.ts
  src/modules/esl-share/buttons/twitter.ts
  src/modules/esl-share/buttons/wykop.ts
  src/modules/esl-share/core/esl-share-button.ts
  src/modules/esl-share/core/esl-share-config.ts
  src/modules/esl-share/core/esl-share-list.ts
  src/modules/esl-share/core/esl-share-popup.ts
  src/modules/esl-share/test/esl-share-config.test.ts
Labels: enhancement, needs review

#2008 chore: ignore lint-staged action in case merge commit processing locally
  .husky/pre-commit
Labels: enhancement, needs review

#2011 docs(site): promo release notes for v4.13.0 created
  pages/views/blogs/ESL v4.13.0.md
  src/modules/esl-event-listener/README.md
Labels: site
