Repository exadel-inc/esl, pull requests merged in 2023-02, with the labels that each got.

#1451 docs(esl-event-listener): `esl-event-listener` module updated documentation & type fixes
  pages/src/common/markdown.less
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/descriptors.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/test/descriptor.test.ts
  src/modules/esl-mixin-element/test/mixin.listener.test.ts
  src/modules/esl-utils/misc/object/types.ts
Labels: documentation

#1431 esl-note-ignore mixin: initial implementation
  pages/src/localdev.ts
  src/modules/esl-footnotes/core.ts
  src/modules/esl-footnotes/core/esl-note-ignore.ts
Labels: feature

#1463 fix(esl-utils): `memoize.clear` and `memoize.has` signature types improved
  src/modules/esl-utils/decorators/memoize.ts
Labels: bug

#1440 fix(esl-image): attribute callback before connect
  src/modules/esl-image/core/esl-image.ts
Labels: bug, needs review

#1468 chore: Code Climate integration to the CI process
  .github/workflows/validate.yml
  package.json
Labels: maintenance

#1458 chore(deps-dev): bump eleventy to 2.0
  package-lock.json
  package.json
  pages/.eleventy.js
  pages/11ty/open.postaction.js
Labels: dependencies

#1489 docs: update exadel logo
  docs/images/exadel-logo.png
Labels: documentation

#1494 docs: small typo fixes and updates in `ESLMixinElement` and `ESLBaseElement` related to #1460
  src/modules/esl-base-element/README.md
  src/modules/esl-mixin-element/README.md
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
Labels: documentation

#1486 feat(esl-event-listener): resize observer target utility
  jest.config.js
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/targets/resize.adapter.ts
  src/modules/esl-event-listener/test/targets/resize.test.ts
  src/modules/esl-utils/dom/events/target.ts
  src/modules/esl-utils/test/resizeObserver.mock.ts
Labels: feature, under discussion

#1500 fix(esl-media): `ref:` prefix is optional, user should be able to use internal id
  src/modules/esl-media/providers/brightcove-provider.ts
Labels: bug

#1501 feat(esl-utils): SyntheticEventTarget API extended with ability to choose target value and specify default event type
  src/modules/esl-utils/dom/events/target.ts
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/memoize.ts
Labels: enhancement

#1499 refactor(esl-utils): `RTLUtils` now deprecated and recreated in tree-shakable way
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-tab/core/esl-tabs.ts
  src/modules/esl-utils/dom/rtl.ts
  src/modules/esl-utils/dom/test/rtl.test.ts
Labels: enhancement
