Repository exadel-inc/esl, pull requests merged in 2023-05, with the labels that each got.

#1633 feat: ES5/IE11 cleanup (part 1)
  pages/src/landing/marquee/marquee.ts
  src/modules/esl-alert/core/esl-alert.less
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-utils/dom/events/target.ts
  src/modules/esl-utils/dom/events/test/target.test.ts
  src/modules/esl-utils/fixes.ts
  src/modules/esl-utils/fixes/ie-fixes.less
  src/modules/esl-utils/fixes/ie-fixes.ts
  src/modules/esl-utils/fixes/viewport.ts
  src/modules/esl-utils/misc/array.ts
  src/modules/esl-utils/misc/set.ts
  src/modules/esl-utils/misc/test/array.test.ts
Labels: enhancement, breaking-change, needs review

#1642 feat: `ESLBaseComponent` interface shared between `ESLMixinElement` and `ESLBaseElement`
  src/modules/draft/esl-carousel/core/esl-carousel.ts
  src/modules/draft/esl-carousel/plugin/esl-carousel-link.plugin.ts
  src/modules/esl-animate/core/esl-animate.ts
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-item.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-tab/core/esl-tabs.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-utils/abstract/component.ts
Labels: enhancement, needs review

#1651 feat(esl-mixin-element): v2.0.0 improvements
  .eslintrc.yml
  package.json
  src/modules/esl-mixin-element/README.md
  src/modules/esl-mixin-element/test/mixin.attributes.test.ts
  src/modules/esl-mixin-element/test/mixin.decorators.test.ts
  src/modules/esl-mixin-element/test/mixin.test.ts
  src/modules/esl-mixin-element/ui/esl-mixin-attr.ts
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
  src/modules/esl-mixin-element/ui/esl-mixin-registry.ts
  tsconfig.build.json
  tsconfig.json
Labels: enhancement, feature, needs review

#1654 fix(esl-utils): fix unwrap method signature types
  src/modules/esl-utils/misc.ts
  src/modules/esl-utils/misc/array.ts
  src/modules/esl-utils/misc/object.ts
  src/modules/esl-utils/misc/test/object.test.ts
Labels: needs review

#1663 docs(esl-share): add `esl-share` component page to UI server
  pages/views/components/esl-share.njk
Labels: site, needs review

#1662 fix(esl-utils): make ts decorators compatiable with babel
  src/modules/esl-utils/decorators/attr.ts
  src/modules/esl-utils/decorators/bool-attr.ts
  src/modules/esl-utils/decorators/json-attr.ts
  src/modules/esl-utils/decorators/prop.ts
Labels: needs review

#1665 refactor(esl-utils): fix export of `esl-utils/misc/url`
  src/modules/esl-utils/misc.ts
Labels: enhancement

#1664 🚩epic: release esl-share 1.0.0-beta -> 4.6.0 stable
  package.json
  pages/src/esl-share/esl-share.less
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/src/navigation/header/header.less
  pages/src/navigation/sidebar/sidebar-primary-nav.less
  pages/src/page/landing-layout.less
  pages/static/assets/common/header-share.svg
  pages/static/assets/examples/share.svg
  pages/static/assets/share/config.json
  pages/views/_includes/navigation/header.njk
  pages/views/_includes/navigation/sidebar.njk
  pages/views/components/esl-share.njk
  pages/views/examples/share.njk
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-share/README.md
  src/modules/esl-share/actions/copy-action.ts
  src/modules/esl-share/actions/external-action.ts
  src/modules/esl-share/actions/media-action.ts
  src/modules/esl-share/actions/native-action.ts
  src/modules/esl-share/actions/print-action.ts
  src/modules/esl-share/actions/url-generic-action.ts
  src/modules/esl-share/core.less
  src/modules/esl-share/core.ts
  src/modules/esl-share/core/esl-share-action-registry.ts
  src/modules/esl-share/core/esl-share-action.ts
  src/modules/esl-share/core/esl-share-button.less
  src/modules/esl-share/core/esl-share-button.shape.ts
  src/modules/esl-share/core/esl-share-button.ts
  src/modules/esl-share/core/esl-share.less
  src/modules/esl-share/core/esl-share.shape.ts
  src/modules/esl-share/core/esl-share.ts
  src/modules/esl-utils/misc.ts
  src/modules/esl-utils/misc/test/url.test.ts
  src/modules/esl-utils/misc/url.ts
Labels: feature, needs review

#1678 feat(esl-carousel): restructuring wave 2
  pages/views/examples/carousel.marquee.njk
  pages/views/examples/carousel.njk
  src/modules/esl-carousel/core.ts
  src/modules/esl-carousel/core/esl-carousel.events.ts
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.utils.ts
  src/modules/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.dots.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.mixin.ts
  src/modules/esl-carousel/plugin/relation/esl-carousel.relation.mixin.ts
  src/modules/esl-carousel/renderers/multi/esl-multi-carousel.ts
  src/modules/esl-carousel/test/nav/esl-carousel.nav-utils.test.ts
  src/modules/esl-utils/async/promise.ts
Labels: enhancement

#1685 [esl-carousel]: restructuring wave 3
  pages/src/common/helpers.less
  pages/views/examples/carousel.njk
  src/modules/esl-carousel/core/esl-carousel.events.ts
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.types.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.dots.ts
  src/modules/esl-carousel/renderers/multi/esl-multi-carousel.ts
  src/modules/esl-carousel/test/nav/esl-carousel.nav-utils.test.ts
  src/modules/esl-utils/async.ts
  src/modules/esl-utils/async/microtask.ts
  src/modules/esl-utils/async/test/microtask.test.ts
Labels: enhancement

#1689 [esl-carousel]: update a11y of slides and dots
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.dots.ts
Labels: enhancement
