Repository exadel-inc/esl, pull requests merged in 2023-07, with the labels that each got.

#1762 fix: default print styles for toggleables and gh-pages
  pages/src/landing/benefits/benefits.less
  pages/src/landing/browser-support/browser-support.less
  pages/src/landing/marquee/marquee.less
  pages/src/landing/overview/overview.less
  pages/src/landing/promo-banner/promo-banner.less
  pages/src/navigation/footer/footer.less
  pages/src/navigation/sidebar/sidebar.less
  pages/src/page/base-layout.less
  pages/src/page/landing-layout.less
  pages/src/page/sidebar-layout.less
  src/modules/esl-animate/core/esl-animate-animations.less
  src/modules/esl-panel-group/core/esl-panel-group.less
  src/modules/esl-panel/core/esl-panel.less
Labels: bug

#1764 refactor (esl-footnotes): renaming attribute for anchor media query
  src/modules/esl-footnotes/README.md
  src/modules/esl-footnotes/core/esl-note.ts
Labels: needs review

#1766 fix(esl-core): register checks improvements
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-base-element/test/element.test.ts
Labels: bug, enhancement

#1765 epic(esl-select): reworked using esl-popup (#1321)
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-forms/esl-select/core/esl-select-renderer.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
Labels: needs review

#1767 fix(esl-mixin-element): performance improvement
  src/modules/esl-mixin-element/test/mixin.test.ts
  src/modules/esl-mixin-element/ui/esl-mixin-registry.ts
Labels: bug, enhancement, needs review

#1761 epic(footnotes): stable target
  pages/src/localdev.ts
  src/modules/esl-footnotes/README.md
  src/modules/esl-footnotes/core.ts
  src/modules/esl-footnotes/core/esl-footnotes.ts
  src/modules/esl-footnotes/core/esl-note-ignore.ts
  src/modules/esl-footnotes/core/esl-note.ts
Labels: feature, needs review

#1668 esl-share: create popup mode
  pages/static/assets/examples/share-trigger-icon.svg
  pages/static/assets/examples/share.svg
  pages/views/draft/share-regression.njk
  pages/views/examples/share.njk
  src/modules/esl-share/README.md
  src/modules/esl-share/core.less
  src/modules/esl-share/core.ts
  src/modules/esl-share/core/esl-share-button.ts
  src/modules/esl-share/core/esl-share-config.ts
  src/modules/esl-share/core/esl-share-trigger.less
  src/modules/esl-share/core/esl-share-trigger.shape.ts
  src/modules/esl-share/core/esl-share-trigger.ts
  src/modules/esl-share/core/esl-share.ts
Labels: feature, under discussion, needs review

#1781 epic(esl-share): popup support for 4.9.0
  pages/static/assets/examples/share-trigger-icon.svg
  pages/static/assets/examples/share.svg
  pages/views/draft/share-regression.njk
  pages/views/examples/share.njk
  src/modules/esl-share/README.md
  src/modules/esl-share/core.less
  src/modules/esl-share/core.ts
  src/modules/esl-share/core/esl-share-button.ts
  src/modules/esl-share/core/esl-share-config.ts
  src/modules/esl-share/core/esl-share-trigger.less
  src/modules/esl-share/core/esl-share-trigger.shape.ts
  src/modules/esl-share/core/esl-share-trigger.ts
  src/modules/esl-share/core/esl-share.ts
Labels: feature

#1782 fix: hotfix for writeable `is` field short initialization syntax
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-base-element/test/element.test.ts
Labels: hotfix

#1795 fix(esl-footnotes): remove the possibility of setup esl-note anchor markup conditionally
  src/modules/esl-footnotes/core/esl-note.less
  src/modules/esl-footnotes/core/esl-note.ts
Labels: needs review, hotfix

#1797 fix(esl-footnotes): esl-tooltip related to the note does not perceive direction and language of original content
  pages/views/examples/footnotes.njk
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-tooltip/core/esl-tooltip.less
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: needs review, hotfix

#1805 fix(esl-base-element): fix redefine tag feature (existing component receives incorrect tag name)
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-base-element/test/element.test.ts
Labels: needs review, hotfix

#1821 🚩 epic(site): Redesign 2023 - Wave 1
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  pages/.eleventy.js
  pages/11ty/date.filter.js
  pages/11ty/hidden.filter.js
  pages/11ty/markdown.img.lib.js
  pages/11ty/markdown.lib.js
  pages/11ty/released.filter.js
  pages/11ty/sort.filter.js
  pages/site.yml
  pages/src/banner/banner.less
  pages/src/banner/banner.ts
  pages/src/banner/redesign.ts
  pages/src/common/buttons.less
  pages/src/common/code.less
  pages/src/common/colors.less
  pages/src/common/helpers.less
  pages/src/common/markdown.less
  pages/src/common/reboot.less
  pages/src/common/typography.less
  pages/src/landing/blogs/blogs.less
  pages/src/landing/landing.less
  pages/src/landing/newsline/newsline-stars.less
  pages/src/landing/newsline/newsline.less
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/src/navigation/header/header-search.less
  pages/src/navigation/header/header-search.ts
  pages/src/navigation/header/header.less
  pages/src/navigation/sidebar/sidebar-content.less
  pages/src/navigation/sidebar/sidebar-primary-nav.less
  pages/src/navigation/sidebar/sidebar-share.less
  pages/src/navigation/sidebar/sidebar.less
  pages/src/search/search.less
  pages/static/assets/common/share.svg
  pages/views/_data/banner.yml
  pages/views/_includes/landing/blogs.njk
  pages/views/_includes/landing/newsline.njk
  pages/views/_includes/navigation/banner.njk
  pages/views/_includes/navigation/footer.njk
  pages/views/_includes/navigation/header.njk
  pages/views/_includes/navigation/sidebar-item.njk
  pages/views/_includes/navigation/sidebar.njk
  pages/views/_layouts/collection-grid.njk
  pages/views/_layouts/content.njk
  pages/views/blogs/ESL v4.0.0.md
  pages/views/blogs/ESL v4.9.0.md
  pages/views/blogs/ESL v5.0.0 Announce.md
  pages/views/components/index.njk
  pages/views/core/index.njk
  pages/views/examples/footnotes.njk
  pages/views/examples/index.njk
  pages/views/index.11tydata.yml
  pages/views/index.njk
  pages/views/introduction/contribute.njk
  pages/views/introduction/roadmap.njk
  pages/views/redirect/roadmap.njk
  pages/views/search.njk
Labels: site, needs review

#1800 fix(esl-togglable): open attribute change behavior
  src/modules/esl-toggleable/core/esl-toggleable-dispatcher.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: bug, needs review

#1829 fix(esl-footnotes): shape to support TSX is missing in esl-footnotes module
  src/modules/esl-footnotes/README.md
  src/modules/esl-footnotes/core.ts
  src/modules/esl-footnotes/core/esl-footnotes.shape.ts
  src/modules/esl-footnotes/core/esl-note.shape.ts
Labels: needs review

#1830 chore(site): fix `btn-link` styles on project site
  pages/src/common/buttons.less
Labels: site, needs review

#1835 chore(site): fix banner appears after rejection on all pages except the page where it was just closed
  pages/src/banner/banner.ts
Labels: bug, site, needs review

#1818 test(esl-utils): test coverage for utils/dom/attr
  src/modules/esl-utils/dom/test/attr.test.ts
Labels: needs review
