Repository exadel-inc/esl, pull requests merged in 2023-01, with the labels that each got.

#1400 fix(esl-popup): protected methods visibility
  src/modules/esl-popup/core/esl-popup.ts
Labels: bug, enhancement

#1395 chore: update semantic-release and dev node version (main-beta -> main)
  .github/workflows/commit.yml
  .github/workflows/pages.yml
  .github/workflows/release.yml
  .github/workflows/validate.yml
  docs/DEVELOPMENT.md
  package-lock.json
  package.json
Labels: maintenance

#1405 chore(eslint): add 'arrow-parens' rule, fix existing warns
  README.md
  linting/codestyle.eslintrc.yml
  src/modules/esl-utils/dom/focus.ts
  src/modules/esl-utils/misc/object/copy.ts
  src/modules/esl-utils/misc/set.ts
Labels: enhancement

#1398 feat(esl-related-target): make related target able to targeting multiple related togglable
  build/jest.html-loader.js
  jest.config.js
  package-lock.json
  pages/views/examples/accordion.njk
  src/modules/esl-related-target/README.md
  src/modules/esl-related-target/core/esl-related-target.ts
  src/modules/esl-related-target/test/related-target.test.ts
  src/modules/esl-related-target/test/template.html
Labels: feature, require squash

#1427 fix(esl-mixin-element): fix oldValue argument of attributeChangedCallback
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
Labels: bug

#1425 fix(esl-footnotes): esl-note is not respond on "ignore" attribute change
  src/modules/esl-footnotes/core/esl-note.ts
Labels: bug

#1341 feat(esl-utils): isVisible predicate
  src/modules/esl-traversing-query/README.md
  src/modules/esl-traversing-query/core/esl-traversing-query.ts
  src/modules/esl-traversing-query/test/esl-traversing-query.test.ts
  src/modules/esl-utils/README.md
  src/modules/esl-utils/dom.ts
  src/modules/esl-utils/dom/rect.ts
  src/modules/esl-utils/dom/test/rect.test.ts
  src/modules/esl-utils/dom/test/visible.test.ts
  src/modules/esl-utils/dom/traversing.ts
  src/modules/esl-utils/dom/visible.ts
Labels: feature, require squash

#1437 feat(esl-event-listener): bugfix and implementation rework of ESLEventListener descriptors
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-event-listener/core.ts
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/descriptors.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/types.ts
  src/modules/esl-event-listener/test/descriptor.test.ts
  src/modules/esl-event-listener/test/utils.test.ts
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
  src/modules/esl-utils/decorators/listen.ts
  src/modules/esl-utils/decorators/test/listen.test.ts
Labels: bug, enhancement
