Repository exadel-inc/esl, pull requests merged in 2023-03, with the labels that each got.

#1515 refactor(esl-utils): rework internal `AttributeTarget` type to separate `ESLDomElementRelated` implementation
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
  src/modules/esl-utils/abstract/dom-target.ts
  src/modules/esl-utils/decorators/attr.ts
  src/modules/esl-utils/decorators/bool-attr.ts
  src/modules/esl-utils/decorators/json-attr.ts
  src/modules/esl-utils/decorators/listen.ts
  src/modules/esl-utils/dom/attr.ts
Labels: enhancement

#1358 epic (esl-share): initial implementation
  package.json
  pages/src/esl-share/esl-share.less
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/static/assets/examples/share.svg
  pages/static/assets/share/config.json
  pages/views/examples/share.njk
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-share/README.md
  src/modules/esl-share/actions/copy-action.ts
  src/modules/esl-share/actions/external-action.ts
  src/modules/esl-share/actions/media-action.ts
  src/modules/esl-share/actions/native-action.ts
  src/modules/esl-share/actions/print-action.ts
  src/modules/esl-share/actions/url-generic-action.ts
  src/modules/esl-share/core.less
  src/modules/esl-share/core.ts
  src/modules/esl-share/core/esl-share-action-registry.ts
  src/modules/esl-share/core/esl-share-action.ts
  src/modules/esl-share/core/esl-share-button.less
  src/modules/esl-share/core/esl-share-button.ts
  src/modules/esl-share/core/esl-share-list.less
  src/modules/esl-share/core/esl-share-list.ts
  src/modules/esl-utils/misc.ts
  src/modules/esl-utils/misc/test/url.test.ts
  src/modules/esl-utils/misc/url.ts
Labels: feature

#1511 feat(esl-event-listener): extended event targets ( epic: event utils 3.0.0 )
  jest.config.js
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/descriptors.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/targets/decorated.target.ts
  src/modules/esl-event-listener/core/targets/resize.adapter.ts
  src/modules/esl-event-listener/core/types.ts
  src/modules/esl-event-listener/test/targets/decorator.test.ts
  src/modules/esl-event-listener/test/targets/resize.test.ts
  src/modules/esl-utils/dom/events/target.ts
  src/modules/esl-utils/test/resizeObserver.mock.ts
Labels: enhancement

#1527 fix(esl-event-listener): (HOTFIX) `@listen` should not require host typeof `ESLDomElementTarget`
  src/modules/esl-utils/decorators/listen.ts
Labels: bug, hotfix

#1536 feat(esl-core): make this.constructor strictly typed for `ESLBaseElement` and `ESLMixinElement`
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/test/esl-trigger.a11y.test.ts
Labels: needs review

#1538 refactor(esl-share): merge list and group attributes
  pages/static/assets/share/config.json
  pages/views/examples/share.njk
  src/modules/esl-share/core/esl-share-list.ts
Labels: needs review

#1537 fix(esl-event-listener): fix `ESLEventTargetDecorator` dispatched event `target`
  src/modules/esl-event-listener/core/targets/decorated.target.ts
  src/modules/esl-event-listener/core/targets/resize.adapter.ts
  src/modules/esl-event-listener/test/targets/decorator.test.ts
  src/modules/esl-utils/dom/events/misc.ts
  src/modules/esl-utils/dom/events/target.ts
Labels: needs review

#1551 Revert "feat(esl-core): make this.constructor strictly typed for `ESLBaseElement` and `ESLMixinElement`"
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-base-element/test/element.listener.test.ts
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-item.ts
  src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-toggleable/test/toggleable.request.test.ts
  src/modules/esl-trigger/test/esl-trigger.a11y.test.ts
Labels: under discussion, needs review

#1502 refactor: Drop IE11 support
  README.md
  docs/BROWSER_SUPPORT.md
  package-lock.json
  package.json
  pages/src/localdev.ts
  pages/src/polyfill-full.ts
  pages/src/polyfill-medium.ts
  pages/src/polyfill.ts
  pages/views/_includes/polyfill.njk
  pages/webpack.config.js
  src/modules/draft/esl-carousel/core/esl-carousel-arrows.less
  src/modules/esl-tab/core/esl-tabs.arrows.less
  src/polyfills/list/dom.element.closest.ts
  src/polyfills/list/dom.element.toggleAttribute.ts
  src/polyfills/list/dom.event.base.ts
  src/polyfills/list/dom.event.custom.ts
  src/polyfills/list/dom.event.focus.ts
  src/polyfills/list/dom.event.keyboard.ts
  src/polyfills/list/dom.event.mouse.ts
  src/polyfills/list/dom.keyboard.key.ts
  src/polyfills/list/dom.node.isConnected.ts
  src/polyfills/list/dom.tokenList.toggle.ts
  src/polyfills/list/es6.array.find.ts
  src/polyfills/list/es6.array.from.ts
  src/polyfills/list/es6.array.includes.ts
  src/polyfills/list/es6.object.assign.ts
  src/polyfills/list/es6.object.is.ts
  src/polyfills/polyfills.es5.ts
  src/polyfills/polyfills.es6.ts
  src/polyfills/test/es6.object.assign.test.ts
Labels: dependencies, breaking-change, needs review

#1576 fix(esl-event-listener): fix typechecking for TS5
  src/modules/esl-event-listener/core/listener.ts
Labels: enhancement

#1575 fix(esl-media): fix `iv_load_policy` param and small test regexp optimization in YouTube provider
  src/modules/esl-media/providers/youtube-provider.ts
Labels: bug

#1580 fix(esl-event-listener): ehnance checking of event target instance when delegating
  src/modules/esl-event-listener/core/listener.ts
Labels: bug, needs review
