Repository exadel-inc/esl, pull requests merged in 2023-04, with the labels that each got.

#1585 refactor(esl-utils): introduce standardized way to resolve `ESLDomElementRelated` - `resolveDomTarget`
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-utils/abstract/dom-target.ts
  src/modules/esl-utils/dom/attr.ts
Labels: enhancement

#1568 docs(esl-share): add documentation
  pages/views/examples/share.njk
  src/modules/esl-share/README.md
  src/modules/esl-share/actions/copy-action.ts
  src/modules/esl-share/actions/external-action.ts
  src/modules/esl-share/actions/media-action.ts
  src/modules/esl-share/actions/native-action.ts
  src/modules/esl-share/actions/print-action.ts
  src/modules/esl-share/actions/url-generic-action.ts
  src/modules/esl-share/core/esl-share-action-registry.ts
  src/modules/esl-share/core/esl-share-action.ts
  src/modules/esl-share/core/esl-share-button.shape.ts
  src/modules/esl-share/core/esl-share-button.ts
  src/modules/esl-share/core/esl-share-list.shape.ts
  src/modules/esl-share/core/esl-share-list.ts
Labels: documentation

#1592 feat(esl-event-listener): improved `ESLResizeObserverTarget` API with a standardized `ESLElementResizeEvent`
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-event-listener/core.ts
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/targets/resize.adapter.event.ts
  src/modules/esl-event-listener/core/targets/resize.adapter.ts
  src/modules/esl-event-listener/core/types.ts
  src/modules/esl-event-listener/test/targets/resize.test.ts
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
  src/modules/esl-utils/decorators/listen.ts
Labels: enhancement

#1573 feat(esl-utils): Support for ESLDomElementTarget as a target for ESLResizeObserverTarget
  src/modules/esl-event-listener/core/targets/resize.adapter.ts
  src/modules/esl-event-listener/test/targets/resize.test.ts
Labels: enhancement, require squash, needs review

#1602 refactor(esl-event-listener): change API of extended EventTargets
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core.ts
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/targets/decorated.target.ts
  src/modules/esl-event-listener/core/targets/resize.adapter.ts
  src/modules/esl-event-listener/test/targets/decorator.test.ts
  src/modules/esl-event-listener/test/targets/resize.test.ts
Labels: needs review

#1596 fix(gh-pages): add new favicon icons
  pages/static/assets/favicon/apple-touch-icon.png
  pages/static/assets/favicon/icon-192.png
  pages/static/assets/favicon/icon-512.png
  pages/static/assets/favicon/icon.svg
  pages/static/assets/logo-64x64.png
  pages/static/tools/favicon.ico
  pages/static/tools/manifest.webmanifest
  pages/views/_layouts/base.njk
Labels: site, needs review

#1595 fix(esl-utils): incorrect throttle behaviour
  src/modules/esl-event-listener/test/targets/decorator.test.ts
  src/modules/esl-utils/async/test/throttle.test.ts
  src/modules/esl-utils/async/throttle.ts
Labels: bug
