Repository exadel-inc/esl, pull requests merged in 2023-12, with the labels that each got.

#2079 refactor(esl-media): migrate `esl-media` to use `esl-event-listener` module
  src/modules/esl-media/core/esl-media-registry.event.ts
  src/modules/esl-media/core/esl-media-registry.ts
  src/modules/esl-media/core/esl-media.ts
Labels: enhancement, needs review

#2080 fix(esl-event-listener): batch of esl-event-listener fixes and utilities unification
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/targets/intersection.target.ts
  src/modules/esl-event-listener/core/targets/resize.target.event.ts
  src/modules/esl-event-listener/core/targets/resize.target.ts
  src/modules/esl-event-listener/core/targets/swipe.target.event.ts
  src/modules/esl-event-listener/core/targets/swipe.target.ts
  src/modules/esl-event-listener/test/listener.delegate.test.ts
Labels: bug, needs review

#2094 test(esl-media): improve media lazy tests speed by migrating to jest fakeTimers (1s -> 20ms)
  src/modules/esl-media/test/esl-media.lazy.test.ts
Labels: needs review

#2086 epic(esl-event-listner): `ESLWheelTarget` proxy target to handle long wheel user actions
  pages/src/esl-events-demo/esl-events-demo.less
  pages/src/esl-events-demo/esl-events-demo.ts
  pages/src/esl-events-demo/esl-swipe-demo/esl-swipe-demo-area.less
  pages/src/esl-events-demo/esl-swipe-demo/esl-swipe-demo-area.ts
  pages/src/esl-events-demo/esl-wheel-demo/esl-wheel-demo-area.less
  pages/src/esl-events-demo/esl-wheel-demo/esl-wheel-demo-area.ts
  pages/src/esl-events-demo/log-area/log-area.less
  pages/src/esl-events-demo/log-area/log-area.ts
  pages/src/esl-swipe-demo/esl-swipe-demo-area.ts
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/views/draft/swipe-demo.njk
  pages/views/draft/wheel-demo.njk
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core.ts
  src/modules/esl-event-listener/core/targets/wheel.target.event.ts
  src/modules/esl-event-listener/core/targets/wheel.target.ts
  src/modules/esl-event-listener/test/targets/wheel.test.ts
Labels: feature, needs review

#2093 test(esl-random-text): cover `esl-random-text` with unit tests
  src/modules/esl-random-text/test/esl-random-text.test.ts
Labels: needs review

#2090 docs(esl-share): update README
  src/modules/esl-share/README.md
Labels: documentation, needs review

#2113 fix(esl-panel-group): `has-opened` attribute inconsistent behavior
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-panel-group/test/esl-panel-group.test.ts
Labels: needs review

#2099 feat(esl-popup): `extraClass`/`extraStyle` features and initial refactoring
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: needs review

#2109 ESLShare pre release updates
  pages/src/esl-share/esl-share.less
  pages/views/draft/share-regression.njk
  pages/views/examples/share.njk
  src/modules/esl-share/actions/print-action.ts
  src/modules/esl-share/core/esl-share-button.less
  src/modules/esl-share/core/esl-share.less
Labels: needs review

#2114 test(esl-utils): improve `aggregated` tests
  src/modules/esl-utils/async/test/aggregate.test.ts
Labels: needs review

#2111 feat(esl-utils): improve `rect` utility (it's almost ready to be immutable)
  src/modules/esl-popup/core/esl-popup-position.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-utils/dom.ts
  src/modules/esl-utils/dom/events/misc.ts
  src/modules/esl-utils/dom/point.ts
  src/modules/esl-utils/dom/rect.ts
  src/modules/esl-utils/dom/test/rect.test.ts
  src/modules/esl-utils/dom/visible.ts
Labels: needs review

#2118 feat(esl-share): add ability to update config items (single one or in batch)
  src/modules/esl-share/core/esl-share-config.ts
  src/modules/esl-share/test/esl-share-config.test.ts
Labels: feature, needs review

#2117 fix(esl-toggleable/esl-popup): fix toggleable and popup flow
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-share/core/esl-share-popup.ts
  src/modules/esl-share/test/esl-share-popup.test.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: bug, needs review

#2112 fix(esl-share): fix focus behavior to a loop inside esl-share-popup
  src/modules/esl-share/core/esl-share-popup.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
  src/modules/esl-utils/dom/focus.ts
Labels: needs review

#1872 test(esl-trigger): cover trigger module with module tests
  src/modules/esl-toggleable/test/toggleable.mock.ts
  src/modules/esl-trigger/README.md
  src/modules/esl-trigger/core/esl-trigger.ts
  src/modules/esl-trigger/test/esl-trigger.a11y.test.ts
  src/modules/esl-trigger/test/esl-trigger.actions.test.ts
  src/modules/esl-trigger/test/esl-trigger.targeting.test.ts
  src/modules/esl-trigger/test/esl-trigger.tracking.test.ts
Labels: needs review

#2120 refactor(esl-note): move `tooltip-shown` marker handling to ESLNote
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: feature, needs review

#2125 chore: add `v4.15.0` public release notes
  pages/views/blogs/ESL v4.15.0.md
  pages/views/examples/menu.njk
  pages/views/index.11tydata.yml
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-forms/esl-select/core/esl-select.ts
Labels: needs review

#2126 fix: esl-popup, esl-tooltip, esl-toggleable hide flow; deprecation of incorrect types; esl-select fixes
  .releaserc.yml
  eslint/README.md
  eslint/src/index.ts
  eslint/src/rules/4/deprecated.alert-action-params.ts
  eslint/src/rules/4/deprecated.deep-compare.ts
  eslint/src/rules/4/deprecated.event-utils.ts
  eslint/src/rules/4/deprecated.generate-uid.ts
  eslint/src/rules/4/deprecated.panel-action-params.ts
  eslint/src/rules/4/deprecated.popup-action-params.ts
  eslint/src/rules/4/deprecated.toggleable-action-params.ts
  eslint/src/rules/4/deprecated.tooltip-action-params.ts
  eslint/src/rules/4/deprecated.traversing-query.ts
  pages/views/examples/footnotes.njk
  pages/views/examples/forms-select-list.njk
  pages/views/examples/forms-select.njk
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-alert/test/alert.request.test.ts
  src/modules/esl-event-listener/core/targets/wheel.target.ts
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-share/core/esl-share-popup.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: bug, enhancement, needs review

#2130 fix(esl-event-listener): fix support for any object-like host
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/test/listener.subscribe.test.ts
Labels: bug, needs review

#2135 epic(site): UIPlayground integration
  package-lock.json
  pages/11ty/htmlmin.transform.js
  pages/package.json
  pages/src/banner/banner.ts
  pages/src/common/badge.less
  pages/src/common/buttons.less
  pages/src/common/code.less
  pages/src/common/colors.less
  pages/src/common/marquee.less
  pages/src/esl-media-demo/test-media-source.ts
  pages/src/esl-media-demo/test-media.ts
  pages/src/localdev.less
  pages/src/localdev.ts
  pages/src/navigation/footer/footer.less
  pages/src/ui-playground/ui-playground.less
  pages/static/assets/common/loader.gif
  pages/static/assets/common/playground.svg
  pages/views/_includes/navigation/sidebar-item.njk
  pages/views/components/esl-media.njk
  pages/views/examples/accordion.njk
  pages/views/examples/embedded-audio.njk
  pages/views/examples/embedded-media.njk
  pages/views/examples/embedded-video.njk
  pages/views/examples/scrollbar.njk
  pages/views/redirect/embedded-audio.njk
  pages/views/redirect/embedded-video.njk
  pages/webpack.config.js
Labels: site, needs review

#2121 feat(esl-toggleable): introducing a base trigger class in purpose to simplify and make Trigger-Toggleable constructions more API strict in ESL
  src/modules/esl-share/core/esl-share.ts
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-trigger/core.ts
  src/modules/esl-trigger/core/esl-base-trigger.ts
  src/modules/esl-trigger/core/esl-trigger.shape.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: enhancement, needs review
