Repository exadel-inc/esl, pull requests merged in 2023-11, with the labels that each got.

#2025 fix(esl-event-utils): `ESLSwipeGestureTarget` target prevents inside element actions
  pages/views/draft/swipe-demo.njk
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core/targets/swipe.target.event.ts
  src/modules/esl-event-listener/core/targets/swipe.target.ts
  src/modules/esl-event-listener/test/targets/swipe.test.ts
Labels: bug, needs review, hotfix

#2014 chore(site): add github reference
  pages/src/navigation/related/related-links.less
  pages/views/_includes/navigation/source-link.njk
  pages/views/_layouts/content.njk
  pages/views/components/esl-a11ty-group.njk
  pages/views/components/esl-alert.njk
  pages/views/components/esl-animate.njk
  pages/views/components/esl-footnotes.njk
  pages/views/components/esl-image.njk
  pages/views/components/esl-media.njk
  pages/views/components/esl-panel-group.njk
  pages/views/components/esl-panel.njk
  pages/views/components/esl-popup.njk
  pages/views/components/esl-scrollbar.njk
  pages/views/components/esl-select-list.njk
  pages/views/components/esl-select.njk
  pages/views/components/esl-share.njk
  pages/views/components/esl-tabs.njk
  pages/views/components/esl-toggleable.njk
  pages/views/components/esl-trigger.njk
  pages/views/core/esl-base-element.njk
  pages/views/core/esl-event-listener.njk
  pages/views/core/esl-media-query.njk
  pages/views/core/esl-mixin-element.njk
  pages/views/core/esl-traversing-query.njk
  pages/views/core/esl-utils.njk
Labels: documentation, needs review

#1981 docs(eslint): ESLint plugin documentation
  eslint/README.md
  pages/views/core/esl-migration-rules.njk
Labels: documentation, needs review

#2018 feat(esl-popup): internal ESLPopup implementation updated to use ESLEventListeners; usage of cached properties reduced
  src/modules/esl-popup/core/esl-popup.ts
Labels: needs review

#2058 fix(esl-scrollbar): fix esl:change:scroll event handler invoked before scrollbar updates
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
Labels: bug, needs review

#821 feat(esl-utils): Transition duration utility
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/test/format.test.ts
Labels: feature, require squash

#2060 feat(esl-panel-group): add ability to enable match-height behavior for tabs height using `esl-tabs-equal-height` class
  pages/views/examples/tabs.njk
  src/modules/esl-panel-group/core/esl-panel-group.less
Labels: feature, needs review

#2061 fix(esl-tabs): fix iOS auto-scroll / arrow controls boundaries on iOS devices when touch-scroll is enabled
  pages/views/draft/tabs-scrollable.njk
  src/modules/esl-tab/core/esl-tabs.ts
Labels: bug, needs review

#2055 feat(esl-random-text): create auxiliary `esl-random-text` component to generate dummy text
  pages/src/localdev.ts
  pages/views/draft/accordion-regression.njk
  src/modules/esl-random-text/README.md
  src/modules/esl-random-text/core.ts
  src/modules/esl-random-text/core/esl-random-text.shape.ts
  src/modules/esl-random-text/core/esl-random-text.ts
Labels: needs review

#2033 Display draft item in sidebar navigation in prod mode when it is current page
  pages/11ty/collections.filter.js
  pages/11ty/hidden.filter.js
  pages/views/_includes/navigation/footer-menu.njk
  pages/views/_includes/navigation/sidebar-item.njk
  pages/views/_includes/navigation/sidebar.njk
  pages/views/_layouts/collection-grid.njk
Labels: site, needs review

#2069 [🚩esl-share]: final follow up
  pages/src/esl-share/esl-share.ts
  pages/views/_includes/navigation/header.njk
  pages/views/_includes/navigation/sidebar.njk
  pages/views/draft/share-regression.njk
  pages/views/examples/share.njk
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-share/core.less
  src/modules/esl-share/core.ts
  src/modules/esl-share/core/esl-share-action-registry.ts
  src/modules/esl-share/core/esl-share-button.ts
  src/modules/esl-share/core/esl-share-config.ts
  src/modules/esl-share/core/esl-share-list.ts
  src/modules/esl-share/core/esl-share-popup-trigger.less
  src/modules/esl-share/core/esl-share-popup-trigger.shape.ts
  src/modules/esl-share/core/esl-share-popup-trigger.ts
  src/modules/esl-share/core/esl-share-popup.ts
  src/modules/esl-share/core/esl-share.less
  src/modules/esl-share/core/esl-share.shape.ts
  src/modules/esl-share/core/esl-share.ts
  src/modules/esl-share/test/actions/copy-action.test.ts
  src/modules/esl-share/test/actions/external-action.test.ts
  src/modules/esl-share/test/actions/media-action.test.ts
  src/modules/esl-share/test/actions/native-action.test.ts
  src/modules/esl-share/test/actions/print-action.test.ts
  src/modules/esl-share/test/esl-share-action-registry.test.ts
  src/modules/esl-share/test/esl-share-button.test.ts
  src/modules/esl-share/test/esl-share-config.test.ts
  src/modules/esl-share/test/esl-share-popup.test.ts
  src/modules/esl-share/test/nested-elements-template.html
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: feature, needs review

#2074 chore: v4.14.1 improvements
  .releaserc.yml
  pages/views/_includes/landing/newsline.njk
  pages/views/_includes/navigation/header.njk
Labels: needs review

#2031 feat(esl-event-listener): inert wheel detector
  src/modules/esl-event-listener/core/targets/wheel.target.event.ts
  src/modules/esl-event-listener/core/targets/wheel.target.ts
Labels: feature, require squash
