Repository exadel-inc/esl, pull requests merged in 2024-04, with the labels that each got.

#2314 fix(esl-popup): fix esl-popup infinitely created independently of placeholder state
  src/modules/esl-popup/core/esl-popup-placeholder.ts
Labels: bug, needs review

#2301 chore(site): ui-playground integration for menu
  site/src/common/dropdown-menu.less
  site/views/examples/menu.njk
Labels: site, needs review

#2318 docs(site): add UIP announce for release 4.15.0 build
  site/views/blogs/ESL v4.15.0.md
  site/views/blogs/UIP 2.0.0 (April).md
Labels: site, maintenance

#2319 [site]: UIP update to `2.1.0-beta.2` (UIP 2 April) + ESL Toggleable examples migration
  package-lock.json
  site/package.json
  site/src/playground/ui-playground.less
  site/views/examples/menu.njk
  site/views/examples/tabs.njk
  site/views/examples/toggleable.njk
Labels: site, maintenance, require squash

#2284 feat(esl carousel) rework css carousel
  site/views/draft/slide-carousel.njk
  src/modules/esl-carousel/core.less
  src/modules/esl-carousel/core.ts
  src/modules/esl-carousel/renderers/esl-carousel.css-only.renderer.less
  src/modules/esl-carousel/renderers/esl-carousel.css-only.renderer.ts
Labels: enhancement, needs review

#2327 [maintain] Porting build and lint changes for `4.16.0`
  .commitlintrc.yml
  .eslintrc.yml
  eslint/src/index.ts
  eslint/src/rules/4/all.rules.ts
  eslint/src/rules/5/all.rules.ts
  eslint/src/rules/5/deprecated.alert-action-params.ts
  eslint/src/rules/5/deprecated.panel-action-params.ts
  eslint/src/rules/5/deprecated.popup-action-params.ts
  eslint/src/rules/5/deprecated.tooltip-action-params.ts
  package.json
  site/11ty/env.config.js
Labels: maintenance, needs review

#2325 [maintain] Porting `attr` related changes for `4.16.0`
  src/modules/esl-utils/decorators/attr.ts
  src/modules/esl-utils/decorators/test/attr.test.ts
  src/modules/esl-utils/dom/attr.ts
  src/modules/esl-utils/dom/test/attr.test.ts
Labels: maintenance, needs review

#2328 [maintain] Porting `esl-base-trigger` changes for `4.16.0`
  src/modules/esl-share/core/esl-share.ts
  src/modules/esl-tab/core/esl-tab.ts
  src/modules/esl-trigger/core.ts
  src/modules/esl-trigger/core/esl-base-trigger.ts
  src/modules/esl-trigger/core/esl-trigger.shape.ts
  src/modules/esl-trigger/core/esl-trigger.ts
Labels: maintenance, needs review

#2329 [maintain] Porting `esl-share` changes for `4.16.0`
  src/modules/esl-share/README.md
  src/modules/esl-share/actions/copy-action.ts
  src/modules/esl-share/buttons/copy.ts
  src/modules/esl-share/core/esl-share-config.ts
  src/modules/esl-share/test/actions/copy-action.test.ts
  src/modules/esl-share/test/esl-share-button.test.ts
  src/modules/esl-share/test/esl-share-config.test.ts
Labels: maintenance, needs review

#2332 [maintanance]: v4.16.0 promo release notes
  site/views/blogs/ESL v4.15.0.md
  site/views/blogs/ESL v4.16.0.md
  site/views/index.11tydata.yml
Labels: site, needs review

#2185 epic(esl carousel): esl-carousel component initial beta
  package.json
  site/src/common/card.less
  site/src/esl-carousel-demo/test-carousel.less
  site/src/localdev.less
  site/src/localdev.ts
  site/views/examples/carousel.11tydata.yml
  site/views/examples/carousel.marquee.11tydata.yml
  site/views/examples/carousel.marquee.njk
  site/views/examples/carousel.njk
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-carousel/README.md
  src/modules/esl-carousel/all.less
  src/modules/esl-carousel/core.less
  src/modules/esl-carousel/core.ts
  src/modules/esl-carousel/core/esl-carousel.events.ts
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.types.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.utils.ts
  src/modules/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
  src/modules/esl-carousel/plugin/esl-carousel.plugin.ts
  src/modules/esl-carousel/plugin/keyboard/esl-carousel.keyboard.mixin.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.arrows.less
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.dots.less
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.dots.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.mixin.ts
  src/modules/esl-carousel/plugin/relation/esl-carousel.relation.mixin.ts
  src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
  src/modules/esl-carousel/plugin/wheel/esl-carousel.wheel.mixin.ts
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.less
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.none.renderer.ts
  src/modules/esl-carousel/test/common/esl-carousel.dummy.renderer.ts
  src/modules/esl-carousel/test/core/esl-carousel.nav.test.ts
  src/modules/esl-carousel/test/core/esl-carousel.renderer.test.ts
  src/modules/esl-carousel/test/plugin/touch/esl-carousel.touch.mixin.test.ts
  src/modules/esl-event-listener/core/targets/swipe.target.event.ts
  src/modules/esl-utils/async/promise/animation.ts
  src/modules/esl-utils/misc/enum.ts
Labels: feature, needs review

#2335 feat(esl-carousel): rework `ESLCarouselNavDots` plugin, improve a11ty
  site/src/common/reboot.less
  site/views/examples/carousel.njk
  src/modules/esl-carousel/all.less
  src/modules/esl-carousel/core.ts
  src/modules/esl-carousel/plugin/dots/README.md
  src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.less
  src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.dots.less
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.dots.ts
Labels: enhancement, needs review

#2350 refactor(esl-carousel): rename `data-slides-area` container to mo obvious `esl-carousel-slides`
  site/src/esl-carousel-demo/test-carousel.less
  site/src/landing/overview/overview.less
  site/views/_includes/landing/overview.njk
  site/views/examples/carousel.marquee.njk
  site/views/examples/carousel.njk
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/plugin/dots/README.md
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.less
Labels: enhancement

#2336 feat(esl-event-listener): separate intersection events
  src/modules/esl-event-listener/core/targets/intersection.event.ts
  src/modules/esl-event-listener/core/targets/intersection.target.ts
  src/modules/esl-event-listener/test/targets/intersection.test.ts
  src/modules/esl-popup/core/esl-popup.ts
Labels: enhancement, needs review

#2344 refactor(esl-event-listener): event's `type` is now replaced with `TYPE`
  src/modules/esl-event-listener/core/targets/resize.target.event.ts
  src/modules/esl-event-listener/core/targets/resize.target.ts
  src/modules/esl-event-listener/core/targets/swipe.target.event.ts
  src/modules/esl-event-listener/core/targets/swipe.target.ts
  src/modules/esl-event-listener/core/targets/wheel.target.event.ts
  src/modules/esl-event-listener/core/targets/wheel.target.ts
Labels: needs review

#2351 feat(esl-carousel): `container-class` slide implementation
  src/modules/esl-carousel/core/esl-carousel.slide.ts
Labels: needs review

#2349 [carousel]: refactoring for default renderer and utils
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.utils.ts
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
  src/modules/esl-carousel/test/core/esl-carousel.nav.test.ts
Labels: needs review

#2353 fix(site): `esl-animate` example page wrong animation
  site/views/examples/animate.njk
Labels: bug, site, needs review

#2279 add the ability to use additional attributes in loadScript utility
  src/modules/esl-utils/dom/script.ts
  src/modules/esl-utils/dom/test/script.test.ts
Labels: feature, needs review

#2354 feat(esl-utils): add provider function support into `@prop` decorator
  src/modules/esl-utils/decorators/prop.ts
  src/modules/esl-utils/decorators/test/prop.test.ts
Labels: feature, needs review

#2352 fix: esl-carousel-dots implementation bugfixes
  src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.less
  src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.ts
Labels: bug

#2356 [🔧 esl-carousel]: migration carousel slide `esl-carousel-slide` to Mixin representation
  site/src/esl-carousel-demo/test-carousel.less
  site/views/_includes/landing/overview.njk
  site/views/examples/carousel.marquee.njk
  site/views/examples/carousel.njk
  site/views/index.njk
  src/modules/esl-carousel/core/esl-carousel.events.ts
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.utils.ts
  src/modules/esl-carousel/plugin/dots/README.md
  src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.less
  src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.mixin.ts
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.less
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
  src/modules/esl-carousel/test/core/esl-carousel.collection.test.ts
  src/modules/esl-carousel/test/core/esl-carousel.renderer.test.ts
  src/modules/esl-utils/decorators/test/prop.test.ts
Labels: bug, enhancement, needs review

#2367 feat(esl-carousel): add handler for 'esl-show-request'
  site/views/examples/carousel.njk
  src/modules/esl-carousel/core/esl-carousel.ts
Labels: feature, require squash, needs review

#2371 fix(esl-animate): fix handling of `esl-animate-mixin` attribute changes
  src/modules/esl-animate/core/esl-animate-mixin.ts
Labels: bug

#2355 refactor(esl-utils): remove `DeviceDetector` use from code
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-footnotes/core/esl-note.ts
  src/modules/esl-image/core/esl-image-iobserver.ts
  src/modules/esl-media-query/core/common/env-shortcuts.ts
  src/modules/esl-media-query/core/common/screen-dpr.ts
  src/modules/esl-media-query/test/esl-media-query.test.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-trigger/core/esl-base-trigger.ts
  src/modules/esl-trigger/test/esl-trigger.actions.test.ts
  src/modules/esl-utils/fixes/viewport.ts
  src/modules/esl-utils/test/deviceDetector.mock.ts
Labels: enhancement, needs review

#2368 refactor(esl-carousel): replace default arrow implementation with a clip-path
  site/views/examples/carousel.marquee.njk
  site/views/examples/carousel.njk
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.arrows.less
Labels: feature

#2372 fix(esl-event-listener): fix `listen` decorator strict types are incorrect
  src/modules/esl-event-listener/test/listener.delegate.test.ts
  src/modules/esl-utils/decorators/listen.ts
  src/modules/esl-utils/decorators/test/listen.test.ts
Labels: bug
