Repository exadel-inc/esl, pull requests merged in 2024-02, with the labels that each got.

#2202 refactor(esl-carousel): carousel touch plugin reworked to respect the most of conflict touch actions
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
  src/modules/esl-carousel/test/common/esl-carousel.dummy.renderer.ts
  src/modules/esl-carousel/test/plugin/touch/esl-carousel.touch.mixin.test.ts
Labels: enhancement, needs review

#2182 chore(site): ui-playground integration for image component
  site/views/examples/image.njk
Labels: site, needs review

#2183 ESLPopup, ESLShare: docs updating
  site/views/_includes/popup.njk
  site/views/draft/popup-scroll-parents.njk
  src/modules/esl-popup/README.md
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-share/README.md
  src/modules/esl-share/core/esl-share-config.ts
Labels: documentation, needs review

#2198 ESLPopup: rework styles to use CSS variables
  site/src/navigation/header/header.less
  src/modules/esl-popup/README.md
  src/modules/esl-popup/core.less
  src/modules/esl-popup/core.mixin.less
  src/modules/esl-popup/core/esl-popup.less
  src/modules/esl-popup/core/esl-popup.mixin.less
Labels: feature, needs review

#2211 chore(site): replace usages of `--100vh` hack with dvh units
  site/src/localdev.ts
  site/src/navigation/sidebar/sidebar.less
  site/src/page/base-layout.less
Labels: site

#2224 feat(esl-carousel-rework): fix jumping during commit animation & fix the final position of the slide
  src/modules/esl-carousel/renderers/multi/esl-multi-carousel.ts
Labels: bug

#2234 docs(e2e): root `e2e` submodule README created with the module instructions
  e2e/README.md
Labels: documentation

#2127 epic: integration tests (v5+)
  .eslintrc.yml
  .github/workflows/e2e.yml
  .gitignore
  e2e/.eslintignore
  e2e/README.md
  e2e/jest-puppeteer.config.js
  e2e/jest.config.js
  e2e/package.json
  e2e/reporters/printers.js
  e2e/reporters/reporter.js
  e2e/setup/image.ts
  e2e/setup/scenarios.env.ts
  e2e/setup/scenarios.screenshot.ts
  e2e/setup/scenarios.ts
  e2e/setup/scenarios.wait.ts
  e2e/setup/scenarious.world.ts
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-screen-1-snap.png
  e2e/tests/homepage.feature
  e2e/transformer/gherkin.d.ts
  e2e/transformer/gherkin.js
  e2e/tsconfig.json
  linting/tests.eslintrc.yml
  package-lock.json
  package.json
  site/.eleventy.js
  site/11ty/env.config.js
  site/11ty/open.postaction.js
  site/package.json
  site/src/common/reboot.less
  site/src/e2e.less
  site/static/assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
  site/static/assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
  site/views/_layouts/base.njk
Labels: needs review

#2238 chore: job to update snapshots
  .github/workflows/e2e.yml
  .husky/pre-push
  e2e/README.md
Labels: enhancement, needs review

#2233 refactor(lint): add commit lint scope validation
  .commitlintrc.yml
  docs/COMMIT_CONVENTION.md
  src/modules/esl-event-listener/test/targets/swipe.test.ts
Labels: needs review

#2228 feat(esl-utils): extend `attr` decorator with inherit option
  src/modules/esl-utils/decorators/attr.ts
  src/modules/esl-utils/decorators/test/attr.test.ts
  src/modules/esl-utils/dom/attr.ts
  src/modules/esl-utils/dom/test/attr.test.ts
Labels: feature, needs review

#2240 ESL Popup position: tests and refactoring
  src/modules/esl-popup/core/esl-popup-position.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-popup/test/esl-popup-position.behaviour-fit-major.test.ts
  src/modules/esl-popup/test/esl-popup-position.behaviour-fit-minor.test.ts
  src/modules/esl-popup/test/esl-popup-position.behaviour-fit.test.ts
  src/modules/esl-popup/test/esl-popup-position.behaviour-none.test.ts
  src/modules/esl-popup/test/esl-popup-position.test.ts
  src/modules/esl-utils/dom/test/window.test.ts
Labels: needs review
