Repository exadel-inc/esl, pull requests merged in 2024-05, with the labels that each got.

#2373 refactor(esl-carousel): touch action rewritten to use `PointerEvents` API
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
Labels: enhancement, needs review

#2280 test(e2e): 'find element by selector' directive
  e2e/README.md
  e2e/setup/element/scenarios.query.ts
  e2e/setup/scenarios.screenshot.ts
  e2e/setup/scenarios.ts
  e2e/setup/scenarios.world.ts
Labels: e2e

#2282 test(e2e): attribute and class directives
  e2e/setup/element/scenarios.attr.ts
  e2e/setup/element/scenarios.class.ts
  e2e/setup/scenarios.ts
Labels: e2e

#2308 test(e2e): test snippet
  e2e/setup/scenarios.screenshot.ts
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-screen-1-snap.png
  e2e/tests/__image_snapshots__/test-feature-feature-test-page-looks-fine-test-page-screen-1-snap.png
  e2e/tests/test.feature
  site/views/_layouts/test.njk
  site/views/test/test-page.njk
Labels: e2e

#2394 test(e2e): finding element by xpath
  e2e/setup/element/scenarios.xpath.ts
  e2e/setup/scenarios.ts
Labels: e2e

#2386 feat(esl-event-listener): add a `group` key to process batch subscription operations
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/types.ts
  src/modules/esl-event-listener/test/listener.unsubscribe.test.ts
Labels: feature, needs review

#2396 feat(esl-event-listener): support of smart subscription when `condition` is used; rework warning system
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/test/listener.resubscribe.test.ts
  src/modules/esl-event-listener/test/listener.subscribe.test.ts
  src/modules/esl-event-listener/test/targets/decorator.test.ts
Labels: enhancement, feature, needs review

#2391 feat(esl-utils): add ability to reject promisifyEvent by using AbortSignal
  src/modules/esl-utils/async/promise/event.ts
  src/modules/esl-utils/async/test/promise/event.test.ts
Labels: feature, needs review

#2389 epic(e2e): e2e tests improvements and extendtion
  .codeclimate.yml
  e2e/README.md
  e2e/setup/element/scenarios.attr.ts
  e2e/setup/element/scenarios.basic.ts
  e2e/setup/element/scenarios.class.ts
  e2e/setup/element/scenarios.events.ts
  e2e/setup/element/scenarios.query.ts
  e2e/setup/element/scenarios.utils.ts
  e2e/setup/element/scenarios.xpath.ts
  e2e/setup/scenarios.env.ts
  e2e/setup/scenarios.page.ts
  e2e/setup/scenarios.screen.ts
  e2e/setup/scenarios.screenshot.ts
  e2e/setup/scenarios.ts
  e2e/setup/scenarios.wait.ts
  e2e/setup/scenarious.world.ts
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-footer-on-desktop-1-snap.png
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-footer-on-mobile-1-snap.png
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-hamburger-menu-on-mobile-1-snap.png
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-screen-1-snap.png
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-screen-on-mobile-1-snap.png
  e2e/tests/__image_snapshots__/test-feature-feature-test-page-looks-fine-test-page-screen-1-snap.png
  e2e/tests/homepage.feature
  e2e/tests/test.feature
  site/src/e2e.less
  site/views/_layouts/test.njk
  site/views/test/test-page.njk
Labels: needs review, e2e

#2412 fix(esl-event-listener): `ESLEventUtils.descriptors` api notes correction
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core/api.ts
Labels: enhancement, needs review

#2416 refactor(esl-media): event resubscribtion and resize target
  src/modules/esl-media/core/esl-media.ts
Labels: needs review

#2417 feat(esl-media): add ability to provide video initial position (start time)
  site/views/examples/embedded-media.njk
  src/modules/esl-media/README.md
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-media/providers/brightcove-provider.ts
  src/modules/esl-media/providers/html5/audio-provider.ts
  src/modules/esl-media/providers/html5/media-provider.ts
  src/modules/esl-media/providers/html5/video-provider.ts
  src/modules/esl-media/providers/youtube-provider.ts
Labels: feature, needs review

#2421 fix(esl-popup): it is not possible to set the offset-arrow to 0
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/test/format.test.ts
Labels: bug, needs review

#2422 refactor(esl-scrollbar): drag action rewritten to use `PointerEvent` API
  src/modules/esl-scrollbar/core/esl-scrollbar.less
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
Labels: enhancement, needs review

#2413 feat(esl-event-listener): update listener internal mechanics to store and collect descriptors (with ability to filter them)
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/descriptors.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/core/types.ts
  src/modules/esl-event-listener/test/descriptor.test.ts
  src/modules/esl-utils/decorators/test/listen.test.ts
Labels: enhancement, feature, needs review

#2423 chore(site): fix `unhandled in promise` error while site watch process
  site/.eleventy.js
Labels: site, needs review

#2424 feat(esl-carousel): Default Renderer: the reordering algorithm improved to respect slides semantical order an available limit of slides
  site/views/examples/carousel.marquee.njk
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
Labels: bug, enhancement, needs review

#2428 fix(esl-media): play-in-viewport tolerance changed to 50% (75% before)
  src/modules/esl-media/core/esl-media-iobserver.ts
Labels: bug, needs review

#2427 fix(esl-media): start-time attribute fixes
  src/modules/esl-media/core/esl-media.shape.ts
  src/modules/esl-media/core/esl-media.ts
Labels: needs review

#2432 fix(esl-panel): fix the falsy state of animation in the default open panel in esl-panel-group
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-panel/core/esl-panel.ts
Labels: bug, needs review

#2439 feat(esl-event-listener): add support for criteria-based subscriptions
  src/modules/esl-event-listener/core/api.ts
  src/modules/esl-event-listener/core/descriptors.ts
  src/modules/esl-event-listener/test/listener.resubscribtion.test.ts
  src/modules/esl-event-listener/test/listener.subscribe.test.ts
Labels: enhancement, needs review

#2429 feat(lint): add deprecation warning regarding incorrect direct imports for `attr`, `prop`, `jsonAttr`, `boolAttr`, `listen`
  eslint/src/core/deprecated-path.ts
  eslint/src/index.ts
  eslint/src/rules/4/all.rules.ts
  eslint/src/rules/4/deprecated.base-decorators-path.ts
Labels: enhancement

#2426 feat(esl-popup): add handler for refresh event
  src/modules/esl-popup/README.md
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-utils/dom/traversing.ts
Labels: feature, needs review

#2442 chore(site): add `4.17.0` version site release notes
  site/views/blogs/ESL v4.17.0.md
Labels: site, needs review

#2443 chore(lint): extend ESL ESLint plugin README
  eslint/README.md
  eslint/defaults/es-config-default.eslint.yml
  eslint/defaults/ts-config-default.eslint.yml
Labels: site, needs review
