Repository exadel-inc/esl, pull requests merged in 2024-12, with the labels that each got.

#2783 feat(esl-tooltip): remove disable-arrow attribute
  site/views/draft/share-regression.njk
  src/modules/esl-share/core/esl-share-popup.ts
  src/modules/esl-tooltip/core/esl-tooltip.shape.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: breaking-change, needs review

#2802 ESLPopup: add offset-trigger attribute
  src/modules/esl-popup/README.md
  src/modules/esl-popup/core/esl-popup.shape.ts
  src/modules/esl-popup/core/esl-popup.ts
Labels: feature, needs review

#2776 chore(site): migrate footnotes example on uip
  site/src/playground/ui-playground.ts
  site/views/draft/footnotes-regression.njk
  site/views/examples/footnotes.njk
Labels: site, needs review

#2795 ESLPopup: optimize position calculations + test
  site/views/examples/popup.njk
  src/modules/esl-popup/README.md
  src/modules/esl-popup/core/esl-popup-position.ts
  src/modules/esl-popup/core/esl-popup.less
  src/modules/esl-popup/core/esl-popup.mixin.less
  src/modules/esl-popup/core/esl-popup.shape.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-popup/test/esl-popup-position.behaviour-fit-major..origin-inner.test.ts
  src/modules/esl-popup/test/esl-popup-position.behaviour-fit-minor.origin-inner.test.ts
  src/modules/esl-popup/test/esl-popup-position.behaviour-fit.origin-inner.test.ts
  src/modules/esl-popup/test/esl-popup-position.behaviour-none.origin-inner.test.ts
  src/modules/esl-popup/test/esl-popup.position-config.test.ts
  src/modules/esl-popup/test/popup.mock.ts
Labels: enhancement, needs review

#2809 fix(esl-media): fix conflict of alignment classes, move definition to the main mixin
  site/views/examples/embedded-media.njk
  src/modules/esl-media/core/esl-media-container.less
  src/modules/esl-media/core/esl-media.less
Labels: bug, needs review

#2810 feat(esl-toggleable): revision v2 for ESLToggleable a11y manger and outside actions handling
  site/src/navigation/sidebar/sidebar.ts
  site/views/draft/focus-management.njk
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-toggleable/README.md
  src/modules/esl-toggleable/core.ts
  src/modules/esl-toggleable/core/esl-toggleable-focus.ts
  src/modules/esl-toggleable/core/esl-toggleable-manager.ts
  src/modules/esl-toggleable/core/esl-toggleable.shape.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-utils/dom/focus.ts
  src/modules/esl-utils/dom/test/focus.test.ts
Labels: needs review

#2820 docs: migration guide update according actual state
  site/views/blogs/ESL v5.0.0 Migartion Guide.md
Labels: documentation, needs review

#2833 fix(esl-toggleable): ESLToggleable should ignore activator direct events
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: hotfix

#2821 [site] : site updates 5.0.0 iteration 1
  e2e/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-footer-on-desktop.jpg
  e2e/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-footer-on-mobile.jpg
  e2e/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-hamburger-menu-on-mobile.jpg
  e2e/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-screen-on-mobile.jpg
  e2e/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-screen.jpg
  site/site.yml
  site/src/navigation/sidebar/sidebar-content.less
  site/src/navigation/sidebar/sidebar-primary-nav.less
  site/src/navigation/sidebar/sidebar-seccondary-nav.less
  site/src/navigation/sidebar/sidebar-share.less
  site/src/navigation/sidebar/sidebar.less
  site/src/navigation/sidebar/sidebar.ts
  site/src/playground/ui-playground.ts
  site/views/_includes/navigation/footer-menu.njk
  site/views/_includes/navigation/sidebar-item.njk
  site/views/_includes/navigation/sidebar.njk
  site/views/_layouts/content.njk
  site/views/blogs/ESL v5.0.0 Migartion Guide.md
  site/views/core/esl-eslint-plugin.njk
  site/views/core/esl-event-listener/core-support.njk
  site/views/core/esl-event-listener/extended-targets.njk
  site/views/core/esl-event-listener/index.njk
  site/views/core/esl-event-listener/overview.njk
  site/views/core/esl-event-listener/public-api.njk
  site/views/draft/footnotes-regression.njk
  site/views/examples/footnotes.njk
  src/modules/esl-event-listener/README.md
  src/modules/esl-event-listener/docs/1-overview.md
  src/modules/esl-event-listener/docs/2-public-api.md
  src/modules/esl-event-listener/docs/3-extended-targets.md
  src/modules/esl-event-listener/docs/4-core-support.md
Labels: site

#2759 [Site]: add breadcrumbs
  site/11ty/collections.filter.js
  site/11ty/markdown.shortcut.js
  site/11ty/tree.filter.js
  site/src/navigation/breadcrumbs/breadcrumbs.less
  site/src/navigation/navigation.less
  site/views/_includes/navigation/breadcrumbs.njk
  site/views/_includes/navigation/collection-grid.njk
  site/views/_includes/navigation/header.njk
  site/views/_includes/navigation/sidebar-item.njk
  site/views/_includes/navigation/sidebar.njk
  site/views/_layouts/content.njk
  site/views/blogs/index.njk
  site/views/components/index.njk
  site/views/core/index.njk
  site/views/dev/accordion-regression.njk
  site/views/dev/carousel.11tydata.yml
  site/views/dev/carousel.njk
  site/views/dev/focus-management.njk
  site/views/dev/footnotes-regression.njk
  site/views/dev/index.njk
  site/views/dev/nav-panels.njk
  site/views/dev/nested-accordion.njk
  site/views/dev/popup-game.njk
  site/views/dev/popup-scroll-parents.njk
  site/views/dev/popup-transition.njk
  site/views/dev/share-regression.njk
  site/views/dev/swipe-demo.njk
  site/views/dev/tabs-scrollable.njk
  site/views/dev/wheel-demo.njk
  site/views/draft/index.njk
  site/views/examples/accordion.njk
  site/views/examples/anchornav.njk
  site/views/examples/animate.njk
  site/views/examples/carousel.njk
  site/views/examples/embedded-media.njk
  site/views/examples/esl-drag-to-scroll.njk
  site/views/examples/footnotes.njk
  site/views/examples/forms-select-list.njk
  site/views/examples/forms-select.njk
  site/views/examples/image-utils.njk
  site/views/examples/image.njk
  site/views/examples/index.njk
  site/views/examples/menu.njk
  site/views/examples/notification.njk
  site/views/examples/popup.njk
  site/views/examples/scrollbar.njk
  site/views/examples/share.njk
  site/views/examples/tabs.njk
  site/views/examples/toggleable.njk
  site/views/index.11tydata.yml
  site/views/introduction/index.njk
  site/views/introduction/installation-guide.njk
Labels: site, needs review
