Repository exadel-inc/esl, pull requests merged in 2024-08, with the labels that each got.

#2558 fix(esl-carousel): direction related issues, cleanup internal nav API (rename dir to direction)
  src/modules/esl-carousel/core/esl-carousel.events.ts
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.types.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.utils.ts
  src/modules/esl-carousel/test/core/esl-carousel.nav.test.ts
Labels: enhancement, needs review

#2555 feat(esl-carousel): rework default renderer animation approach (now uses js animation)
  src/modules/esl-carousel/core/esl-carousel.events.ts
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.types.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.utils.ts
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.less
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.grid.renderer.less
  src/modules/esl-carousel/test/core/esl-carousel.nav.test.ts
Labels: enhancement

#2573 feat(esl-utils): add `parseTime`, less restrictive alternative to passed time format
  src/modules/esl-utils/misc/format.ts
  src/modules/esl-utils/misc/test/format.test.ts
Labels: enhancement, needs review

#2577 feat(esl-anchornav): create esl-anchornav to provide anchor navigation
  .commitlintrc.yml
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-footer-on-desktop-1-snap.png
  site/src/esl-anchornav/esl-anchornav.less
  site/src/esl-anchornav/esl-anchornav.ts
  site/src/localdev.less
  site/src/localdev.ts
  site/static/assets/examples/anchornav.svg
  site/views/components/esl-anchornav.njk
  site/views/examples/anchornav.njk
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-anchornav/README.md
  src/modules/esl-anchornav/core.less
  src/modules/esl-anchornav/core.ts
  src/modules/esl-anchornav/core/esl-anchor.less
  src/modules/esl-anchornav/core/esl-anchor.ts
  src/modules/esl-anchornav/core/esl-anchornav-sticked.less
  src/modules/esl-anchornav/core/esl-anchornav-sticked.ts
  src/modules/esl-anchornav/core/esl-anchornav-types.ts
  src/modules/esl-anchornav/core/esl-anchornav.less
  src/modules/esl-anchornav/core/esl-anchornav.ts
  src/modules/esl-utils/dom/scroll/parent.ts
Labels: feature, needs review

#2544 refactor(site): add presentation draft
  .eslintignore
  site/package.json
  site/src/playground/ui-playground.less
  site/src/playground/ui-playground.ts
  site/src/presentation/carousel.less
  site/src/presentation/footer.less
  site/src/presentation/layout.less
  site/src/presentation/sidebar.less
  site/src/presentation/slide.less
  site/src/site.less
  site/src/site.presentation.less
  site/src/site.ts
  site/static/assets/common/open-source.svg
  site/static/assets/common/print.svg
  site/static/assets/common/puzzle-pieces.svg
  site/static/assets/presentation/angular.svg
  site/static/assets/presentation/react.svg
  site/static/assets/presentation/vue.svg
  site/views/_includes/presentation/footer.njk
  site/views/_includes/presentation/header.njk
  site/views/_includes/presentation/sidebar.njk
  site/views/_layouts/base.njk
  site/views/_layouts/presentation.njk
  site/views/overview/index.njk
  site/views/overview/quick/00-intro/00-intro.njk
  site/views/overview/quick/01-overview/00-what-is.njk
  site/views/overview/quick/01-overview/01-goals.njk
  site/views/overview/quick/01-overview/02-stack&compatibility.njk
  site/views/overview/quick/01-overview/03-browser-support.njk
  site/views/overview/quick/01-overview/04-compatibility.njk
  site/views/overview/quick/02-core/00-core.njk
  site/views/overview/quick/02-core/01-custom-tags.njk
  site/views/overview/quick/02-core/02-custom-attributes.njk
  site/views/overview/quick/02-core/03-tag-vs-attribute.njk
  site/views/overview/quick/02-core/04-event-listener.njk
  site/views/overview/quick/02-core/05-esl-utils.njk
  site/views/overview/quick/03-components/00-components.njk
  site/views/overview/quick/03-components/01-component-list.njk
  site/views/overview/quick/03-components/02-flexibility.njk
  site/views/overview/quick/03-components/03-ux-list.njk
  site/views/overview/quick/03-components/04-responsiveness-n-flexibility.njk
  site/views/overview/quick/04-playground/00-playground.njk
  site/views/overview/quick/04-playground/01-isolated&embedded.njk
  site/views/overview/quick/04-playground/02-editor.njk
  site/views/overview/quick/04-playground/03-settings.njk
  site/views/overview/quick/05-outro/outro.njk
  site/views/overview/quick/index.njk
  site/webpack.config.js
Labels: site, needs review

#2595 [esl-carousel] inner API update + fixes
  src/modules/esl-carousel/core/esl-carousel.events.ts
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/esl-carousel.types.ts
  src/modules/esl-carousel/core/esl-carousel.utils.ts
  src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.mixin.ts
  src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
  src/modules/esl-carousel/renderers/esl-carousel.centered.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.grid.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.none.renderer.ts
  src/modules/esl-carousel/test/core/esl-carousel.manip.test.ts
  src/modules/esl-carousel/test/core/esl-carousel.slide.events.test.ts
  src/modules/esl-carousel/test/core/esl-carousel.utils.test.ts
Labels: bug, enhancement, feature

#2607 fix(esl-image-utils): de-scope (img-cover, img-contain) classes
  src/modules/esl-image-utils/core/esl-image-utils.container.less
Labels: enhancement

#2606 [ESLAnchornav] updates
  site/src/esl-anchornav/esl-anchornav.ts
  site/views/examples/anchornav.njk
  src/modules/esl-anchornav/core.ts
  src/modules/esl-anchornav/core/esl-anchornav-types.ts
  src/modules/esl-anchornav/core/esl-anchornav.ts
Labels: needs review

#2601 fix(site): share preview cards
  site/site.yml
  site/static/assets/social-card.png
  site/views/_layouts/base.njk
  site/views/examples/animate.njk
  site/views/examples/share.njk
Labels: bug, site, needs review

#2609 fix(esl-carousel): fix slide mixin initialization order
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-carousel/core/esl-carousel.ts
Labels: bug
