Repository exadel-inc/esl, pull requests merged in 2024-10, with the labels that each got.

#2691 chore(lint): unite eslint rules
  eslint-plugin/README.md
  eslint-plugin/src/core/deprecated-alias.ts
  eslint-plugin/src/core/deprecated-class-method.ts
  eslint-plugin/src/rules/4/all.rules.ts
  eslint-plugin/src/rules/4/deprecated.aliases.ts
  eslint-plugin/src/rules/4/deprecated.class-methods.ts
  eslint-plugin/src/rules/4/deprecated.deep-compare.ts
  eslint-plugin/src/rules/4/deprecated.event-utils.ts
  eslint-plugin/src/rules/4/deprecated.generate-uid.ts
  eslint-plugin/src/rules/4/deprecated.import.ts
  eslint-plugin/src/rules/4/deprecated.media-rule-list-parse.ts
  eslint-plugin/src/rules/4/deprecated.toggleable-action-params.ts
  eslint-plugin/src/rules/4/deprecated.traversing-query.ts
  eslint-plugin/src/rules/5/all.rules.ts
  eslint-plugin/src/rules/5/deprecated.alert-action-params.ts
  eslint-plugin/src/rules/5/deprecated.aliases.ts
  eslint-plugin/src/rules/5/deprecated.panel-action-params.ts
  eslint-plugin/src/rules/5/deprecated.popup-action-params.ts
  eslint-plugin/src/rules/5/deprecated.tooltip-action-params.ts
Labels: needs review

#2696 style(site): add support for third level navigation
  site/src/navigation/sidebar/sidebar-primary-nav.less
  site/src/navigation/sidebar/sidebar-seccondary-nav.less
  site/src/navigation/sidebar/sidebar.less
  site/views/_includes/navigation/footer-menu.njk
  site/views/_includes/navigation/sidebar-item.njk
  site/views/_includes/navigation/sidebar.njk
  site/views/core/esl-event-listener.njk
  site/views/core/esl-event-listener/basic-concepts.njk
  site/views/core/esl-event-listener/extended-behavior.njk
  site/views/core/esl-event-listener/extended-event-targets.njk
  site/views/core/esl-event-listener/index.njk
  site/views/core/esl-event-listener/public-api.njk
  src/modules/esl-event-listener/README.md
Labels: site

#2670 test(e2e): handle sanpshot's size mismatch
  e2e/setup/serializers/image-snapshot.matcher.ts
  e2e/setup/serializers/image-snapshot.pocessor.ts
  e2e/setup/serializers/image-snapshot.sharp.ts
Labels: needs review, e2e

#2714 fix(esl-drag-to-scroll): fix propagation of the click if drag detected
  src/modules/esl-drag-to-scroll/core/esl-drag-to-scroll.mixin.ts
Labels: bug

#2713 fix(esl-carousel): esl-carousel tag is not declared to be used in TSX
  src/modules/esl-carousel/core.ts
  src/modules/esl-carousel/core/esl-carousel.shape.ts
  src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.shape.ts
Labels: bug

#2690 feat(esl-footnotes): migrate esl-note to esl-base-trigger
  src/modules/esl-footnotes/core/esl-note.less
  src/modules/esl-footnotes/core/esl-note.ts
Labels: enhancement, needs review
