Repository exadel-inc/esl, pull requests merged in 2024-11, with the labels that each got.

#2732 feat(esl-footnotes): claenup readonly API of `esl-note`
  src/modules/esl-footnotes/README.md
  src/modules/esl-footnotes/core/esl-note.ts
Labels: bug, breaking-change

#2733 site: nav updates, 5.0.0 migration guide for blogs section
  site/src/navigation/sidebar/sidebar-content.less
  site/src/navigation/sidebar/sidebar-seccondary-nav.less
  site/src/navigation/sidebar/sidebar.less
  site/views/_includes/navigation/sidebar-item.njk
  site/views/_layouts/content.njk
  site/views/blogs/ESL v5.0.0 Migartion Guide.md
  site/views/core/esl-event-listener/index.njk
Labels: documentation, site

#2747 [🚀 ESL Popup] add position-origin attribute
  site/views/draft/popup-game.njk
  src/modules/esl-popup/README.md
  src/modules/esl-popup/core/esl-popup-position.ts
  src/modules/esl-popup/core/esl-popup.ts
Labels: feature, needs review

#2745 feat(esl-utils): `safeContains` traverse utility
  src/modules/esl-utils/dom/traversing.ts
Labels: enhancement, needs review

#2766 feat(esl-toggleale/esl-popup): focus management cleanup (v2)
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-share/core/esl-share-popup.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: enhancement, needs review

#2765 fix(esl-tooltip): fix tooltip arrow disappearing
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: bug, needs review

#2760 fix(esl-utils): fix visibility and a11y checks for getKeyboardFocusableElements
  src/modules/esl-utils/dom/focus.ts
  src/modules/esl-utils/dom/test/focus.test.ts
Labels: bug, needs review

#2764 fix(esl-footnotes): fix improper note highlighting
  src/modules/esl-footnotes/core/esl-note.ts
Labels: bug, needs review

#2753 feat: ESLTogglable based focus management (UPDATED v2)
  docs/COMMIT_CONVENTION.md
  site/views/components/esl-panel-group.njk
  site/views/components/esl-toggleable.njk
  site/views/examples/image.njk
  src/modules/esl-carousel/renderers/esl-carousel.none.renderer.ts
  src/modules/esl-image/README.md
  src/modules/esl-image/core/esl-image.shape.ts
  src/modules/esl-panel-group/README.md
  src/modules/esl-panel-group/core/esl-panel-group.shape.ts
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-share/actions/external-action.ts
  src/modules/esl-share/core/esl-share-popup.shape.ts
  src/modules/esl-share/core/esl-share-popup.ts
  src/modules/esl-toggleable/README.md
  src/modules/esl-toggleable/core/esl-toggleable.shape.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
  src/modules/esl-utils/async/delayed-task.ts
  src/modules/esl-utils/dom/focus.ts
  src/modules/esl-utils/dom/rtl.ts
Labels: enhancement, feature, needs review

#2771 fix: ESLToggleable fix focus flow for nested cases. Introducing focus manager
  eslint-config/rules/eslint.config.codestyle.js
  site/views/draft/focus-management.njk
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-toggleable/core.ts
  src/modules/esl-toggleable/core/esl-toggleable-focus.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
  src/modules/esl-utils/dom/focus.ts
Labels: bug, needs review, hotfix

#2775 fix(esl-toggleable): fix focus should return to activator
  src/modules/esl-toggleable/core/esl-toggleable-focus.ts
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: bug, hotfix
