Repository exadel-inc/esl, pull requests merged in 2024-03, with the labels that each got.

#2257 fix(esl-toggleable): outside action should be handled from entire page
  src/modules/esl-toggleable/core/esl-toggleable.ts
Labels: bug, needs review

#2209 chore(site): ui-playground integration for tabs component
  package-lock.json
  site/package.json
  site/src/common/body.less
  site/src/common/helpers.less
  site/src/common/tabs.less
  site/src/common/typography.less
  site/src/localdev.less
  site/src/playground/ui-playground.ts
  site/views/examples/tabs.njk
Labels: site, require squash, needs review

#2269 convert Rect to immutable and update popup positioning
  site/src/esl-popup/esl-d-popup-game.ts
  site/src/localdev.ts
  site/views/draft/popup-game.njk
  src/modules/esl-popup/core/esl-popup-position.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-popup/test/esl-popup-position.behaviour-fit-minor.test.ts
  src/modules/esl-popup/test/esl-popup-position.behaviour-fit.test.ts
  src/modules/esl-utils/dom/rect.ts
  src/modules/esl-utils/dom/test/rect.test.ts
Labels: enhancement, require squash
