Repository exadel-inc/esl, pull requests merged in 2024-09, with the labels that each got.

#2625 chore(deps-dev): update ESLint pluggins, migrate lint rules
  .eslintignore
  .eslintrc.yml
  e2e/.eslintignore
  e2e/jest-puppeteer.config.js
  e2e/package.json
  eslint.config.js
  eslint/package.json
  eslint/test/deprecated-alias.invalid.test.ts
  eslint/test/deprecated-alias.valid.test.ts
  eslint/test/deprecated-class-method.test.ts
  linting/coderules.eslintrc.yml
  linting/codestyle.eslintrc.yml
  linting/eslint.config.coderules.js
  linting/eslint.config.codestyle.js
  linting/eslint.config.editorconfig.js
  linting/eslint.config.ignore.js
  linting/eslint.config.import.js
  linting/eslint.config.language.js
  linting/eslint.config.sonarjs.js
  linting/eslint.config.stylistic.js
  linting/eslint.config.tsdoc.js
  linting/eslint.eslintrc.yml
  linting/import.eslintrc.yml
  linting/site.eslintrc.yml
  linting/sonarjs.eslintrc.yml
  linting/tests.eslintrc.yml
  package-lock.json
  package.json
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
  src/modules/esl-image/test/esl-image.test.ts
  src/modules/esl-media/providers/youtube-provider.ts
  src/modules/esl-share/buttons/blogger.ts
  src/modules/esl-share/buttons/copy.ts
  src/modules/esl-share/buttons/facebook.ts
  src/modules/esl-share/buttons/hatena.ts
  src/modules/esl-share/buttons/kakao.ts
  src/modules/esl-share/buttons/line.ts
  src/modules/esl-share/buttons/linkedin.ts
  src/modules/esl-share/buttons/mail.ts
  src/modules/esl-share/buttons/mix.ts
  src/modules/esl-share/buttons/mixi.ts
  src/modules/esl-share/buttons/myspace.ts
  src/modules/esl-share/buttons/native-share.ts
  src/modules/esl-share/buttons/pinterest.ts
  src/modules/esl-share/buttons/print.ts
  src/modules/esl-share/buttons/pusha.ts
  src/modules/esl-share/buttons/reddit.ts
  src/modules/esl-share/buttons/sina-weibo.ts
  src/modules/esl-share/buttons/skype.ts
  src/modules/esl-share/buttons/telegram.ts
  src/modules/esl-share/buttons/tumblr.ts
  src/modules/esl-share/buttons/twitter.ts
  src/modules/esl-share/buttons/viber.ts
  src/modules/esl-share/buttons/whatsapp.ts
  src/modules/esl-share/buttons/wykop.ts
  src/modules/esl-utils/async/debounce.ts
  src/modules/esl-utils/async/throttle.ts
  src/modules/esl-utils/decorators/bind.ts
  src/modules/esl-utils/environment/export-ns.ts
Labels: dependencies, needs review

#2666 feat(esl-drag-to-scroll): create mixin to enable drag-to-scroll functionality
  .commitlintrc.yml
  site/site.yml
  site/src/site.ts
  site/static/assets/examples/drag-to-scroll.svg
  site/views/components/esl-drag-to-scroll.njk
  site/views/examples/esl-drag-to-scroll.njk
  src/modules/all.less
  src/modules/all.ts
  src/modules/esl-drag-to-scroll/README.md
  src/modules/esl-drag-to-scroll/core.less
  src/modules/esl-drag-to-scroll/core.ts
  src/modules/esl-drag-to-scroll/core/esl-drag-to-scroll.less
  src/modules/esl-drag-to-scroll/core/esl-drag-to-scroll.mixin.ts
Labels: feature, needs review

#2667 fix(esl-base-element): fix subscription for component that currently out of DOM
  src/modules/esl-base-element/core/esl-base-element.ts
Labels: bug, needs review

#2682 feat(lint): adapt eslint plugin to be used with ESLint 9
  eslint.config.js
  eslint/jest.config.js
  eslint/package.json
  eslint/src/core/deprecated-alias.ts
  eslint/src/core/deprecated-path.ts
  eslint/src/index.ts
  eslint/src/rules/4/all.rules.ts
  eslint/src/rules/5/all.rules.ts
  eslint/test/deprecated-alias.invalid.test.ts
  eslint/test/deprecated-alias.valid.test.ts
  eslint/test/deprecated-class-method.test.ts
  package-lock.json
  package.json
Labels: bug, needs review

#2684 feat(eslint-config): introducing shared eslint-config for esl projects
  .commitlintrc.yml
  .github/workflows/validate.yml
  .gitignore
  .releaserc.yml
  docs/DEVELOPMENT.md
  eslint-config/README.md
  eslint-config/index.js
  eslint-config/package.json
  eslint-config/rules/eslint.config.coderules.js
  eslint-config/rules/eslint.config.codestyle.js
  eslint-config/rules/eslint.config.editorconfig.js
  eslint-config/rules/eslint.config.import.js
  eslint-config/rules/eslint.config.language.js
  eslint-config/rules/eslint.config.sonarjs.js
  eslint-config/rules/eslint.config.stylistic.js
  eslint-config/rules/eslint.config.tsdoc.js
  eslint-plugin/README.md
  eslint-plugin/defaults/es-config-default.eslint.yml
  eslint-plugin/defaults/ts-config-default.eslint.yml
  eslint-plugin/jest.config.js
  eslint-plugin/package.json
  eslint-plugin/src/core/ast.traverse.ts
  eslint-plugin/src/core/ast.utils.ts
  eslint-plugin/src/core/check-version.ts
  eslint-plugin/src/core/deprecated-alias.ts
  eslint-plugin/src/core/deprecated-class-method.ts
  eslint-plugin/src/core/deprecated-path.ts
  eslint-plugin/src/core/log.ts
  eslint-plugin/src/index.ts
  eslint-plugin/src/rules/4/all.rules.ts
  eslint-plugin/src/rules/4/deprecated.base-decorators-path.ts
  eslint-plugin/src/rules/4/deprecated.deep-compare.ts
  eslint-plugin/src/rules/4/deprecated.event-utils.ts
  eslint-plugin/src/rules/4/deprecated.generate-uid.ts
  eslint-plugin/src/rules/4/deprecated.media-rule-list-parse.ts
  eslint-plugin/src/rules/4/deprecated.toggleable-action-params.ts
  eslint-plugin/src/rules/4/deprecated.traversing-query.ts
  eslint-plugin/src/rules/5/all.rules.ts
  eslint-plugin/src/rules/5/deprecated.alert-action-params.ts
  eslint-plugin/src/rules/5/deprecated.panel-action-params.ts
  eslint-plugin/src/rules/5/deprecated.popup-action-params.ts
  eslint-plugin/src/rules/5/deprecated.tooltip-action-params.ts
  eslint-plugin/test/deprecated-alias.invalid.test.ts
  eslint-plugin/test/deprecated-alias.valid.test.ts
  eslint-plugin/test/deprecated-class-method.test.ts
  eslint-plugin/tsconfig.build.json
  eslint-plugin/tsconfig.json
  eslint.config.ignore.js
  eslint.config.js
  jest.config.js
  package-lock.json
  package.json
  site/views/core/esl-eslint-plugin.njk
  src/modules/esl-drag-to-scroll/core/esl-drag-to-scroll.mixin.ts
Labels: feature, maintenance, needs review

#2626 [ESL Anchornav] final update
  src/modules/esl-anchornav/README.md
  src/modules/esl-anchornav/core/esl-anchornav-sticked.ts
  src/modules/esl-anchornav/core/esl-anchornav.shape.ts
  src/modules/esl-anchornav/core/esl-anchornav.ts
Labels: needs review

#2692 feat(esl-carousel): add attribute to carousel if it has only one slide
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/renderers/esl-carousel.grid.renderer.ts
Labels: feature, needs review
