Repository exadel-inc/esl, pull requests merged in 2024-01, with the labels that each got.

#2145 fix: popup has wrong positioning leads to a broken popup layout
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-utils/dom/test/visible.test.ts
  src/modules/esl-utils/dom/visible.ts
  src/modules/esl-utils/dom/window.ts
Labels: bug

#2165 fix(esl-share): fix merging of `additional`(nested) params when `ESLShareConfig.update` method is called
  src/modules/esl-share/README.md
  src/modules/esl-share/actions/copy-action.ts
  src/modules/esl-share/buttons/copy.ts
  src/modules/esl-share/core/esl-share-config.ts
  src/modules/esl-share/test/actions/copy-action.test.ts
  src/modules/esl-share/test/esl-share-button.test.ts
  src/modules/esl-share/test/esl-share-config.test.ts
Labels: bug, needs review

#2164 feat: esl-carousel renderer flow rework / add vertical config property
  site/views/_layouts/presentation.njk
  src/modules/esl-carousel/core.ts
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.types.ts
  src/modules/esl-carousel/plugin/keyboard/esl-carousel.keyboard.mixin.ts
  src/modules/esl-carousel/renderers/multi/esl-multi-carousel.horizontal.ts
  src/modules/esl-carousel/renderers/multi/esl-multi-carousel.less
  src/modules/esl-carousel/renderers/multi/esl-multi-carousel.ts
  src/modules/esl-carousel/renderers/multi/esl-multi-carousel.vertical.ts
  src/modules/esl-carousel/renderers/slide/esl-slide-carousel.ts
Labels: needs review

#2175 feat: esl-utils `DeviceDetector` deprecation, `TOUCH_EVENTS` removal, and `isReducedMotion` addition
  src/modules/esl-utils/environment/device-detector.ts
Labels: needs review

#2176 refactor(site): avoid of including to sitemap of partial non-styled data from collections
  site/11ty/sitemap.collection.js
  site/site.yml
  site/views/blogs/ESL v4.15.0.md
  site/views/blogs/ESL v5.0.0 Announce.md
  site/views/index.njk
  site/views/sitemap.njk
Labels: bug, site, needs review

#2179 chore(site): ui-playground integration for animate example + UIP update
  package-lock.json
  site/package.json
  site/src/ui-playground/ui-playground.less
  site/views/examples/animate.njk
Labels: site, require squash, needs review

#2180 docs: update development information regarding Node version on the project
  docs/DEVELOPMENT.md
  package-lock.json
  site/package.json
Labels: documentation

#2184 feat(attr): add provider to default value in attr
  src/modules/esl-utils/decorators/attr.ts
  src/modules/esl-utils/decorators/test/attr.test.ts
Labels: feature, needs review

#2194 chore(deps): update husky config
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  package.json
Labels: dependencies

#2190 feat(esl-carousel): add swipe support for ESLCarouselTouchMixin
  site/views/draft/multi-carousel.njk
  site/views/examples/carousel.njk
  src/modules/esl-carousel/README.md
  src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
  src/modules/esl-event-listener/core/targets/swipe.target.event.ts
  src/modules/esl-utils/misc/enum.ts
Labels: enhancement, needs review

#2098 chore(esl-event-listener): block events if scroll was detected
  src/modules/esl-event-listener/core/targets/swipe.target.ts
  src/modules/esl-event-listener/core/targets/wheel.target.ts
  src/modules/esl-utils/dom/scroll/parent.ts
  src/modules/esl-utils/dom/scroll/test/parent.test.ts
  src/modules/esl-utils/dom/scroll/utils.ts
Labels: enhancement, require squash, needs review, finalization

#2201 chore(site): isolated playground base code
  package-lock.json
  site/package.json
  site/src/localdev.less
  site/src/localdev.ts
  site/src/playground/export/lib.less
  site/src/playground/export/lib.ts
  site/src/playground/ui-playground.less
  site/src/playground/ui-playground.ts
  site/webpack.config.js
Labels: site
