Repository exadel-inc/esl, pull requests merged in 2024-07, with the labels that each got.

#2481 feat(esl-carousel + esl-event-listener): Bunch of updates for carousel API, wheel plugin and core wheel target
  src/modules/esl-carousel/core/esl-carousel.events.ts
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
  src/modules/esl-carousel/plugin/esl-carousel.plugin.ts
  src/modules/esl-carousel/plugin/wheel/esl-carousel.wheel.mixin.ts
  src/modules/esl-event-listener/core/targets/wheel.target.ts
  src/modules/esl-event-listener/test/targets/wheel.test.ts
Labels: needs review

#2487 fix(esl-carousel): fix handling of pointercancel event by touch plugin
  site/views/examples/carousel/vertical.sample.njk
  src/modules/esl-base-element/core/esl-base-element.ts
  src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
  src/modules/esl-mixin-element/ui/esl-mixin-element.ts
  src/modules/esl-utils/abstract/component.ts
Labels: enhancement, needs review

#2498 refactor(esl-media-query): deprecate `ESLMediaRuleList.parse`
  src/modules/esl-media-query/README.md
  src/modules/esl-media-query/core/esl-media-rule-list.ts
Labels: needs review

#2499 fix(esl-carousel): make animated carousel area equal to the content without padding
  site/views/examples/carousel/vertical.sample.njk
  src/modules/esl-carousel/core/esl-carousel.less
Labels: bug

#2501 chore(site): fix site sorters, make them generalized
  site/11ty/sort.filter.js
  site/views/_includes/landing/newsline.njk
  site/views/_includes/navigation/footer-menu.njk
  site/views/_includes/navigation/sidebar-item.njk
  site/views/_layouts/collection-grid.njk
  site/views/examples/carousel.njk
Labels: site

#2506 fix(esl-mixin-element): major fix for nested hierarchy mixin disconnection
  src/modules/esl-mixin-element/test/mixin.prototype.test.ts
  src/modules/esl-mixin-element/test/mixin.test.ts
  src/modules/esl-mixin-element/ui/esl-mixin-registry.ts
Labels: needs review

#2509 feat(lint): deprecation rule for `ESlMediaRuleList.parse`
  eslint/README.md
  eslint/src/core/deprecated-class-method.ts
  eslint/src/rules/4/all.rules.ts
  eslint/src/rules/4/deprecated.media-rule-list-parse.ts
  eslint/test/deprecated-class-method.test.ts
  src/modules/esl-image/core/esl-image.ts
  src/modules/esl-media-query/test/esl-media-rule-list.test.ts
  src/modules/esl-panel-group/core/esl-panel-group.ts
  src/modules/esl-tab/core/esl-tabs.ts
Labels: enhancement, needs review

#2510 refactor(lint): fix deprecated-4/media-rule-list-parse rule according live testing notes and introduced utilities
  eslint/src/core/check-version.ts
  eslint/src/core/deprecated-class-method.ts
  eslint/src/core/log.ts
  eslint/src/index.ts
  eslint/src/rules/4/deprecated.media-rule-list-parse.ts
  eslint/test/deprecated-class-method.test.ts
Labels: bug

#2452 feat(esl-media-query): ingore tuple values if query syntax passed
  .eslintrc.yml
  src/modules/esl-media-query/README.md
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-media-query/test/esl-media-rule-list.test.ts
Labels: enhancement, needs review

#2522 refactor(esl-carousel): complete rework of carousel container & events API
  site/src/common/close.less
  site/views/draft/carousel.njk
  site/views/examples/carousel/default.sample.njk
  site/views/examples/carousel/multirow.sample.njk
  site/views/examples/carousel/nav-carousel.sample.njk
  site/views/examples/carousel/siblings.sample.njk
  site/views/examples/carousel/single.sample.njk
  site/views/examples/carousel/vertical.sample.njk
  src/modules/esl-carousel/core/esl-carousel.events.ts
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/core/nav/esl-carousel.nav.utils.ts
  src/modules/esl-carousel/plugin/dots/README.md
  src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.arrows.less
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.mixin.ts
  src/modules/esl-carousel/test/common/esl-carousel.dummy.ts
  src/modules/esl-carousel/test/core/esl-carousel.renderer.test.ts
  src/modules/esl-carousel/test/core/esl-carousel.slide.events.test.ts
Labels: needs review

#2523 feat(esl-carousel): add centered renderer
  site/views/examples/carousel/centered-siblings.sample.njk
  src/modules/esl-carousel/core.ts
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/renderers/esl-carousel.centered.renderer.ts
Labels: feature, needs review

#2524 feat(esl-carousel): rework carousel plugins API to use json attr + smart media query
  site/src/common/close.less
  site/views/examples/carousel/default.sample.njk
  site/views/examples/carousel/multirow.sample.njk
  site/views/examples/carousel/single.sample.njk
  src/modules/esl-carousel/core/esl-carousel.ts
  src/modules/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
  src/modules/esl-carousel/plugin/esl-carousel.plugin.ts
  src/modules/esl-carousel/plugin/keyboard/esl-carousel.keyboard.mixin.ts
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.arrows.less
  src/modules/esl-carousel/plugin/relation/esl-carousel.relation.mixin.ts
  src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
  src/modules/esl-carousel/plugin/wheel/esl-carousel.wheel.mixin.ts
  src/modules/esl-carousel/renderers/esl-carousel.centered.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.grid.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.none.renderer.ts
  src/modules/esl-carousel/test/plugin/touch/esl-carousel.touch.mixin.test.ts
  src/modules/esl-media-query/core/esl-media-rule-list.ts
  src/modules/esl-media-query/test/esl-media-rule-list.test.ts
  src/modules/esl-popup/core/esl-popup.mixin.less
  tsdoc.json
Labels: enhancement, needs review

#2528 fix(esl-carousel): `esl-carousel-dots` does not re-renders after target re-definition
  src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.ts
Labels: bug

#2532 feat(esl-carousel): `esl-carousel-nav` default classes and attributes reworked
  site/views/examples/carousel/centered-siblings.sample.njk
  site/views/examples/carousel/default.sample.njk
  site/views/examples/carousel/multirow.sample.njk
  site/views/examples/carousel/nav-carousel.sample.njk
  site/views/examples/carousel/siblings.sample.njk
  site/views/examples/carousel/single.sample.njk
  site/views/examples/carousel/vertical.sample.njk
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.arrows.less
  src/modules/esl-carousel/plugin/nav/esl-carousel.nav.mixin.ts
Labels: bug, enhancement, needs review

#2538 fix(esl-carousel): fix count of slides to be rendered before the first slide
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.grid.renderer.ts
Labels: bug

#2539 refactor(site): update site contribution banner
  site/src/banner/banner.less
  site/src/banner/banner.ts
  site/src/common/alert.less
  site/src/common/colors.less
  site/src/common/markdown.less
  site/src/navigation/footer/footer-compact.less
  site/views/_data/banner.yml
  site/views/_includes/navigation/banner.njk
  site/views/_includes/navigation/footer-compact.njk
Labels: site, needs review

#2540 refactor(site): introduce missing common utilities and enhancements from presentation branch
  site/11ty/sort.filter.js
  site/11ty/tree.filter.js
  site/src/collection-grid/collection-grid.less
  site/src/common/flex.less
  site/src/common/helpers.less
  site/static/assets/examples/animate.svg
  site/views/_includes/navigation/collection-grid.njk
  site/views/_layouts/collection-grid.njk
  site/views/examples/carousel/siblings.sample.njk
Labels: site, needs review

#2543 refactor(site): rework icons to unify animation, header styles cleanup
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-footer-on-desktop-1-snap.png
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-screen-1-snap.png
  e2e/tests/__image_snapshots__/homepage-feature-feature-homepage-looks-fine-test-homepage-screen-on-mobile-1-snap.png
  site/src/common/typography.large.less
  site/src/common/typography.less
  site/src/localdev.less
  site/src/logo/logo.animation.less
  site/src/navigation/footer/footer.less
  site/src/navigation/header/header.less
  site/src/navigation/navigation.less
  site/static/assets/logo-pretty.svg
  site/static/assets/logo-white.svg
  site/views/_includes/landing/marquee.njk
  site/views/_includes/navigation/header.njk
  site/views/_layouts/landing.njk
Labels: site, needs review

#2552 fix(esl-carousel): multiple carousel touch behavior fixes
  site/views/examples/carousel/centered-siblings.sample.njk
  site/views/examples/carousel/siblings.sample.njk
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/core/esl-carousel.renderer.ts
  src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.grid.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.none.renderer.ts
  src/modules/esl-carousel/test/common/esl-carousel.dummy.renderer.ts
Labels: bug, needs review

#2556 fix(esl-carousel): fix carousel empty state
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/renderers/esl-carousel.grid.renderer.ts
Labels: bug

#2557 fix(esl-carousel): fix incomplete centered carousel rendering
  src/modules/esl-carousel/renderers/esl-carousel.centered.renderer.ts
Labels: bug
