Repository exadel-inc/esl, pull requests merged in 2025-01, with the labels that each got.

#2851 fix(esl-toggleable): inner activator leads to infinite loop while getting toggleables chain
  src/modules/esl-toggleable/core/esl-toggleable-manager.ts
Labels: bug, needs review

#2880 fix(esl-carousel): fix initial rendering layout shift to eliminate CLS degradation
  site/views/dev/carousel-cls.njk
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.less
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
  src/modules/esl-carousel/renderers/esl-carousel.grid.renderer.less
Labels: bug, needs review

#2884 fix(esl-image-utils): omit console warnings in case of missing inner image
  src/modules/esl-image-utils/core/esl-image-container.mixin.ts
Labels: bug

#2893 chore(deps): bump @stylistic/eslint-plugin from 2.13.0 to 3.0.0
  eslint-config/package.json
  package-lock.json
Labels: dependencies, maintenance

#2720 feat(esl-media): observation for togglebale container state
  src/modules/esl-media/README.md
  src/modules/esl-media/core/esl-media-iobserver.ts
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-media/providers/brightcove-provider.ts
  src/modules/esl-media/providers/html5/media-provider.ts
Labels: under discussion
