Repository exadel-inc/esl, pull requests merged in 2025-07, with the labels that each got.

#3205 feat(esl-carousel): add out of the box viewport visibility control for ESL Carousel autoplay plugin
  packages/esl/src/esl-carousel/plugin/autoplay/README.md
  packages/esl/src/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
Labels: needs review

#3215 feat(esl-carousel): major rework state API and nav API to use `ESLCarouselRenderer` instance and public `offset` property
  packages/esl/src/esl-carousel/core/esl-carousel.renderer.registry.ts
  packages/esl/src/esl-carousel/core/esl-carousel.renderer.ts
  packages/esl/src/esl-carousel/core/esl-carousel.ts
  packages/esl/src/esl-carousel/core/esl-carousel.types.ts
  packages/esl/src/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
  packages/esl/src/esl-carousel/renderers/esl-carousel.css.renderer.ts
  packages/esl/src/esl-carousel/renderers/esl-carousel.default.renderer.ts
  packages/esl/src/esl-carousel/renderers/esl-carousel.none.renderer.ts
  packages/esl/src/esl-carousel/test/core/esl-carousel.collection.test.ts
Labels: enhancement, needs review

#3218 fix(esl-popup): fix ESLPopup is still visible when the trigger is outside the viewport
  packages/esl/src/esl-popup/core/esl-popup.ts
Labels: needs review

#3206 fix(esl-media): fix ESLMedia play-in-viewport observes viewport intersection ratio threshold incorrectly
  packages/esl/src/esl-media/README.md
  packages/esl/src/esl-media/core/esl-media-iobserver.ts
  packages/esl/src/esl-media/core/esl-media-manager.ts
  packages/esl/src/esl-media/core/esl-media.shape.ts
  packages/esl/src/esl-media/core/esl-media.ts
  packages/esl/src/esl-media/test/base-provider.livecycle.test.ts
  packages/esl/src/esl-media/test/media-manager.test.ts
Labels: bug, needs review

#3223 feat(esl-carousel): extended esl-carousel-wheel implementation
  packages/esl-website/views/components/esl-carousel/autoplay.njk
  packages/esl-website/views/components/esl-carousel/container-class.njk
  packages/esl-website/views/components/esl-carousel/dots.njk
  packages/esl-website/views/components/esl-carousel/keyboard.njk
  packages/esl-website/views/components/esl-carousel/nav.njk
  packages/esl-website/views/components/esl-carousel/relation.njk
  packages/esl-website/views/components/esl-carousel/touch.njk
  packages/esl-website/views/components/esl-carousel/wheel.njk
  packages/esl/src/esl-carousel/plugin/wheel/README.md
  packages/esl/src/esl-carousel/plugin/wheel/esl-carousel.wheel.mixin.ts
  packages/esl/src/esl-event-listener/core/targets/wheel.target.ts
  packages/esl/src/esl-event-listener/test/targets/wheel.test.ts
Labels: feature, needs review

#3238 feat(esl-event-litener. esl-utils): improve types
  packages/esl/src/esl-base-element/core/esl-base-element.ts
  packages/esl/src/esl-event-listener/core/api.ts
  packages/esl/src/esl-event-listener/core/targets/intersection.event.ts
  packages/esl/src/esl-event-listener/core/targets/swipe.target.event.ts
  packages/esl/src/esl-event-listener/core/targets/wheel.target.event.ts
  packages/esl/src/esl-event-listener/core/types.ts
  packages/esl/src/esl-mixin-element/ui/esl-mixin-element.ts
  packages/esl/src/esl-utils/abstract/component.ts
  packages/esl/src/esl-utils/decorators/listen.ts
  packages/esl/src/esl-utils/misc.ts
  packages/esl/src/esl-utils/misc/functions.ts
  packages/esl/src/esl-utils/misc/types.ts
Labels: enhancement, needs review

#3263 fix(esl-carousel): fix wheel event handling (wheel ignores next slide direction)
  packages/esl/src/esl-carousel/core/esl-carousel.utils.ts
  packages/esl/src/esl-carousel/plugin/wheel/esl-carousel.wheel.mixin.ts
Labels: bug, needs review

#3271 Tech/notes script improvement
  CHANGELOG.md
  scripts/notes.mjs
Labels: maintenance
