Repository exadel-inc/esl, pull requests merged in 2025-02, with the labels that each got.

#2911 fix(esl-media): postpone BrightcoveProvider ready state notification until metadata is available
  src/modules/esl-media/providers/brightcove-provider.ts
Labels: needs review

#2906 fix(esl-media): add play preconditions support for toggle method
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-media/core/esl-media.ts
Labels: require squash, needs review

#2878 feat(esl-media): control mixin
  site/src/site.ts
  site/views/examples/embedded-media.njk
  src/modules/esl-media/control/esl-media-control-mixin.ts
  src/modules/esl-media/core.ts
Labels: feature, require squash, needs review

#2913 refactor(esl-utils): remove `RTL` unnecessary logic
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
  src/modules/esl-tab/core/esl-tabs.ts
  src/modules/esl-utils/dom/rtl.ts
  src/modules/esl-utils/dom/test/rtl.test.ts
Labels: require squash, needs review

#2823 ESLPopup: introduce config for easily acessing params
  src/modules/esl-alert/core/esl-alert.ts
  src/modules/esl-panel/core/esl-panel.ts
  src/modules/esl-popup/core.ts
  src/modules/esl-popup/core/esl-popup-types.ts
  src/modules/esl-popup/core/esl-popup.ts
  src/modules/esl-popup/test/esl-popup.config.test.ts
  src/modules/esl-popup/test/esl-popup.position-config.test.ts
  src/modules/esl-share/core/esl-share-popup.ts
  src/modules/esl-tooltip/core/esl-tooltip.ts
Labels: feature, needs review

#2918 fix(esl-media): detect youtube provider stopped state
  src/modules/esl-media/providers/youtube-provider.ts
Labels: bug, needs review

#2927 fix(esl-event-listener): subscribe descriptors if the host is function/class
  src/modules/esl-event-listener/core/descriptors.ts
  src/modules/esl-event-listener/test/descriptor.test.ts
Labels: bug, require squash

#2939 [esl-media]: refactor instance manager, add support of handling media behavoir inside containers
  site/views/dev/esl-media-regression.njk
  src/modules/esl-media/README.md
  src/modules/esl-media/core.ts
  src/modules/esl-media/core/esl-media-iobserver.ts
  src/modules/esl-media/core/esl-media-manager.ts
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-media/core/esl-media-registry.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-media/providers/brightcove-provider.ts
  src/modules/esl-media/providers/html5/media-provider.ts
  src/modules/esl-media/test/media-manager.test.ts
Labels: require squash, needs review

#2943 test(esl-media): update tests, add BaseProvider & MediaManager livecycle tests
  src/modules/esl-media/test/base-provider.livecycle.test.ts
  src/modules/esl-media/test/base-provider.mock.ts
  src/modules/esl-media/test/base-provider.test.ts
  src/modules/esl-media/test/media-manager.test.ts
  src/modules/esl-media/test/mocks/base-provider.mock.ts
Labels: needs review

#2952 core(site): site updates & release 5.1.0 notes
  e2e/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-footer-on-desktop.jpg
  e2e/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-footer-on-mobile.jpg
  e2e/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-screen-on-mobile.jpg
  e2e/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-screen.jpg
  site/src/common/helpers.less
  site/src/navigation/footer/footer.less
  site/src/navigation/navigation.less
  site/src/navigation/related/aside.less
  site/src/navigation/related/related-links.less
  site/static/assets/common/github.svg
  site/views/_includes/navigation/aside.njk
  site/views/_includes/navigation/collection-grid.njk
  site/views/_includes/navigation/related-links.njk
  site/views/_includes/navigation/sidebar-item.njk
  site/views/_includes/navigation/source-link.njk
  site/views/_layouts/content.njk
  site/views/blogs/ESL v5.1.0.md
  site/views/components/esl-anchornav.njk
  site/views/components/esl-carousel/index.njk
  site/views/components/esl-drag-to-scroll.njk
  site/views/components/esl-image-utils.njk
  site/views/components/esl-lazy-template.njk
  site/views/components/esl-media.njk
  site/views/components/esl-share.njk
  site/views/core/esl-event-listener/index.njk
  site/views/examples/accordion.njk
  site/views/examples/anchornav.njk
  site/views/examples/animate.njk
  site/views/examples/carousel.njk
  site/views/examples/embedded-media.njk
  site/views/examples/esl-drag-to-scroll.njk
  site/views/examples/image-utils.njk
  site/views/examples/lazy-template.njk
  site/views/examples/menu.njk
  site/views/examples/notification.njk
  site/views/examples/scrollbar.njk
  site/views/examples/share.njk
  site/views/examples/tabs.njk
  site/views/examples/toggleable.njk
Labels: needs review

#2942 epic(esl-media): rework commands API, add possibility to restrict play, handle containers
  site/views/dev/esl-media-regression.njk
  site/views/examples/embedded-media.njk
  src/modules/esl-media/README.md
  src/modules/esl-media/control/esl-media-control-mixin.ts
  src/modules/esl-media/core.ts
  src/modules/esl-media/core/esl-media-iobserver.ts
  src/modules/esl-media/core/esl-media-manager.ts
  src/modules/esl-media/core/esl-media-provider.ts
  src/modules/esl-media/core/esl-media-registry.ts
  src/modules/esl-media/core/esl-media.events.ts
  src/modules/esl-media/core/esl-media.ts
  src/modules/esl-media/test/base-provider.livecycle.test.ts
  src/modules/esl-media/test/base-provider.mock.ts
  src/modules/esl-media/test/base-provider.test.ts
  src/modules/esl-media/test/esl-media.condition.test.ts
  src/modules/esl-media/test/media-manager.test.ts
  src/modules/esl-media/test/mocks/base-provider.mock.ts
  src/modules/esl-utils/dom/visible.ts
  src/modules/esl-utils/test/intersectionObserver.mock.ts
Labels: needs review
