Repository exadel-inc/esl, pull requests merged in 2025-03, with the labels that each got.

#2968 epic(eslint-config): rework and restructure eslint-config-esl module
  eslint.config.mjs
  package-lock.json
  packages/eslint-config/README.md
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/eslint-config/rules/base/ecmascript.js
  packages/eslint-config/rules/base/imports.js
  packages/eslint-config/rules/base/index.js
  packages/eslint-config/rules/base/typescript.js
  packages/eslint-config/rules/codestyle/ecmascript.js
  packages/eslint-config/rules/codestyle/editorconfig.js
  packages/eslint-config/rules/codestyle/imports.js
  packages/eslint-config/rules/codestyle/index.js
  packages/eslint-config/rules/codestyle/stylistic.js
  packages/eslint-config/rules/codestyle/typescript.js
  packages/eslint-config/rules/es.base.js
  packages/eslint-config/rules/lang/ecmascript.js
  packages/eslint-config/rules/lang/index.js
  packages/eslint-config/rules/lang/typescript.js
  packages/eslint-config/rules/strict/ecmascript.js
  packages/eslint-config/rules/strict/imports.js
  packages/eslint-config/rules/strict/index.js
  packages/eslint-config/rules/strict/sonarjs.js
  packages/eslint-config/rules/strict/tsdoc.js
  packages/eslint-config/rules/strict/typescript.js
  src/modules/esl-base-element/test/element.test.ts
  src/modules/esl-carousel/plugin/esl-carousel.plugin.ts
  src/modules/esl-event-listener/core/listener.ts
  src/modules/esl-event-listener/test/targets/resize.test.ts
  src/modules/esl-utils/misc/object/test/path.test.ts
Labels: needs review

#2971 fix(stylelint-config): extend @exadel/stylelint-config-esl defaults with the primary rules
  .stylelintrc.yml
  packages/stylelint-config/index.js
Labels: enhancement, needs review

#2970 fix(eslint-config): replace legacy editorconfig-eslint-plugin with direct rules
  package-lock.json
  packages/eslint-config/package.json
  packages/eslint-config/rules/codestyle/editorconfig.js
Labels: bug, needs review

#2973 feat(eslint-config): extend @exadel/eslint-config-esl defaults with sonarjs rules for all levels
  packages/eslint-config/README.md
  packages/eslint-config/rules/base/index.js
  packages/eslint-config/rules/base/sonarjs.js
  packages/eslint-config/rules/codestyle/index.js
  packages/eslint-config/rules/codestyle/sonarjs.js
  packages/eslint-config/rules/strict/sonarjs.js
  src/modules/esl-carousel/core/esl-carousel.slide.ts
  src/modules/esl-image/test/xmlHttpRequest.mock.ts
  src/modules/esl-media-query/core/common/screen-breakpoint.ts
  src/modules/esl-media/providers/youtube-provider.ts
Labels: enhancement, needs review

#2979 refactor(e2e): move `e2e` package to `packages/snapshot-tests`
  .github/workflows/e2e.yml
  .gitignore
  package-lock.json
  package.json
  packages/snapshot-tests/.gitignore
  packages/snapshot-tests/README.md
  packages/snapshot-tests/jest-puppeteer.config.js
  packages/snapshot-tests/jest.config.js
  packages/snapshot-tests/package.json
  packages/snapshot-tests/src/reporters/printers.js
  packages/snapshot-tests/src/reporters/reporter.js
  packages/snapshot-tests/src/scenarios.ts
  packages/snapshot-tests/src/scenarios/element/scenarios.attr.ts
  packages/snapshot-tests/src/scenarios/element/scenarios.basic.ts
  packages/snapshot-tests/src/scenarios/element/scenarios.class.ts
  packages/snapshot-tests/src/scenarios/element/scenarios.events.ts
  packages/snapshot-tests/src/scenarios/element/scenarios.query.ts
  packages/snapshot-tests/src/scenarios/element/scenarios.utils.ts
  packages/snapshot-tests/src/scenarios/element/scenarios.xpath.ts
  packages/snapshot-tests/src/scenarios/scenarios.env.ts
  packages/snapshot-tests/src/scenarios/scenarios.page.ts
  packages/snapshot-tests/src/scenarios/scenarios.screen.ts
  packages/snapshot-tests/src/scenarios/scenarios.screenshot.ts
  packages/snapshot-tests/src/scenarios/scenarios.wait.ts
  packages/snapshot-tests/src/serializers/image-snapshot.composer.ts
  packages/snapshot-tests/src/serializers/image-snapshot.matcher.ts
  packages/snapshot-tests/src/serializers/image-snapshot.pocessor.ts
  packages/snapshot-tests/src/serializers/image-snapshot.sharp.ts
  packages/snapshot-tests/src/serializers/image-snapshot.ts
  packages/snapshot-tests/src/transformer/gherkin.d.ts
  packages/snapshot-tests/src/transformer/gherkin.js
  packages/snapshot-tests/src/utils/directory.d.ts
  packages/snapshot-tests/src/utils/directory.js
  packages/snapshot-tests/src/utils/image-snapshot.name.d.ts
  packages/snapshot-tests/src/utils/image-snapshot.name.js
  packages/snapshot-tests/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-footer-on-desktop.jpg
  packages/snapshot-tests/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-footer-on-mobile.jpg
  packages/snapshot-tests/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-hamburger-menu-on-mobile.jpg
  packages/snapshot-tests/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-screen-on-mobile.jpg
  packages/snapshot-tests/tests/__image_snapshots__/homepage.feature/feature-homepage-looks-fine-test-homepage-screen.jpg
  packages/snapshot-tests/tests/__image_snapshots__/test.feature/feature-test-page-looks-fine-test-page-screen.jpg
  packages/snapshot-tests/tests/homepage.copyright.test.ts
  packages/snapshot-tests/tests/homepage.feature
  packages/snapshot-tests/tests/test.feature
  packages/snapshot-tests/tsconfig.json
Labels: needs review

#2989 fix(esl-scrollbar): inconsistent dragging if target is `html`
  src/modules/esl-scrollbar/core/esl-scrollbar.ts
Labels: bug, needs review

#2985 fix(esl-carousel): fix initial CLS for looped carousels
  src/modules/esl-carousel/README.md
  src/modules/esl-carousel/core/esl-carousel.less
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.less
  src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
Labels: bug, needs review

#2986 refactor(site): introduce single scrollbar for all page layouts
  packages/esl-website/src/landing/benefits/benefits.less
  packages/esl-website/src/navigation/header/header.less
  packages/esl-website/src/navigation/sidebar/sidebar.less
  packages/esl-website/src/page/base-layout.less
  packages/esl-website/src/page/landing-layout.less
  packages/esl-website/src/page/sidebar-layout.less
  packages/esl-website/src/presentation/layout.less
  packages/esl-website/views/_layouts/base.njk
  packages/esl-website/views/_layouts/content.njk
  packages/esl-website/views/_layouts/empty.njk
  packages/esl-website/views/_layouts/landing.njk
  packages/esl-website/views/_layouts/presentation.njk
Labels: site, needs review

#3018 chore(deps): update @exadel/ui-playground to version 2.1.0-beta.10
  package-lock.json
  packages/esl-website/package.json
Labels: needs review

#3017 fix(eslint-config): fix import plugin configuration
  package-lock.json
  packages/eslint-config/README.md
  packages/eslint-config/package.json
  packages/eslint-config/rules/lang/typescript.js
Labels: needs review

#3012 refactor(esl-utils): deprecate `isBot` utility
  packages/esl/src/esl-media-query/core/common/env-shortcuts.ts
  packages/esl/src/esl-media-query/core/common/screen-dpr.ts
  packages/esl/src/esl-media-query/test/esl-media-query.test.ts
  packages/esl/src/esl-utils/environment/device-detector.ts
  packages/esl/src/esl-utils/test/deviceDetector.mock.ts
Labels: require squash, needs review

#3027 docs: update root README.md for the project structure
  README.md
  packages/esl/README.md
  packages/eslint-config/README.md
  packages/eslint-plugin/README.md
  packages/stylelint-config/README.md
Labels: documentation
