Repository exadel-inc/esl, pull requests merged in 2025-08, with the labels that each got.

#3293 feat/carousel slide autoplay timeout
  packages/esl-website/src/common/buttons.less
  packages/esl-website/views/examples/carousel/css-slide-autoplay.sample.njk
  packages/esl/src/esl-animate/test/animate.service.test.ts
  packages/esl/src/esl-carousel/core/esl-carousel.ts
  packages/esl/src/esl-carousel/core/esl-carousel.utils.ts
  packages/esl/src/esl-carousel/plugin/autoplay/README.md
  packages/esl/src/esl-carousel/plugin/autoplay/esl-carousel.autoplay.event.ts
  packages/esl/src/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
  packages/esl/src/esl-carousel/plugin/wheel/esl-carousel.wheel.mixin.ts
  packages/esl/src/esl-carousel/test/plugin/autoplay/esl-carousel.autoplay.control.test.ts
  packages/esl/src/esl-carousel/test/plugin/autoplay/esl-carousel.autoplay.slide.test.ts
  packages/esl/src/esl-carousel/test/plugin/autoplay/esl-carousel.autoplay.test.ts
  packages/esl/src/esl-media/test/base-provider.livecycle.test.ts
  packages/esl/src/esl-media/test/esl-media.condition.test.ts
  packages/esl/src/esl-media/test/esl-media.lazy.test.ts
  packages/esl/src/esl-media/test/media-manager.test.ts
  packages/esl/src/esl-utils/test/intersectionObserver.mock.ts
Labels: needs review

#3301 refactor(site): news section labels refresh
  packages/esl-website/11ty/date.filter.js
  packages/esl-website/src/landing/newsline/newsline.ts
  packages/esl-website/src/site.ts
  packages/esl-website/views/_includes/landing/newsline-item.njk
Labels: enhancement, site, needs review

#3327 [esl-animate]: added CSS variable for transition timing/function
  packages/esl/src/esl-animate/core/esl-animate-animations.less
Labels: needs review

#3333 fix(esl-utils): add tests and validation to prevent prototype pollution (CWE-1321) for `set` and `setByPath` utils
  packages/esl/src/esl-utils/misc/object/path.ts
  packages/esl/src/esl-utils/misc/object/test/path.test.ts
Labels: bug, needs review

#3334 feat(esl-carousel): rework esl-carousel-autoplay plugin to support pause on slides marked with 0 duration; turn autoplay to inactive state if the navigation command is not possible for current carousel state
  packages/esl/src/esl-carousel/plugin/autoplay/README.md
  packages/esl/src/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
  packages/esl/src/esl-carousel/test/plugin/autoplay/esl-carousel.autoplay.slide.test.ts
  packages/esl/src/esl-carousel/test/plugin/autoplay/esl-carousel.autoplay.test.ts
  packages/esl/src/esl-utils/misc/format.ts
  packages/esl/src/esl-utils/misc/test/format.test.ts
Labels: enhancement, needs review
