Repository exadel-inc/esl, pull requests merged in 2025-09, with the labels that each got.

#3339 feat(esl-carousel): esl-carousel-autoplay internal API and state machine completely reworked
  packages/esl/src/esl-carousel/plugin/autoplay/README.md
  packages/esl/src/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
  packages/esl/src/esl-carousel/test/plugin/autoplay/esl-carousel.autoplay.interaction.test.ts
  packages/esl/src/esl-carousel/test/plugin/autoplay/esl-carousel.autoplay.test.ts
Labels: bug, enhancement, needs review

#3351 chore(esl-carousel): rename internal invalidate method to refresh
  packages/esl/src/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
  packages/esl/src/esl-utils/decorators/safe.ts
Labels: needs review

#3256 feat(esl-event-listener): make strict event names type handling
  packages/esl/src/esl-base-element/core/esl-base-element.ts
  packages/esl/src/esl-base-element/test/element.listener.test-d.ts
  packages/esl/src/esl-base-element/test/element.listener.test.ts
  packages/esl/src/esl-base-element/test/element.test.ts
  packages/esl/src/esl-event-listener/core/api.ts
  packages/esl/src/esl-event-listener/core/targets/intersection.target.ts
  packages/esl/src/esl-event-listener/core/targets/resize.target.ts
  packages/esl/src/esl-event-listener/core/targets/swipe.target.ts
  packages/esl/src/esl-event-listener/core/targets/wheel.target.ts
  packages/esl/src/esl-event-listener/core/types.ts
  packages/esl/src/esl-event-listener/test/api.subscribe.test-d.ts
  packages/esl/src/esl-mixin-element/test/mixin.listener.test-d.ts
  packages/esl/src/esl-mixin-element/ui/esl-mixin-element.ts
  packages/esl/src/esl-trigger/test/esl-trigger.a11y.test.ts
  packages/esl/src/esl-utils/abstract/component.ts
  packages/esl/src/esl-utils/decorators/listen.ts
  packages/esl/src/esl-utils/decorators/test/attr.extended.test.ts
  packages/esl/src/esl-utils/decorators/test/attr.test.ts
  packages/esl/src/esl-utils/decorators/test/bool-attr.test.ts
  packages/esl/src/esl-utils/decorators/test/json-attr.test.ts
  packages/esl/src/esl-utils/decorators/test/listen.test-d.ts
  packages/esl/src/esl-utils/decorators/test/listen.test.ts
  packages/esl/src/esl-utils/decorators/test/prop.test.ts
  packages/esl/src/esl-utils/dom/events/target.ts
  packages/esl/src/esl-utils/misc/types.ts
Labels: enhancement, needs review

#3369 chore: add correct distribution channel calculation for NPM CI
  .github/workflows/release-npm.yml
  package.json
  scripts/common/config.mjs
  scripts/get-dist-tag.mjs
Labels: maintenance, needs review

#3382 chore(site): update sidebar links divider to common style
  packages/esl-website/src/navigation/sidebar/sidebar-primary-nav.less
  packages/esl-website/views/_includes/navigation/sidebar.njk
Labels: site

#3378 feat(esl-carousel): introduce capabilities to provide custom autoplay restrictions
  packages/esl/src/esl-carousel/plugin/autoplay/README.md
  packages/esl/src/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
  packages/esl/src/esl-carousel/test/plugin/autoplay/esl-carousel.autoplay.interaction.test.ts
  packages/esl/src/esl-trigger/core/esl-base-trigger.ts
  packages/esl/src/esl-trigger/core/esl-trigger.ts
  packages/esl/src/esl-utils/dom/events/misc.ts
  packages/esl/src/esl-utils/dom/events/test/misc.test.ts
Labels: feature, needs review

#3359 feat(ui-playground): default attribute settings
  packages/esl-website/src/playground/ui-playground.ts
  packages/esl-website/views/dev/popup-game.njk
  packages/esl-website/views/examples/accordion.njk
  packages/esl-website/views/examples/anchornav.njk
  packages/esl-website/views/examples/animate.njk
  packages/esl-website/views/examples/carousel.njk
  packages/esl-website/views/examples/embedded-media.njk
  packages/esl-website/views/examples/esl-drag-to-scroll.njk
  packages/esl-website/views/examples/esl-line-clamp.njk
  packages/esl-website/views/examples/footnotes.njk
  packages/esl-website/views/examples/image-utils.njk
  packages/esl-website/views/examples/image.njk
  packages/esl-website/views/examples/lazy-template.njk
  packages/esl-website/views/examples/menu.njk
  packages/esl-website/views/examples/notification.njk
  packages/esl-website/views/examples/scrollbar.njk
  packages/esl-website/views/examples/tabs.njk
  packages/esl-website/views/examples/toggleable.njk
  packages/esl-website/views/overview/quick/03-components/04-responsiveness-n-flexibility.njk
  packages/esl-website/views/overview/quick/04-playground/02-editor.njk
  packages/esl-website/views/overview/quick/04-playground/03-settings.njk
  packages/ui-playground/src/core/config/config.ts
  packages/ui-playground/src/core/panel/plugin-panel.header.less
  packages/ui-playground/src/core/panel/plugin-panel.horizontal.less
  packages/ui-playground/src/core/panel/plugin-panel.tsx
  packages/ui-playground/src/core/panel/plugin-panel.vertical.less
  packages/ui-playground/src/plugins/editor/editor.tsx
  packages/ui-playground/src/plugins/settings/settings.less
  packages/ui-playground/src/plugins/settings/settings.tsx
  packages/ui-playground/src/registration.all.ts
  packages/ui-playground/src/registration.ts
Labels: enhancement, site, needs review, ui-playground

#3395 docs: esl-utils/decorators
  packages/esl-website/11ty/markdown.shortcut.js
  packages/esl-website/site.yml
  packages/esl-website/views/_includes/navigation/aside.njk
  packages/esl-website/views/core/decorators/attr.njk
  packages/esl-website/views/core/decorators/bind.njk
  packages/esl-website/views/core/decorators/bool-attr.njk
  packages/esl-website/views/core/decorators/decorate.njk
  packages/esl-website/views/core/decorators/index.njk
  packages/esl-website/views/core/decorators/json-attr.njk
  packages/esl-website/views/core/decorators/listen.njk
  packages/esl-website/views/core/decorators/memoize.njk
  packages/esl-website/views/core/decorators/prop.njk
  packages/esl-website/views/core/decorators/ready.njk
  packages/esl-website/views/core/decorators/safe.njk
  packages/esl-website/views/core/esl-eslint-plugin.njk
  packages/esl-website/views/core/esl-event-listener/core-support.njk
  packages/esl-website/views/core/esl-event-listener/extended-targets.njk
  packages/esl-website/views/core/esl-event-listener/index.njk
  packages/esl/src/esl-utils/README.md
  packages/esl/src/esl-utils/decorators/README.md
  packages/esl/src/esl-utils/decorators/attr.ts
  packages/esl/src/esl-utils/decorators/bind.ts
  packages/esl/src/esl-utils/decorators/bool-attr.ts
  packages/esl/src/esl-utils/decorators/decorate.ts
  packages/esl/src/esl-utils/decorators/docs/attr.md
  packages/esl/src/esl-utils/decorators/docs/bind.md
  packages/esl/src/esl-utils/decorators/docs/bool-attr.md
  packages/esl/src/esl-utils/decorators/docs/decorate.md
  packages/esl/src/esl-utils/decorators/docs/json-attr.md
  packages/esl/src/esl-utils/decorators/docs/listen.md
  packages/esl/src/esl-utils/decorators/docs/memoize.md
  packages/esl/src/esl-utils/decorators/docs/prop.md
  packages/esl/src/esl-utils/decorators/docs/ready.md
  packages/esl/src/esl-utils/decorators/docs/safe.md
  packages/esl/src/esl-utils/decorators/listen.ts
  packages/esl/src/esl-utils/decorators/memoize.ts
  packages/esl/src/esl-utils/decorators/prop.ts
  packages/esl/src/esl-utils/decorators/ready.ts
Labels: documentation, needs review

#3406 refactor: remove deprecated properties and methods across ESL
  packages/esl/src/esl-alert/core/esl-alert.ts
  packages/esl/src/esl-event-listener/core/api.ts
  packages/esl/src/esl-event-listener/core/targets/intersection.event.ts
  packages/esl/src/esl-event-listener/core/targets/resize.target.event.ts
  packages/esl/src/esl-event-listener/core/targets/swipe.target.event.ts
  packages/esl/src/esl-event-listener/core/targets/wheel.target.event.ts
  packages/esl/src/esl-media-query/core/common/media-shortcuts.ts
  packages/esl/src/esl-utils/async/promise.ts
  packages/esl/src/esl-utils/dom/rtl.ts
  packages/esl/src/esl-utils/environment/device-detector.ts
  packages/esl/src/esl-utils/misc.ts
  packages/esl/src/esl-utils/misc/array.ts
  packages/esl/src/esl-utils/misc/test/array.test.ts
  packages/eslint-config/rules/custom/configs.js
Labels: breaking-change, needs review
