Repository exadel-inc/esl, pull requests merged in 2025-04, with the labels that each got.

#3030 chore(e2e): update package to ues ts and esm output
  package-lock.json
  packages/snapshot-tests/jest-puppeteer.config.js
  packages/snapshot-tests/jest.config.js
  packages/snapshot-tests/package.json
  packages/snapshot-tests/src/reporters/printers.js
  packages/snapshot-tests/src/reporters/reporter.js
  packages/snapshot-tests/src/serializers/image-snapshot.matcher.ts
  packages/snapshot-tests/src/transformer/gherkin.js
  packages/snapshot-tests/src/utils/directory.js
  packages/snapshot-tests/src/utils/image-snapshot.name.js
  packages/snapshot-tests/tests/homepage.copyright.test.ts
  packages/snapshot-tests/tsconfig.json
Labels: needs review, e2e

#3072 feat(eslint-config): replace `eslint-import-plugin-x` with `eslint-import-plugin`
  package-lock.json
  packages/eslint-config/README.md
  packages/eslint-config/package.json
  packages/eslint-config/rules/base/imports.js
  packages/eslint-config/rules/codestyle/imports.js
  packages/eslint-config/rules/lang/typescript.js
  packages/eslint-config/rules/strict/imports.js
Labels: bug, needs review

#3076 chore: fix nx pipelines for the project, get rid of prepare steps
  nx.json
  package.json
  packages/esl/package.json
  packages/eslint-plugin/package.json
  packages/snapshot-tests/package.json
  packages/snapshot-tests/project.json
Labels: enhancement, needs review
